Feature/100 endpoint validation
svetit-io/svetit pull request #101
Opened 2024-04-18 10:25 UTC by prt0117

2024-05-03 04:57 UTC, lirik90 requested changes

2024-05-03 04:57 UTC, lirik90 commented on pipeline/Makefile
> +	. migrate/venv/bin/activate && pip uninstall -y openapi2jsonschema && make -C ../src/back/deps/swagger2jsonschema build && pip install ../src/back/deps/swagger2jsonschema/dist/openapi2jsonschema-0.1
Вместо этого давай пожалуйста
1. перенесём из pipeline/migrate/migrate.sh кусок инициализации venv в скрипт init_env.sh
2. перенесём файл pipeline/migrate/requirements.txt на уровень выше
3. в скрипте init_env.sh добавим 
```bash
pip install git+https://github.com/lirik90/swagger2jsonschema
```
или если сработает то вместо этого добавим 
```
git+https://github.com/lirik90/swagger2jsonschema
```
в файл requirements.txt

2024-05-03 04:57 UTC, lirik90 commented on src/back/deps/swagger2jsonschema/Dockerfile
> +##################################################
Удали пожалуйста папку src/back/deps/swagger2jsonschema она тут не нужна

2024-05-03 05:21 UTC, prt0117 commented on src/back/deps/swagger2jsonschema/Dockerfile
> +##################################################
Готово.

2024-05-03 06:19 UTC, prt0117 commented on pipeline/Makefile
> +	. migrate/venv/bin/activate && pip uninstall -y openapi2jsonschema && make -C ../src/back/deps/swagger2jsonschema build && pip install ../src/back/deps/swagger2jsonschema/dist/openapi2jsonschema-0.1
Всё получилось (через requirements.txt).

2024-05-03 06:37 UTC, lirik90 requested changes

2024-05-03 06:37 UTC, lirik90 commented on src/back/deps/s2j.Dockerfile
> +WORKDIR /swagger2jsonschema
Проверь пожалуйста будет ли так работать:
```suggestion
WORKDIR /swagger2jsonschema
COPY doc/api/api.yaml .
```

поидее WORKDIR должна будет сама создать папку

2024-05-03 06:37 UTC, lirik90 commented on src/back/deps/s2j.Dockerfile
> +FROM python:3.10
переименуй пожалуйста файл
в swagger2jsonschema.Dockerfile или что то такое

2024-05-03 06:44 UTC, prt0117 commented on src/back/deps/s2j.Dockerfile
> +FROM python:3.10
Готово.

2024-05-03 06:44 UTC, prt0117 commented on src/back/deps/s2j.Dockerfile
> +WORKDIR /swagger2jsonschema
Да, работает, поправил, вливаю.

2024-05-07 03:02 UTC, lirik90 requested changes

2024-05-07 03:02 UTC, lirik90 commented on pipeline/.env.example
> +JSON_SCHEMAS_PATH='/home/user/svetit/doc/api/schemas/'
Нужно использовать относительный путь
```suggestion
JSON_SCHEMAS_PATH='../../../../schemas/'
```

2024-05-07 03:02 UTC, lirik90 commented on src/back/deps/svetit/shared/schemas.hpp
> +	bool loadBody,
loadParams и loadBody не нужны. Если они есть в схеме, то загружаем, если нет, то не загружаем. =)

2024-05-07 08:43 UTC, prt0117 commented on src/back/deps/svetit/shared/schemas.hpp
> +	bool loadBody,
Готово.

2024-05-10 23:46 UTC, lirik90 requested changes

2024-05-10 23:46 UTC, lirik90 commented on src/back/deps/svetit/shared/schemas.cpp
> +	const auto requestBodyPath = path + '/' + boost::algorithm::to_lower_copy(requestBodyParam.As<std::string>());
утилита должна в параметре указывать точный относительный путь к файлу в том числе в правильном регистре
```suggestion
	const auto requestBodyPath = path + '/' + requestBodyParam.As<std::string>();
```

2024-05-10 23:46 UTC, lirik90 commented on src/back/project/src/service/service.cpp
> +std::string Service::GetJSONSchemasPath() {
Значение меняется только при инициализации объекта, поэтому мы можем безопасно вернуть его по ссылке.
```suggestion
const std::string& Service::GetJSONSchemasPath() {
```

2024-05-15 08:33 UTC, prt0117 commented on src/back/deps/svetit/shared/schemas.cpp
> +	const auto requestBodyPath = path + '/' + boost::algorithm::to_lower_copy(requestBodyParam.As<std::string>());
Регистр поправил, теперь всё в нижнем всегда. Влил правку в репу утилиты - пожалуйста, опубликуй в pypi новый пакет.

А насчет относительного пути не понял, так как все генерируемые схемы лежат в одной директории. Относительный путь относительно чего нужно указать? Разве что вот так "./project.json" в параметре писать?

2024-05-17 03:06 UTC, lirik90 requested changes

2024-05-17 03:06 UTC, lirik90 commented on src/back/project/src/repo/table_cc_status_type.hpp
> +	model::CcStatusType Get(int id);
Если в базе поле SERIAL - то тут int
Если BIGSERIAL то тут int64_t

2024-05-17 05:34 UTC, prt0117 commented on src/back/project/src/repo/table_cc_status_type.hpp
> +	model::CcStatusType Get(int id);
Готово (везде поправил).

2024-05-21 02:43 UTC, lirik90 requested changes

2024-05-21 02:43 UTC, lirik90 commented on src/back/project/src/api/simple_crud.hpp
> +			// - X-Space-Role
Убери пожалуйста коммент после того как добавишь эти заголовки в описание апи.

2024-05-21 02:43 UTC, lirik90 commented on src/back/project/src/api/simple_crud.hpp
> +
Нужно достать эти параметры и передавать их во все функции.
userId нужно добавлять в логирование там где оно используется.
spaceId нужно передавать во все sql запросы.
```suggestion
			const auto userId = params["X-User"].As<std::string>();
			const auto spaceId = params["X-Space-Id"].As<std::string>();

```

2024-05-21 02:43 UTC, lirik90 commented on src/web/pipeline/server.nginx.conf
> +			proxy_pass http://space-proxy;
Давай так попробуем избавится от лишнего regex group в 119 строке 
```suggestion
			proxy_pass http://space-proxy/;
```

2024-05-21 02:43 UTC, lirik90 commented on src/web/pipeline/server.nginx.conf
> +	location ~ ^/([^/]+)/([^/]+)/(project|replace_to_another_ms_name)(/.*)?$ {
```suggestion
	location ~ ^/([^/]+)/(project|replace_to_another_ms_name)(/.*)?$ {
```

2024-05-21 02:43 UTC, lirik90 commented on src/back/project/src/repo/table_cc_param.cpp
> +void CcParam::Insert(int64_t ccId, int64_t paramId) {
Давай во все таблицы добавим space_id чтобы ограничивать выборку в запросе для пользователя и по простому проверять права пользователя на доступ к этим данным. В будущем по этому полю будем использовать шардирование (или партицирование).

2024-05-21 03:22 UTC, lirik90 commented on src/back/project/tests/test_value_view.py
> +h = {'X-User': 'd2f9924d-a69a-4aec-b9c0-c80171d3ed86'}
Вместо этого используем дефолтные хидеры 
```suggestion
```

2024-05-21 04:22 UTC, prt0117 commented on src/back/project/tests/test_value_view.py
> +h = {'X-User': 'd2f9924d-a69a-4aec-b9c0-c80171d3ed86'}
Готово.

2024-05-21 04:37 UTC, prt0117 commented on src/web/pipeline/server.nginx.conf
> +			proxy_pass http://space-proxy;
Получилось.

2024-05-21 04:37 UTC, prt0117 commented on src/web/pipeline/server.nginx.conf
> +	location ~ ^/([^/]+)/([^/]+)/(project|replace_to_another_ms_name)(/.*)?$ {
Работает.

2024-05-21 17:42 UTC, lirik90 commented
Нужно добавить для таблицы di_type связь c project

2024-05-21 17:55 UTC, lirik90 commented
Предполагаемые параметры которые будут передаваться в ручки с выводом списка. limit и page сокращены
/list:
- /project?l=10, p=0, spaceId=xxx
- /project_param?l=10, p=0, spaceId=xxx, projectId=xxx
- /section?l=10, p=0, spaceId=xxx, projectId=xxx
- /section_param?l=10, p=0, spaceId=xxx, sectionId=xxx
- /cc_type?l=10, p=0, spaceId=xxx, projectId=xxx
- /control_circuit?l=10, p=0, spaceId=xxx, sectionId=xxx
- /plugin?l=10, p=0, spaceId=xxx, projectId=xxx
- /device?l=10, p=0, spaceId=xxx, projectId=xxx
- /device_plugin_param?l=10, p=0, spaceId=xxx, deviceId=xxx
- /code?l=10, p=0, spaceId=xxx, projectId=xxx
- /measure?l=10, p=0, spaceId=xxx, projectId=xxx
- /save_timer?l=10, p=0, spaceId=xxx, projectId=xxx
- /cc_type_param?l=10, p=0, spaceId=xxx, ccTypeId=xxx
- /di_type?l=10, p=0, spaceId=xxx, projectId=xxx
- /di_plugin_param?l=10, p=0, spaceId=xxx, diTypeId=xxx
- /cc_type_di_type?l=10, p=0, spaceId=xxx, ccTypeId=xxx
- /device_item?l=10, p=0, spaceId=xxx, deviceId=xxx
- /cc_mode_type?l=10, p=0, spaceId=xxx, ccTypeId=xxx || projectId
- /cc_di?l=10, p=0, spaceId=xxx, ccId=xxx
- /cc_param?l=10, p=0, spaceId=xxx, ccId=xxx
- /cc_status_category?l=10, p=0, spaceId=xxx, projectId=xxx
- /cc_status_type?l=10, p=0, spaceId=xxx, ccTypeId=xxx
- /value_view?l=10, p=0, spaceId=xxx, ccTypeId=xxx
- /translation?l=10, p=0, spaceId=xxx, projectId=xxx

2024-05-21 18:28 UTC, lirik90 commented on src/back/project/src/main.cpp
> +#include "model/cc_mode_type.hpp"
cc_mode_type содержится в cc_mode_type_serialize который ты импортируешь ниже. Давай тут все лишние импорты уберём.

2024-05-21 19:39 UTC, lirik90 commented on src/back/project/src/main.cpp
> +	DECLARE_SIMPLE_HANDLER_FULL(DeviceItem, handler-device-item, deviceId);
Эта штука всё ещё не подходит для связывающих таблиц, но уже подходит для списков. Замени пожалуйста обработчики получения списков из не связывающий таблиц, на это.

2024-05-21 19:46 UTC, lirik90 commented on src/back/project/src/main.cpp
> +
Раскомментировав строку выше, нужно удалить соответствующий код тут.

2024-05-22 04:45 UTC, prt0117 commented on src/back/project/src/main.cpp
> +#include "model/cc_mode_type.hpp"
Готово.

2024-05-22 06:31 UTC, prt0117 commented on src/back/project/src/main.cpp
> +
Понятно, спасибо.

2024-05-22 06:37 UTC, prt0117 commented on src/back/project/src/repo/table_cc_param.cpp
> +void CcParam::Insert(int64_t ccId, int64_t paramId) {
Готово.

2024-05-22 16:17 UTC, lirik90 commented on src/back/project/src/api/di-plugin-param.cpp
> +	auto spaceId = utils::BoostUuidFromString(req.GetHeader("X-Space-Id"));
Давай значения доставать из провалидированных параметров, а не напрямую из запроса.
```suggestion
	auto spaceId = utils::BoostUuidFromString(params["X-Space-Id"].As<std::string>());
```

2024-05-22 16:28 UTC, lirik90 requested changes

2024-05-22 16:28 UTC, lirik90 commented on src/back/project/src/api/di-plugin-param.cpp
> +	diPluginParam.spaceId = spaceId;
Давай сразу присваивать значение модели:

```suggestion
	diPluginParam.spaceId = utils::BoostUuidFromString(req.GetHeader("X-Space-Id"));
```

2024-05-22 16:28 UTC, lirik90 commented on src/back/project/src/api/di-plugin-param.cpp
> +	auto diPluginParam = body.As<model::DiPluginParam>();
Давай пожалуйста в типовом коде, который копируется как есть из места в место, создавать сущности с типовыми именами, когда работает только с одним типом сущности. Наличие уникального имени в 50 одинаковых файлах никакой пользы не несёт. А если имя будет типовым, то и копировать этот код будет проще.
```suggestion
	auto item = body.As<model::DiPluginParam>();
```

2024-05-22 21:09 UTC, lirik90 commented on src/back/project/src/repo/table_device.cpp
> +PagingResult<model::Device> Device::GetList(const boost::uuids::uuid& spaceId, int start, int limit) {
Нужно space_id добавить в перечисление столбцов в SELECT чтобы он смапил все поля в структуру.
Без этого будет ошибка
`Invalid tuple size requested. Field count X < tuple size Y`

2024-05-22 22:20 UTC, lirik90 commented on src/back/project/src/main.cpp
> +	DECLARE_SIMPLE_HANDLER_FULL(DeviceItem, handler-device-item, deviceId);
Теперь должно подходить для всего кроме одной ручки где list по двум разным фильтрам нужен.

2024-05-23 09:03 UTC, prt0117 commented
> Нужно добавить для таблиц di_type и cc_mode_type связь c project

Готово.

2024-05-27 09:21 UTC, prt0117 commented on src/back/project/src/repo/table_device.cpp
> +PagingResult<model::Device> Device::GetList(const boost::uuids::uuid& spaceId, int start, int limit) {
Готово.

2024-05-27 09:21 UTC, prt0117 commented on src/back/project/src/api/di-plugin-param.cpp
> +	diPluginParam.spaceId = spaceId;
ОК (уже не актуально, так как все эти места ушли после рефакторинга на шаблоны).

2024-05-27 09:21 UTC, prt0117 commented on src/back/project/src/api/di-plugin-param.cpp
> +	auto spaceId = utils::BoostUuidFromString(req.GetHeader("X-Space-Id"));
ОК (уже не актуально, так как все эти места ушли после рефакторинга на шаблоны).

2024-05-27 09:21 UTC, prt0117 commented on src/back/project/src/main.cpp
> +	DECLARE_SIMPLE_HANDLER_FULL(DeviceItem, handler-device-item, deviceId);
Готово (заменил везде).

2024-05-27 09:21 UTC, prt0117 commented on src/back/project/src/api/simple_crud.hpp
> +
По spaceId - готово, уже передаётся во все sql запросы. 

по userId - логирование, если не ошибаюсь, в мс Проекты сейчас происходит только вот тут https://github.com/svetit-io/svetit/blob/feature/100-endpoint-validation/src/back/deps/svetit/shared/schemas.cpp#L105 (работа со схемами) и вот тут https://github.com/svetit-io/svetit/blob/feature/100-endpoint-validation/src/back/deps/svetit/shared/errors_catchit.cpp#L21 (стандартный верхнеуровневый обработчик исключений). Нужно ли передавать userId в эти места?

2024-05-27 09:21 UTC, prt0117 commented on src/back/project/src/api/simple_crud.hpp
> +			// - X-Space-Role
X-User и X-Space-Id уже во всех ручках описаны в api.yaml. X-Space-Role тоже уже можно добавлять? Этот заголовок обязательный?

2024-05-27 09:39 UTC, prt0117 commented on src/back/project/src/api/di-plugin-param.cpp
> +	auto diPluginParam = body.As<model::DiPluginParam>();
Готово.

2024-05-28 02:40 UTC, lirik90 commented on src/back/project/src/api/simple_crud.hpp
> +			// - X-Space-Role
Этот заголовок обязательный. Можно добавлять.

2024-05-28 03:11 UTC, lirik90 commented on src/back/project/src/api/simple_crud.hpp
> +
Добавил

2024-05-28 04:03 UTC, lirik90 requested changes

2024-05-28 04:03 UTC, lirik90 commented on src/back/project/src/model/save_timer_serialize.cpp
> +		.id = json["id"].As<int64_t>(),
Давай проинициализируем все поля в структуре чтобы компилятор не выдавал предупреждения
```suggestion
		.spaceId = {},
```

это нужно сделать для всех моделей

2024-05-28 04:03 UTC, lirik90 commented on src/back/project/src/repo/table_cc_param.cpp
>  	pg::Query::Name{"count_cc_params"},
в kCount запросе ошибка, нет фильтров. Это нужно исправить для всех таблиц.

2024-05-28 05:23 UTC, prt0117 commented on src/back/project/src/api/simple_crud.hpp
> +			// - X-Space-Role
Готово - везде добавил, комменты ToDo убрал.

2024-05-28 05:33 UTC, prt0117 commented on src/back/project/src/model/save_timer_serialize.cpp
> +		.id = json["id"].As<int64_t>(),
Готово (для всех моделей).

2024-05-28 06:21 UTC, prt0117 commented on src/back/project/src/repo/table_cc_param.cpp
>  	pg::Query::Name{"count_cc_params"},
Готово - везде.

2024-05-28 06:45 UTC, lirik90 approved these changes

2024-05-28 06:45 UTC, merged