Feature/131 space introspect
svetit-io/svetit pull request #132
Opened 2024-05-28 11:42 UTC by prt0117

2024-05-31 04:54 UTC, lirik90 requested changes

2024-05-31 04:54 UTC, lirik90 commented on pipeline/.env.example
> +SPACE_INTERNAL_TLS_KEY_PATH='/home/user/svetit/src/back/auth/configs/session.key'
Не должно быть полных путей в конфиге

2024-05-31 05:00 UTC, prt0117 commented on pipeline/.env.example
> +SPACE_INTERNAL_TLS_KEY_PATH='/home/user/svetit/src/back/auth/configs/session.key'
Пардон, это рудимент, забыл убрать, убрал.

2024-06-01 04:18 UTC, lirik90 requested changes

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				LOG_DEBUG() << "Token verify OK";
Давай это уберём.

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				// TODO - может надо ловить тут разные исключения? если исключение верификации, то переходим к созданию. если исключения другие, то re-throw
Пока не надо.
```suggestion
```

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +		// todo - какие тут нам нужны настройки у создаваемой куки?
Давай пожалуйста проверим будет ли работать кука с одинаковым именем 'space', но разным Path для разных пространств. Попробуем в Path передавать путь такой: X-ApiPrefix + "/s/" + {space_key} + '/'

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +		LOG_DEBUG() << "Setting Cookie and headers and returning OK";
Отладку перед влитием давай уберём

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				return "Ok";
А если вместо Ок пустую строку передавать, нормально отработает?
```suggestion
				return {};
```

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				return "Ok";
Давай ещё устанавливать код 204

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/service/service.cpp
> +		throw errors::Forbidden403();
```suggestion
	throw errors::Forbidden403();
```

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/service/service.cpp
> +	std::regex rgx("^/([^/]+)/");
```suggestion
	static std::regex rgx("^/([^/]+)/");
```

2024-06-01 04:18 UTC, lirik90 commented on src/back/space/src/service/service.cpp
> +    return result.checksum();
Замени пожалуйста пробелы на табы
```suggestion
	result.process_bytes(data.data(), data.length());
	return result.checksum();
```

2024-06-03 04:28 UTC, prt0117 commented on src/back/space/src/service/service.cpp
> +    return result.checksum();
Готово.

2024-06-03 04:28 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				return "Ok";
Готово - работает корректно.

2024-06-03 04:28 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				return "Ok";
Готово.

2024-06-03 04:28 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +		LOG_DEBUG() << "Setting Cookie and headers and returning OK";
Готово.

2024-06-03 04:28 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				LOG_DEBUG() << "Token verify OK";
Ты про LOG_DEBUG()? Убрал.

2024-06-03 05:07 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +		// todo - какие тут нам нужны настройки у создаваемой куки?
Готово, влил.

2024-06-06 09:35 UTC, lirik90 approved these changes

2024-06-06 09:36 UTC, merged