Сбой повторной авторизации и 500 ответ ручки userinfo
svetit-io/svetit pull request #146
Opened 2024-06-05 06:17 UTC by prt0117

2024-06-06 09:43 UTC, lirik90 requested changes

2024-06-06 09:43 UTC, lirik90 commented on src/back/auth/src/api/user_info.cpp
> -	const auto& sessionId = req.GetHeader(headers::kSessionId);
А что не так с получением id по хидеру? Он должен приходить. Для ручек /user на проксе авторизация не выключена.

2024-06-07 04:17 UTC, prt0117 commented on src/back/auth/src/api/user_info.cpp
> -	const auto& sessionId = req.GetHeader(headers::kSessionId);
Ой, вернул, как было)

2024-06-07 13:12 UTC, lirik90 approved these changes

2024-06-07 13:12 UTC, merged