Валидация по схеме в мс Пространства
svetit-io/svetit pull request #150
Opened 2024-06-05 11:23 UTC by prt0117

2024-06-06 09:47 UTC, lirik90 requested changes

2024-06-06 09:47 UTC, lirik90 commented on src/back/space/src/api/user-list.cpp
> +	, _mapHttpMethodToSchema{LoadSchemas(kName, _s.GetJSONSchemasPath())}
Схема загружается, но не используется. Ещё не доделал?

2024-06-06 11:43 UTC, prt0117 commented on src/back/space/src/api/user-list.cpp
> +	, _mapHttpMethodToSchema{LoadSchemas(kName, _s.GetJSONSchemasPath())}
Да, это был один из этапов) Уже дополнил использованием.

2024-06-07 13:29 UTC, lirik90 requested changes

2024-06-07 13:29 UTC, lirik90 commented on doc/api/api.yaml
> +        - main
Нужно тегами разбить ручки по микросервисам. 
```suggestion
        - space
```

2024-06-07 13:29 UTC, lirik90 commented on src/back/space/src/api/list-available.cpp
>  			throw errors::BadRequest400("Too big limit param");
Подобные штуки не нужны потому что будут проверены валидатором.

2024-06-07 13:29 UTC, lirik90 commented on src/back/space/src/api/list-available.cpp
> +		};
Посмотри как в МС Проекты парсятся параметры пагинации
```suggestion
		const auto paging = parsePaging(params);
```

2024-06-10 08:20 UTC, prt0117 commented on src/back/space/src/api/list-available.cpp
> +		};
Готово (везде в этом мс).

2024-06-10 08:32 UTC, prt0117 commented on src/back/space/src/api/list-available.cpp
>  			throw errors::BadRequest400("Too big limit param");
Готово (везде)

2024-06-10 08:42 UTC, prt0117 commented on doc/api/api.yaml
> +        - main
Готово.

2024-06-10 13:16 UTC, lirik90 requested changes

2024-06-10 13:16 UTC, lirik90 commented on src/back/space/src/api/invitation.cpp
>  	const server::http::HttpRequest& req,
Этот параметр кажется не используется. Давай уберем везде в таких местах

2024-06-11 09:31 UTC, prt0117 commented on src/back/space/src/api/invitation.cpp
>  	const server::http::HttpRequest& req,
Готово (убрал везде, где можно было в этом мс).

2024-06-12 14:13 UTC, lirik90 approved these changes

2024-06-12 14:14 UTC, merged