setting secret for realm import during init
svetit-io/svetit pull request #16
Opened 2023-09-04 10:34 UTC by prt0117

2023-09-13 06:16 UTC, lirik90 requested changes

2023-09-13 06:16 UTC, lirik90 commented on pipeline/init_env.sh
> +		sed -i "s/\"secret\":\\s\?\"[^\"]*\"/\"secret\": \"$password\"/g" "$SCRIPT_PATH/keycloak/import/realm-export.json"
При таком подходе пароль заменится в исходном файле и затем разработчик при работе может случайно его закоммитить. Нужно сделать чтобы файл копировался при сборке контейнера и внутри контейнера подставлялся пароль в этот файл.

2023-09-14 06:22 UTC, prt0117 commented on pipeline/init_env.sh
> +		sed -i "s/\"secret\":\\s\?\"[^\"]*\"/\"secret\": \"$password\"/g" "$SCRIPT_PATH/keycloak/import/realm-export.json"
Готово. Посмотри, пожалуйста, вариант реализации. Если всё ок, то единственное порт Клока вынесем тоже в енв.

2023-09-23 04:13 UTC, lirik90 commented
Будет сделано в ПР https://github.com/svetit-io/svetit/pull/30

2023-09-23 04:13 UTC, closed without merging