Валидация по схеме в мс Авторизации
svetit-io/svetit pull request #161
Opened 2024-06-07 05:01 UTC by prt0117

2024-06-07 17:28 UTC, lirik90 requested changes

2024-06-07 17:28 UTC, lirik90 commented on src/back/deps/svetit/shared/schemas.cpp
> +		}else
```suggestion
		} else
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/user_list.cpp
> +		};
```suggestion
		const auto paging = parsePaging(params);
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/logout_callback.cpp
> +	const auto params = ValidateRequest(_mapHttpMethodToSchema, req, body);
Там есть перегруженная функция
```suggestion
	const auto params = ValidateRequest(_mapHttpMethodToSchema, req);
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/login_callback.cpp
> +	const std::string userAgent = params[http::headers::kUserAgent].As<std::string>();
```suggestion
	const auto userAgent = params[http::headers::kUserAgent].As<std::string>();
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/login_callback.cpp
> +	const auto params = ValidateRequest(_mapHttpMethodToSchema, req, body);
```suggestion
	const auto params = ValidateRequest(_mapHttpMethodToSchema, req);
```

2024-06-07 17:28 UTC, lirik90 commented on doc/api/api.yaml
> +          description: Null response
Если null response то код наверное должен быть 204

2024-06-07 17:28 UTC, lirik90 commented on doc/api/api.yaml
> +          description: unexpected error
401 это же не unexpected error, давай поменяем код или сообщение.

2024-06-07 17:28 UTC, lirik90 commented on doc/api/api.yaml
> +                $ref: "#/components/schemas/Error"
Давай явно указывать код. И давай сократим запись:
```suggestion
        '500':
          $ref: "#/components/schemas/Error500"
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/helpers.cpp
> +	}
Не используем else там где можно без него.
```suggestion
	std::string scheme = "http";
	if (params.HasMember("X-Forwarded-Proto"))
		scheme = params["X-Forwarded-Proto"].As<std::string>();
```

Проверь пожалуйста, должно работать что-то такое:
```suggestion
	const auto scheme = params["X-Forwarded-Proto"].As<std::string>("http");
```
Если работает как ожидается, используй такое пожалуйста везде в затронутом коде.

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/helpers.cpp
> +	}
Не используем else там где можно без него.
```suggestion
	std::string host = req.GetHost();
	if (params.HasMember("X-Forwarded-Host"))
		host = params["X-Forwarded-Host"].As<std::string>();
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/helpers.cpp
>  	return scheme + "://" + host + apiPrefix;
Давай вернём результат не создавая объект переменной - std::string apiPrefix - если он не нужен.
```suggestion
	if (!addApiPrefix)
		return scheme + "://" + host;

	 auto apiPrefix = params["X-ApiPrefix"]
		.As<std::string>(formats::json::Value::DefaultConstructed{});
	if (!apiPrefix.empty() && apiPrefix.front() != '/')
		apiPrefix.insert(0, '/');
	return scheme + "://" + host + apiPrefix;
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/login.cpp
>  	}
```suggestion
	auto redirectPath = params["redirectPath"]
		.As<std::string>(formats::json::Value::DefaultConstructed{});
	if (redirectPath.empty()) {
		redirectPath = params[http::headers::kReferer].As<std::string>();
		redirectPath = http::ExtractPath(redirectPath);
	}
```

Проверь пожалуйста, может сработает более короткий вариант:
```suggestion
	auto redirectPath = params["redirectPath"].As<std::string>({});
	if (redirectPath.empty()) {
		redirectPath = params[http::headers::kReferer].As<std::string>();
		redirectPath = http::ExtractPath(redirectPath);
	}
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/token_introspect.cpp
> +	const std::string& userAgent = params[http::headers::kUserAgent].As<std::string>();
Тут не указываем ссылку, потому что функция возвращает новый объект, а не объект по ссылке.
```suggestion
	const auto userAgent = params[http::headers::kUserAgent].As<std::string>();
```

2024-06-07 17:28 UTC, lirik90 commented on src/back/auth/src/api/token_introspect.cpp
>  		const auto data = _s.Session().Token().Verify(token);
Сейчас выглядит так как будто мы проверяем пустой токен. Кажется это делать не нужно.
Конкретно в этой ручке мы можем засунуть в общий try catch ещё и валидацию, потому что тут, как мне кажется, 400 код не актуален, от этой ручки nginx ждёт либо 2xx либо 401
```suggestion
	try {
		const auto params = ValidateRequest(_mapHttpMethodToSchema, req);
		const auto token = params[Consts::SessionCookieName].As<std::string>();		
		const auto userAgent = params[http::headers::kUserAgent].As<std::string>();
		const auto data = _s.Session().Token().Verify(token);
```

2024-06-10 05:37 UTC, prt0117 commented on doc/api/api.yaml
> +          description: unexpected error
Готово (поменял description).

2024-06-10 05:40 UTC, prt0117 commented on src/back/auth/src/api/token_introspect.cpp
> +	const std::string& userAgent = params[http::headers::kUserAgent].As<std::string>();
Готово.

2024-06-10 06:20 UTC, prt0117 commented on src/back/auth/src/api/login.cpp
>  	}
Вот такой вариант сработал:
```
    auto redirectPath = params["redirectPath"]
		.As<std::string>(formats::json::Value::DefaultConstructed{});
	if (redirectPath.empty()) {
		redirectPath = params[http::headers::kReferer].As<std::string>();
		redirectPath = http::ExtractPath(redirectPath);
	}
```

2024-06-10 06:22 UTC, prt0117 commented on src/back/auth/src/api/token_introspect.cpp
>  		const auto data = _s.Session().Token().Verify(token);
Готово.

2024-06-10 06:23 UTC, prt0117 commented on src/back/auth/src/api/login.cpp
>  	}
Более короткий не работает, не может найти параметр, если его нет и если не указать дефолтное значение As<std::string>(formats::json::Value::DefaultConstructed{});

2024-06-10 06:24 UTC, prt0117 commented on src/back/auth/src/api/helpers.cpp
>  	return scheme + "://" + host + apiPrefix;
Готово.

2024-06-10 06:24 UTC, prt0117 commented on src/back/auth/src/api/helpers.cpp
> +	}
Готово.

2024-06-10 06:29 UTC, prt0117 commented on src/back/auth/src/api/helpers.cpp
> +	}
Готово, работает.

2024-06-10 06:35 UTC, prt0117 commented on doc/api/api.yaml
> +                $ref: "#/components/schemas/Error"
Готово - только эта ручка может вернуть либо 200, либо 401, поэтому поменял 500 на 401.

Будем менять это везде во всех ручках? Кстати, мы ведь никак пока не используем responses, описанные в ямле?

2024-06-10 06:44 UTC, prt0117 commented on src/back/auth/src/api/login_callback.cpp
> +	const auto params = ValidateRequest(_mapHttpMethodToSchema, req, body);
Готово (везде).

2024-06-10 06:46 UTC, prt0117 commented on src/back/auth/src/api/login_callback.cpp
> +	const std::string userAgent = params[http::headers::kUserAgent].As<std::string>();
Готово.

2024-06-10 06:47 UTC, prt0117 commented on src/back/auth/src/api/logout_callback.cpp
> +	const auto params = ValidateRequest(_mapHttpMethodToSchema, req, body);
Готово (везде).

2024-06-10 06:48 UTC, prt0117 commented on src/back/auth/src/api/user_list.cpp
> +		};
Готово.

2024-06-10 06:48 UTC, prt0117 commented on src/back/deps/svetit/shared/schemas.cpp
> +		}else
Готово.

2024-06-10 06:53 UTC, prt0117 commented on doc/api/api.yaml
> +          description: Null response
Везде такие изменения внести? Сейчас в api.yaml 68 мест, где description = Null response. Нужно тогда перепроверить, а также поменять ответы в ручках + ожидаемые ответы в тестах.

2024-06-10 13:00 UTC, lirik90 commented on doc/api/api.yaml
> +          description: Null response
Да

2024-06-11 04:18 UTC, lirik90 commented on doc/api/api.yaml
> +                $ref: "#/components/schemas/Error"
Конкретно эта ручка да. Но большинство других ручек могут вернуть 500. Нужно описать все коды которые возвращаются нами (а не проксёй или фреймворком, например).
Это нужно для всех ручек несмотря на то что пока не используем. Этот ямл ценен сам по себе как дока, и пока это в основном для целей документирования. Но думаю будут и редкие кейсы когда будем использовать сгенерированные из этого файла ответы во фронте.

2024-06-11 06:37 UTC, prt0117 commented on doc/api/api.yaml
> +          description: Null response
Готово.

2024-06-11 06:37 UTC, prt0117 commented on doc/api/api.yaml
> +                $ref: "#/components/schemas/Error"
Готово (везде в текущей ветке).

2024-06-11 09:35 UTC, prt0117 commented on doc/api/api.yaml
> +                $ref: "#/components/schemas/Error"
Только надо ещё изучить табличные классы и сервис дополнительно, оттуда тоже могут выбрасываться исключения, а следовательно - будут новые статусы ответов. В процессе.

2024-06-12 14:20 UTC, lirik90 requested changes
Сделай ребейз пожалуйста

2024-06-13 04:48 UTC, lirik90 approved these changes

2024-06-13 04:48 UTC, merged