Feature/167 splitted openapi
svetit-io/svetit pull request #187
Opened 2024-06-19 10:12 UTC by prt0117

2024-06-21 03:07 UTC, lirik90 commented on .gitignore
> +doc/api/api.yaml
А зачем это добавил? Если у нас такого файла больше нет, то и тут он не нужен.

2024-06-21 05:02 UTC, prt0117 commented on .gitignore
> +doc/api/api.yaml
Поправил.

2024-06-24 03:24 UTC, lirik90 requested changes
А зачем отдельная вложенная папка splitted нужна? Давай без неё. Вынесем всё в doc/api

2024-06-24 03:27 UTC, prt0117 commented
> А зачем отдельная вложенная папка splitted нужна? Давай без неё. Вынесем всё в doc/api

мы сейчас в doc/api храним файл с хешем + там появляется и потом удаляется временный файл api.yaml. Если расположить все файл прямо в doc/api - возможно коллизиии. Например, если будет какой-то параметр api.yaml.

2024-06-24 03:29 UTC, lirik90 commented
А в какой момент появляется api.yaml? Он разве не внутри контейнера появляется перед запуском питоновской утилиты? Давай сделаем чтобы этот файл генерировался во временную папку /tmp а потом удалялся.

2024-06-24 03:43 UTC, prt0117 commented
> А в какой момент появляется api.yaml? Он разве не внутри контейнера появляется перед запуском питоновской утилиты? Давай сделаем чтобы этот файл генерировался во временную папку /tmp а потом удалялся.

когда локально собираем. когда в докере, не появляется. в /tmp - ок.
а hash файл можно заэксклюдить при запуске find.

2024-06-25 02:42 UTC, lirik90 approved these changes

2024-06-25 02:42 UTC, merged