Feature/15 session token refresh
svetit-io/svetit pull request #20
Opened 2023-09-05 07:05 UTC by prt0117

2023-09-06 07:55 UTC, lirik90 requested changes

2023-09-06 07:55 UTC, lirik90 commented on src/back/auth/src/model/session_refresh_serialize.hpp
> +model::SessionRefresh ParseSessionRefreshInfo(const formats::json::Value& json);
Это кажется у тебя нигде не используется.

2023-09-06 07:55 UTC, lirik90 commented on src/back/auth/src/model/session_refresh_serialize.cpp
> +}
Кажется у тебя это не используется.

2023-09-06 07:55 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +
А для чего отдельными запросами?

2023-09-06 07:55 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	const std::chrono::system_clock::time_point exp = _tokenizer.GetExpirationTime(tokens._refreshToken);
```suggestion
	// Получаем expiration time из refresh токена OIDC
	const auto exp = _tokenizer.GetExpirationTime(tokens._refreshToken);
```

2023-09-06 07:55 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +		._sessionId = decoded.get_payload_claim("ses").as_string()
```suggestion
	return {
		._userId = decoded.get_subject(),
		._sessionId = decoded.get_payload_claim(std::string{_sessionIdKey}).as_string()
```

2023-09-06 07:55 UTC, lirik90 commented on src/back/auth/src/service/session.cpp
> +	};
Нужно вынести этот кусов в отдельную приватную функцию и переиспользовать в Create

2023-09-07 04:26 UTC, prt0117 commented on src/back/auth/src/model/session_refresh_serialize.hpp
> +model::SessionRefresh ParseSessionRefreshInfo(const formats::json::Value& json);
Поправил.

2023-09-07 04:27 UTC, prt0117 commented on src/back/auth/src/model/session_refresh_serialize.cpp
> +}
Поправил.

2023-09-07 04:43 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +
Поправил.

2023-09-07 04:46 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	const std::chrono::system_clock::time_point exp = _tokenizer.GetExpirationTime(tokens._refreshToken);
Поправил.

2023-09-07 04:49 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +		._sessionId = decoded.get_payload_claim("ses").as_string()
Поправил.

2023-09-07 04:57 UTC, prt0117 commented on src/back/auth/src/service/session.cpp
> +	};
Поправил.

2023-09-07 18:16 UTC, lirik90 requested changes

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/api/token_refresh.cpp
> +
Кажется тут лишняя пустая строка.

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/model/session_refresh.hpp
> +}
Для того чтобы понимать что эта закрывающая скобка закрывает namespace, я предлагаю добавлять к ней комментарий. Она особенная по тому что на одном уровне с содержимым. В противном случае всё содержимое внутри нужно было бы оформить отступом.
```suggestion
} // namespace svetit::auth::model
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/model/session_refresh_serialize.hpp
> +#include <userver/formats/parse/common_containers.hpp>
Возможно этот инклуд лишний.

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +	"UPDATE session SET active = false "
Если сессия не активна, то и токены не нужны. Только место занимают. 
```suggestion
	"UPDATE session SET active=false, token='', accessToken='', refreshToken='', idToken='' "
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +	"UPDATE session SET active = false "
```suggestion
	"UPDATE session SET active=false, token='', accessToken='', refreshToken='', idToken='' "
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +
Зачем нужен этот запрос если тот что выше точно такой же?

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +}
```suggestion
void Session::MarkInactive(const boost::uuids::uuid& id)
{
	_pg->Execute(
		storages::postgres::ClusterHostType::kMaster, kMarkSessionInactive, id);
}
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +	MarkInactiveAndCleanTokensById(oldSessionId);
Тут запрос не в транзакции.
```suggestion
	t.Execute(kMarkSessionInactive, oldId);
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +	const boost::uuids::uuid& oldSessionId)
Слово session есть в названии класса. Да и другого id с таким типом тут быть не может. Предлагаю укоротить.)
```suggestion
	const boost::uuids::uuid& oldId)
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/repo/table_session.hpp
> +
Давай соблюдать порядок перечисления функций таким как он идёт в файле определений. Так их проще искать.
```suggestion
	void BlockEverySessionByUser(const std::string& userId);
	void Refresh(
		const model::Session& data,
		const boost::uuids::uuid& oldSessionId
	);

	void MarkInactiveAndCleanTokensById(const boost::uuids::uuid& sid);


```

2023-09-07 18:16 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +		//console.log("Session token: " + token);
Не удалил коммент.

2023-09-07 18:16 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +		let msecs = decoded.exp * 1000 - new Date().getTime() - 30000000;
Зачем эта правка?

2023-09-07 18:16 UTC, lirik90 commented on src/back/shared/errors.hpp
> +};
Этот файл в папке shared на уровень выше папки проекта. Это для того чтобы хранить в этой папке код который точно будет переиспользован в других МС.  ForceBlock лучше перенести в папку с проектом.

2023-09-07 18:16 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +
Не удалил коммент.

2023-09-07 18:16 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +		});
Функция startRefreshTimer вызывается в setToken которая вызывается в SaveToken. Зачем тут вызывать её ещё раз?

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/session.hpp
> +		const std::chrono::system_clock::time_point& exp);
1. Слишком абстрактное имя с учётом того что в классе могут появится и другие методы которые не будут вызывать этот. Предлагаю prepare или prepareNew
2. Приватные методы предлагаю называть с маленькой буквы. Это позволяет отличить из в файле определения и при автодополнении в некоторых случаях.
```suggestion
	model::Session prepare(
		const OIDCTokens& tokens,
		const TokenPayload& data,
		const std::string& userAgent,
		const std::chrono::system_clock::time_point& exp);
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.hpp
>  private:
Если эти методы нужны только для использования внутри других методов этого же класса, нужно сделать их приватными.
```suggestion

private:
	void sameInactiveSessionSecurityCheck(const std::string& sessionId);
	void differentDeviceSecurityCheck(
		const std::string& currentUserAgent,
		const std::string& oldUserAgent
	);	
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/model/session_refresh_serialize.cpp
> +#include <userver/utils/strong_typedef.hpp>
Возможно этот инклуд не нужен? Проверь пожалуйста.

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	if (strcmp(currentUserAgent.c_str(), oldUserAgent.c_str()) != 0){
```suggestion
	if (currentUserAgent != oldUserAgent) {
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	DifferentDeviceSecurityCheck(userAgent, session._device);
Тут мы должны сначала получить сессию по id независимо от того активна она или нет. Затем проверить device и если не совпадает, то бросить исключение и не блокировать все сессии пользователя. Затем если сессия не активна блокируем все сессии пользователя.

Если сессия активна, обновляем oidc токены, делаем dist lock и проверяем ещё раз активна ли сессия и если нет, делаем unlock и блокируем все активные. Если же она активна, то в одной транзакции закрываем старую сессию и сохраняем новую. Затем unlock.

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	if (_tokenizer.IsExpired(session._accessToken))
```suggestion
	// Обновляем OIDC токены даже если не требуется
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	}
Такое можно было бы сделать вот так:
```suggestion
	} catch(const NotFound& e) {
		isSecurityRisk = false;
	}
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	const std::chrono::system_clock::time_point exp = _tokenizer.GetExpirationTime(tokens._refreshToken);
```suggestion
	const auto exp = _tokenizer.GetExpirationTime(tokens._refreshToken);
```

2023-09-07 18:16 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	const model::Session newSession = _session.Refresh(tokens, data, userAgent, exp, session._id);
```suggestion
	const auto newSession = _session.Refresh(tokens, data, userAgent, exp, session._id);
```

2023-09-11 03:43 UTC, prt0117 commented on src/back/auth/src/api/token_refresh.cpp
> +
Поправил.

2023-09-11 03:44 UTC, prt0117 commented on src/back/auth/src/model/session_refresh.hpp
> +}
Поправил.

2023-09-11 03:48 UTC, prt0117 commented on src/back/auth/src/model/session_refresh_serialize.hpp
> +#include <userver/formats/parse/common_containers.hpp>
Не совсем понял, какой именно инклуд лишний.

2023-09-11 03:51 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +	"UPDATE session SET active = false "
Поправил.

2023-09-11 03:53 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +	"UPDATE session SET active = false "
Поправил.

2023-09-11 03:55 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +
Поправил.

2023-09-11 03:57 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +}
Поправил.

2023-09-11 03:59 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +	MarkInactiveAndCleanTokensById(oldSessionId);
Поправил.

2023-09-11 04:10 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +	const boost::uuids::uuid& oldSessionId)
Согласен:) Поправил.

2023-09-11 04:14 UTC, prt0117 commented on src/back/auth/src/repo/table_session.hpp
> +
Поправил (но в других файлах пока не проверял, чтобы порядок был везде правильным).

2023-09-11 04:16 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +		//console.log("Session token: " + token);
Поправил.

2023-09-11 04:20 UTC, prt0117 commented on src/back/shared/errors.hpp
> +};
Перенёс.

2023-09-11 04:21 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +
Готово.

2023-09-11 04:22 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +		});
Без этого обновление токена вызывается только 1 раз.

2023-09-11 04:26 UTC, prt0117 commented on src/back/auth/src/service/session.hpp
> +		const std::chrono::system_clock::time_point& exp);
Поправил.

2023-09-11 04:30 UTC, prt0117 commented on src/back/auth/src/service/service.hpp
>  private:
Поправил.

2023-09-11 04:40 UTC, prt0117 commented on src/back/auth/src/model/session_refresh_serialize.cpp
> +#include <userver/utils/strong_typedef.hpp>
Убрал 1 лишний инклюд.

2023-09-11 04:44 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	if (strcmp(currentUserAgent.c_str(), oldUserAgent.c_str()) != 0){
Поправил.

2023-09-11 04:45 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	if (_tokenizer.IsExpired(session._accessToken))
Поправил.

2023-09-11 04:48 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	}
Поправил.

2023-09-11 04:50 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	const std::chrono::system_clock::time_point exp = _tokenizer.GetExpirationTime(tokens._refreshToken);
Поправил.

2023-09-11 04:52 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	const model::Session newSession = _session.Refresh(tokens, data, userAgent, exp, session._id);
Поправил.

2023-09-11 05:04 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +		let msecs = decoded.exp * 1000 - new Date().getTime() - 30000000;
Я думал, что ты опечатался, когда писал этот момент. Если сделать так, как было изначально (30000), то на локалке рефреш токен будет обновляться раз в 10 часов. А если увеличить это число в 1000 раз, то раз в 1,5 часа будет обновление. В любом случае, логика этого отнимания мне не ясна. Не до конца понятно, чего ты хотел добиться данным уменьшением.

2023-09-11 06:21 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +		let msecs = decoded.exp * 1000 - new Date().getTime() - 30000000;
Тут decoded.exp хранит ту точку времени когда токен уже просрочится, т.е. его уже нельзя обновить. Нам нужен небольшой запас по времени на обновление токена.

2023-09-11 06:53 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +		let msecs = decoded.exp * 1000 - new Date().getTime() - 30000000;
Поправил.

2023-09-12 04:43 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	DifferentDeviceSecurityCheck(userAgent, session._device);
Реализовано в соответствие с дополнительным обсуждением.

2023-09-12 06:29 UTC, lirik90 requested changes

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/api/token_refresh.cpp
> +
Неа.

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/model/errors.hpp
> +	SecurityRisk(const std::string& msg) : std::runtime_error{msg} {}
```suggestion
	using std::runtime_error::runtime_error
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +
Лишние пустые строки.

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +
Тут ещё одна лишняя пустая строка.

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/repo/table_session.hpp
> +	);
```suggestion
		const boost::uuids::uuid& oldId);
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +		storages::postgres::ClusterHostType::kMaster, kMarkSessionInactive, sid);
sid - кажется s тут лишняя. Давай оставим просто id

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/repo/table_session.hpp
> +	void BlockEverySessionByUser(const std::string& userId);
Session - есть в названии класса, Every понятно из того что нет специфичных аргументов. Тут можно было бы сделать название покороче, например BlockByUserId. Но у нас уже есть функция которая делает тоже самое но с другими параметрами. Нужно назвать её так же MarkInactive. И ещё поставь их пожалуйста рядом.
```suggestion
	void MarkInactive(const std::string& userId);
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +	"WHERE userId=$1",
```suggestion
	"WHERE userId=$1 AND active=true",
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +){
```suggestion
	const std::string& oldUserAgent)
{
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +		throw errors::SecurityRisk{"Different user agent."};
Нужно бы залогировать агент.
```suggestion
		const auto agent = currentUserAgent.substr(0, 150);
		throw errors::SecurityRisk{"Different user agent: '" + agent + '\''};
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/api/token_refresh.cpp
> +		LOG_WARNING() << "Fail to refresh session token: " << e.what();
Добавь пожалуйста ID сессии:
```suggestion
		LOG_WARNING() << '[' << sessionId << "] Fail to refresh session token: " << e.what();
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	return refresh;
Можно сократить:
```suggestion
	try {
		auto token = updateSession(session, userAgent);
		return {token};
	} catch(errors::SecurityRisk& e) {
		_session.Table().BlockEverySessionByUser(session._userId);
		throw;
	}

	return {};
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +
Пустая строка

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	const std::string& userAgent){
```suggestion
	const std::string& userAgent)
{
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/service.hpp
> +	);
```suggestion
		const std::string& oldUserAgent);	
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/session.cpp
> +){
```suggestion
	const std::chrono::system_clock::time_point& exp)
{
```

2023-09-12 06:29 UTC, lirik90 commented on src/back/auth/src/service/session.hpp
> +		const std::chrono::system_clock::time_point& exp);
Перенеси пожалуйста объявление функции над объявлением членов класса.
```suggestion
	model::Session prepare(
		const OIDCTokens& tokens,
		const TokenPayload& data,
		const std::string& userAgent,
		const std::chrono::system_clock::time_point& exp);

	table::Session& _table;
	tokens::Session& _tokenizer;
```

2023-09-12 06:29 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +		});
Завёл [баг](https://github.com/svetit-io/svetit/issues/24).  Тут повторный запуск таймера удали пожалуйста.

2023-09-12 08:40 UTC, prt0117 commented on src/back/auth/src/api/token_refresh.cpp
> +
Теперь поправил)

2023-09-12 08:40 UTC, prt0117 commented on src/back/auth/src/api/token_refresh.cpp
> +		LOG_WARNING() << "Fail to refresh session token: " << e.what();
Поправил.

2023-09-12 08:40 UTC, prt0117 commented on src/back/auth/src/model/errors.hpp
> +	SecurityRisk(const std::string& msg) : std::runtime_error{msg} {}
Поправил.

2023-09-12 08:40 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +
Поправил.

2023-09-12 08:40 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +	"WHERE userId=$1",
Поправил.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +
Не вижу, наверное, уже поправил ранее.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +		storages::postgres::ClusterHostType::kMaster, kMarkSessionInactive, sid);
Поправил.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/repo/table_session.hpp
> +	void BlockEverySessionByUser(const std::string& userId);
Готово.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/repo/table_session.hpp
> +	);
Готово.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	return refresh;
Поправил.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	const std::string& userAgent){
Готово.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +
Готово.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +){
Готово.

2023-09-12 08:41 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +		throw errors::SecurityRisk{"Different user agent."};
Готово.

2023-09-12 08:42 UTC, prt0117 commented on src/back/auth/src/service/service.hpp
> +	);
Готово.

2023-09-12 08:42 UTC, prt0117 commented on src/back/auth/src/service/session.cpp
> +){
Готово.

2023-09-12 08:42 UTC, prt0117 commented on src/back/auth/src/service/session.hpp
> +		const std::chrono::system_clock::time_point& exp);
Готово.

2023-09-12 08:42 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +		});
Поправил.

2023-09-13 02:17 UTC, lirik90 approved these changes

2023-09-13 03:39 UTC, merged