Обновление app компонента при принятии приглашения
svetit-io/svetit pull request #221
Opened 2024-06-26 09:38 UTC by prt0117

2024-07-05 20:21 UTC, lirik90 requested changes

2024-07-05 20:21 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<router-outlet (activate)="onRefresh($event)"></router-outlet>
Кажется тут должно быть onActivate?)

2024-07-05 20:21 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		);
А для чего такой трюк? Просто так не работает?
```suggestion
		this.space.Check().subscribe();
```

2024-07-05 20:21 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			}),
Так стало читаемее?

2024-07-05 20:40 UTC, lirik90 requested changes

2024-07-05 20:40 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +	@Output() refreshListComponentEvent = new EventEmitter<void>();
```suggestion
	@Output() onApprove = new EventEmitter<Detail>();
```

2024-07-05 20:40 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	onRefresh() {
```suggestion
	onInvitationApprove() {
```

2024-07-05 20:40 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +	}
В идеале компонент не должен знать о существовании каких то parent'ов. Если нужно, мы уведомляем о деяствиях которые мы совершаем, а тот кто нами управляет, на эти события реагирует.

```suggestion
		this.space.approveInvitation(item.id)
			.subscribe(_ => {
				this.goToFirstPage();
				this.onApprove.emit(item);
			});
	}

	goToFirstPage() {
		if (this.paginator.pageIndex == 0) {
			this.getItems(this.pageSize, 0);
		} else {
			this.paginator.firstPage();
		}
	}
```

Кажется в этом файле много мест где есть кусок кода из goToFirstPage, посмотри пожалуйста и замени по возможности на вызов goToFirstPage.

2024-07-05 21:04 UTC, lirik90 requested changes

2024-07-05 21:04 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	(refreshListComponentEvent)="onRefresh()"
```suggestion
	(onApprove)="onInvitationApprove($event)"
```

2024-07-05 21:04 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +	}
Вместо этого давай сделаем так:
1. Сделаем UserBadgeService который будет хранить userNotificationSize и spaceInvitationSize
2. Вынесем иконку пользователя с менюшкой в отдельный компонент
3. В этом компоненте делаем в конструкторе импорт сервиса публичным (public userBadges: UserBadgeService)
4. В шаблоне используем сервис для отображения уведомлений ...[matBadge]="userBadges.spaceInvitationSize"...
5. В SpaceListComponent при обработке события аппрува приглашения, уменьшаем кол-во уведомлений this.userBadges.spaceInvitationSize--

2024-07-16 09:03 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			}),
Наверное, что-то добавлял ещё внутри фигурных скобок, а потом удалил. Вернул, как было.

2024-07-16 10:16 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	onRefresh() {
> Кажется тут в detail достаточно инфы для добавления в список пространства. Давай тут вместо обновления всех списков точечно добавим то что изменилось в нужный список.

Вот такая инфа прилетает в detail:
```
Object { id: 47, spaceId: "1c6c06cf-d9c6-4717-b775-ae1b6954ceb5", userId: "e7f735cb-acb4-47ff-ba37-9cd0cd3126a1", role: "user", creatorId: "c5d34070-fd9f-4285-89ef-0ab9398d9d0f", createdAt: 1721124558, type: 1, userDisplayName: "test2 test2", userLogin: "test2", userEmail: "test2@example.com" }
```

Тут, получается, не всё, что нужно для добавления нового пространства в список пространств. Надо запрос будет делать на получение инфы о пространстве (его названия) по айдишнику, который у нас действительно есть в detail.

2024-07-18 06:46 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +	}
Готово, влил.

2024-07-29 04:00 UTC, lirik90 requested changes

2024-07-29 04:00 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +			// TODO - нужно перепроверить логику здесь, судя по всему, spaceInvitationSize - это подмножество userNotificationSize?
!

2024-07-29 05:17 UTC, lirik90 approved these changes

2024-07-29 05:18 UTC, merged