переключение локализации по куке
svetit-io/svetit pull request #225
Opened 2024-06-27 10:30 UTC by prt0117

2024-06-28 11:50 UTC, prt0117 commented
Также замечено, что сейчас при генерации фронта ресурсы в разных языковых директориях получают одинаковый анти-кеш хеш. Из-за этого для браузера, судя по всему, они выглядят одинаково и переключение языка не работает так, как требуется.
![image](https://github.com/svetit-io/svetit/assets/134271128/133cb62f-3f8b-4234-ab48-337dd06ff157)

Но проблема с отсутствием анти-кеш хеша на файлах в папке /assets/i18n/ тоже существует паралелльно, судя по всему. https://github.com/ngx-translate/http-loader/issues/25 и https://stackoverflow.com/questions/54840449/i18n-files-are-cached-in-production

2024-07-05 21:22 UTC, lirik90 commented on src/web/pipeline/server.nginx.conf
> +        try_files $uri /index.html?$args;
```suggestion
        try_files $uri /index.html$is_args$args;
```

2024-07-17 06:38 UTC, prt0117 commented
> Также замечено, что сейчас при генерации фронта ресурсы в разных языковых директориях получают одинаковый анти-кеш хеш. 

Проверил, что всё же по умолчанию некоторые статические ресурсы всё же отличаются анти-кеш хешом, то есть проблемы, о которой говорил на скрине выше, нет. Часть ресурсов имеют одинаковый хеш, но, судя по всему, они идентичны в обеих языковых версиях.

> Но проблема с отсутствием анти-кеш хеша на файлах в папке /assets/i18n/ тоже существует паралелльно, судя по всему. [ngx-translate/http-loader#25](https://github.com/ngx-translate/http-loader/issues/25) и https://stackoverflow.com/questions/54840449/i18n-files-are-cached-in-production

Что касается файлов с локалью, то доработал, чтобы добавлялся хеш, как советовали на SO и в Гитхабе по ссылкам выше.

2024-07-29 05:23 UTC, lirik90 requested changes

2024-07-29 05:23 UTC, lirik90 commented on src/web/angular.json
> +          "baseHref": "/"
А зачем тут этот кастомный параметр? Давай уберём в index.html

2024-07-29 05:23 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Что то тут не то. Зачем нам хэш если мы при каждой отдельной локали должны подгружать только один файл. Т.е. переключились на русский подгрузили ru.json , переключились на английский подгрузили en.json тут проблем быть не должно

2024-07-29 05:23 UTC, lirik90 commented on src/web/src/app/app.component.ts
> -			this.uiService.setCurLang(toLang);
Вот это кажется убирать нельзя было. Тут мы вроде как раз устанавливаем какой json файл нам подгружать

2024-07-29 06:21 UTC, prt0117 commented on src/web/angular.json
> +          "baseHref": "/"
Убрал, но при билде в докере всё равно подставляется данный параметр в index.html (в англ версии en, в русской ru):
![image](https://github.com/user-attachments/assets/dee4bbd3-466a-44a3-82ce-3d84ec2d0004)

2024-07-29 06:28 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Возможно, дело в том, что когда сейчас локаль переключается, фронт тянет в случае английского только en.json, а для русского и en.json, и ru.json.
Русская версия:
![image](https://github.com/user-attachments/assets/e7878513-e50c-43e9-9984-71dd8214fef0)
Английская:
![image](https://github.com/user-attachments/assets/666d230b-263b-45c0-8a17-cfe3f704e9f6)

Не знаю, с чем это связано.

Кстати, ещё вот такой баг сейчас есть https://github.com/svetit-io/svetit/issues/235 Возможно, как-то связано.

2024-07-29 06:42 UTC, prt0117 commented on src/web/src/app/app.component.ts
> -			this.uiService.setCurLang(toLang);
Вернул этот вызов. Проверил - работает, вроде, так же при беглом тесте. Также перепроверил с подгрузкой одновременно en.json и ru.json для русской локали - не поменялось это поведение.

2024-07-30 01:52 UTC, lirik90 requested changes

2024-07-30 01:52 UTC, lirik90 commented on src/web/src/app/app.component.ts
> -			this.uiService.setCurLang(toLang);
Теперь нужно убрать генерацию хэша для файлов .json

2024-07-30 01:53 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
А этот баг #235 не из за того что переводы там забыли добавить?

2024-07-30 02:19 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Когда собираешь такое сообщение как раз появляется.
![image](https://github.com/user-attachments/assets/c25c96e8-bb0d-4e3c-bb53-759008461a5f)

2024-07-30 02:20 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Кажется раньше я через qt linguist переводил. А ещё раньше google translate поддерживал .xlf можно было просто закинуть файл и от возвращал переведённый файл, но потом лавочку прикрыли, но возможно есть другие похожие сервисы которые так смогут.

2024-07-30 02:22 UTC, lirik90 commented on src/web/angular.json
> +          "baseHref": "/"
Не убрал видимо, я проверил, всё норм билдится. 
![image](https://github.com/user-attachments/assets/5db4e9d5-2d38-4ac5-90e8-8421338d1346)

2024-07-30 02:23 UTC, lirik90 commented
Сделай ребейз пожалуйста.

2024-07-30 03:14 UTC, prt0117 commented on src/web/angular.json
> +          "baseHref": "/"
Билдится-то норм, но обрати внимание, какой у тебя base href - "/en/". А должен же быть "/", если я правильно понимаю.

2024-07-30 03:20 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> Когда собираешь такое сообщение как раз появляется.
А где такое сообщение? Первый раз подобное вижу.

2024-07-30 03:20 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> А этот баг #235 не из за того что переводы там забыли добавить?

Да, надо это проверить в первую очередь.

2024-07-30 03:20 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> Кажется раньше я через qt linguist переводил. А ещё раньше google translate поддерживал .xlf можно было просто закинуть файл и от возвращал переведённый файл, но потом лавочку прикрыли, но возможно есть другие похожие сервисы которые так смогут.

Пометил себе, чтобы перепроверить файлы с переводами.

2024-07-30 03:20 UTC, prt0117 commented on src/web/src/app/app.component.ts
> -			this.uiService.setCurLang(toLang);
> Теперь нужно убрать генерацию хэша для файлов .json

Ок, проверю.

2024-07-30 03:23 UTC, prt0117 commented
> Сделай ребейз пожалуйста.

Готово.

2024-07-30 03:23 UTC, lirik90 commented on src/web/angular.json
> +          "baseHref": "/"
Ага, извини, не заметил что он его почему то в самый верх засунул. ((

2024-07-30 03:26 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> А где такое сообщение? Первый раз подобное вижу.

node_modules/.bin/ng build --configuration en

2024-07-30 03:28 UTC, lirik90 commented on src/web/angular.json
> +          "baseHref": "/"
Но в index.html давай всё равно поменяем <base href="/ru/"> на <base href="/"> чтобы не путаться

2024-07-30 03:30 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> > А где такое сообщение? Первый раз подобное вижу.
> 
> node_modules/.bin/ng build --configuration en

увидел. там довольно много ошибок - разберусь, в каком файле надо правки вносить.

2024-07-30 03:34 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Нужно этот файл сначала сгенерировать.

2024-07-30 03:36 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> Нужно этот файл сначала перегенерировать.

какой командой?

2024-07-30 03:43 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
node_modules/.bin/ng extract-i18n --out-file ./src/locale/messages.en.xlf

Кстати посмотри вывод, там видно что где то не правильно id перевода указан.
![image](https://github.com/user-attachments/assets/6c14c2da-5e8e-4901-bfcd-fc63cb318966)

2024-07-30 04:16 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> node_modules/.bin/ng extract-i18n --out-file ./src/locale/messages.en.xlf

Посмотрел вывод. Это же, получается, старый фронт. Надо в нём это пофиксить?

2024-07-30 04:20 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> node_modules/.bin/ng extract-i18n --out-file ./src/locale/messages.en.xlf

сделал так. потом перебилдил фронт в докере, протестил - всё равно на русском языке подтягивает два файла с локалью ру и ен. Попробую ошибки при экстракции поправить.

2024-07-30 04:21 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
А для русского языка так не надо сделать тоже?
node_modules/.bin/ng extract-i18n --out-file ./src/locale/messages.RU.xlf

2024-07-30 04:25 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Протестил и для русского файла. Всё равно тянутся ру и ен файлы в русской локали. Попробую сейчас ошибки переводов пофиксить.

2024-07-30 04:31 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Относительно ошибок есть вопрос:
```
WARNINGS:
 - Duplicate messages with id "CONTROL.SAVE":
   - "Сохранить" : src/app/schemes/detail/detail.component.html:56
   - "Сохранить" : src/app/scheme/param/param.component.html:8
   - "Сохранить" : src/app/scheme/param-item/param-item.component.html:73
   - "Сохранить" : src/app/scheme/status-manage-dialog/status-manage-dialog.component.html:52
   - "Сохранить" : src/app/scheme/elements/manage/section-detail-dialog/section-detail-dialog.component.html:16
   - "Cохранить" : src/app/scheme/elements/manage/device-item-group-detail-dialog/device-item-group-detail-dialog.component.html:19
   - "Сохранить" : src/app/scheme/elements/manage/device-item-detail-dialog/device-item-detail-dialog.component.html:45
   - "Cохранить" : src/app/scheme/elements/manage/device-detail-dialog/device-detail-dialog.component.html:28
   - "Сохранить" : src/app/scheme/elements/manage/device-item-type-detail-dialog/device-item-type-detail-dialog.component.html:49
   - "Сохранить" : src/app/scheme/elements/manage/device-item-group-type-detail-dialog/device-item-group-type-detail-dialog.component.html:16
   - "Сохранить" : src/app/scheme/elements/manage/sign-type-detail-dialog/sign-type-detail-dialog.component.html:8
   - "Сохранить" : src/app/scheme/elements/manage/plugin-detail-dialog/plugin-detail-dialog.component.html:8
   - "Сохранить " : src/app/scheme/reports/charts/chart-filter/chart-filter.component.html:152,153
   - "Сохранить" : src/app/scheme/settings/confirm-unsaved-changes-dialog/confirm-unsaved-changes-dialog.component.html:4
 - Duplicate messages with id "CONTROL.EDIT":
   - "Изменить" : src/app/scheme-groups/create-new-scheme-group/create-new-scheme-group.component.html:10
   - "Изменить" : src/app/scheme/reports/charts/chart-filter/chart-filter.component.html:139
   - "Изменить " : src/app/scheme/reports/charts/chart-filter/chart-filter.component.html:150,151
 - Duplicate messages with id "DEVICE_ITEM.LOADING":
   - "Загрузка" : src/app/scheme/dev-item-value/dev-item-value.component.html:13
   - "Установку значения нельзя отменить. Вы уверены что хотите сделать это?" : src/app/scheme/dev-item-value/holding-register-dialog.component.html:3
 - Duplicate messages with id "PARAMS.TITLE":
   - "Параметры" : src/app/scheme/param/param.component.html:2
   - "Уставки" : src/app/scheme/device-item-group/params-dialog/params-dialog.component.html:2
 - Duplicate messages with id "REPORTS.EXPORT.SELECT_SCHEME":
   - "Выберите проект" : src/app/scheme/reports/export/export.component.html:5
   - "Проекты" : src/app/scheme/reports/export/export.component.html:8
 - Duplicate messages with id "SETTINGS.ITEM.SIGNTYPES":
   - "Единицы измерения" : src/app/scheme/settings/settings.component.html:7
   - "Еденицы измерения" : src/app/scheme/settings/group-types/item-types.component.html:42
 - Duplicate messages with id "SETTINGS.TYPE":
   - "Тип" : src/app/scheme/settings/devices/deviceitems.component.html:43
   - "Категория" : src/app/scheme/settings/group-types/statuses.component.html:31
 ```
Это, вроде, не ошибки, а ворнинги. Как их можно поправить? В каждом месте, где встречается, например, CONTROL.SAVE заменить этот "ключ" на уникальный? К примеру, для 
"Сохранить" : src/app/schemes/detail/detail.component.html:56
это может быть SCHEMES.DETAIL.CONTROL.SAVE. И так везде. Пойдет такое решение?

2024-07-30 04:37 UTC, prt0117 commented on src/web/src/app/app.component.ts
> -			this.uiService.setCurLang(toLang);
> Теперь нужно убрать генерацию хэша для файлов .json

Убрал - ошибка вернулась, локаль не переключается (долго не ждал, пока кеш устареет). Наверное, сначала надо разобраться с подтягиванием и en, и ru файлов локали при переключении языка.

2024-07-30 04:43 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
Кстати, ещё заметил, что после выполнения команды извлечения строк переводов из сорцов, ресурсы для en перевода теперь не содержат <file source-language="ru" target-language="en"... , вместо этого там сейчас <file source-language="ru"... То есть пропал  target-language="en".

![image](https://github.com/user-attachments/assets/d94f1e0a-ae83-4bbc-9e13-b8b1e793ca16)

2024-07-30 04:46 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
И также пропали атрибуты другие:
![image](https://github.com/user-attachments/assets/2dbf138f-6b38-4395-b175-fd54ce034ee4)

Раньше было, например,
<source>Заголовок</source>
<target>Title</target>
А теперь только source без target.

2024-07-30 05:01 UTC, prt0117 commented on src/web/angular.json
> +          "baseHref": "/"
> Но в index.html давай всё равно поменяем на чтобы не путаться

Поменял в index.html, влил.

2024-07-30 07:00 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> А для русского языка так не надо сделать тоже? node_modules/.bin/ng extract-i18n --out-file ./src/locale/messages.RU.xlf

Для русского не надо, т.к. он у нас по умолчанию прописан

2024-07-30 07:04 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> Относительно ошибок есть вопрос

1. Там где CONTROL.SAVE в одном месте добавился перевод строки, а в двух других места первая буква не кириллицей написана, а латиницей. Поправь пожалуйста.
2. Примерно такие же проблемы и с CONTROL.EDIT
3. А вот например SETTINGS.TYPE явно указан не корректно в файле src/app/scheme/settings/group-types/statuses.component.html, там должен быть какой то свой ключ уникальный (в зависимости от того что там написано).


Давай это всё в отдельную задачу вынесем.

2024-07-30 07:06 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> То есть пропал target-language="en".

Здорово что заметил, значит нужно ключ дополнительный добавить для командной строки

2024-07-30 07:07 UTC, lirik90 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> А теперь только source без target

target Это мы должны добавить либо через qt linguist либо через сервис какой то.

2024-07-30 08:18 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> Давай это всё в отдельную задачу вынесем.

Создал задачку https://github.com/svetit-io/svetit/issues/238

2024-07-30 08:18 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> > А теперь только source без target
> 
> target Это мы должны добавить либо через qt linguist либо через сервис какой то.

что, поставить Qt Linguist? Или искать сторонний сервис?

2024-07-30 08:49 UTC, prt0117 commented on src/web/pipeline/Dockerfile
> +RUN export RAND1=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) && export RAND2=$(openssl rand -base64 12 | tr -dc A-Za-z0-9) \
> > То есть пропал target-language="en".
> 
> Здорово что заметил, значит нужно ключ дополнительный добавить для командной строки

у утилиты вот такие доступны ключи:
```
user@pc:~/svetit/src/web$ ./node_modules/.bin/ng extract-i18n --help
ng extract-i18n [project]

Extracts i18n messages from source code.

Arguments:
  project  The name of the project to build. Can be an application or a library.                      [string] [choices: "device-access", "device-access-e2e"]

Options:
      --help            Shows a help message for this command in the console.                                                                        [boolean]
  -c, --configuration   One or more named builder configurations as a comma-separated list as specified in the "configurations" section in angular.json.
                        The builder uses the named configurations to run the given target.
                        For more information, see https://angular.io/guide/workspace-config#alternate-build-configurations.                           [string]
      --browser-target  A browser builder target to extract i18n messages in the format of `project:target[:configuration]`. You can also pass in more than
                        one configuration name as a comma-separated list. Example: `project:target:production,staging`.                               [string]
      --format          Output format for the generated file.
                                         [string] [choices: "xmb", "xlf", "xlif", "xliff", "xlf2", "xliff2", "json", "arb", "legacy-migrate"] [default: "xlf"]
      --out-file        Name of the file to output.                                                                                                   [string]
      --output-path     Path where output will be placed.                                                                                             [string]
      --progress        Log progress to the console.                                                                                 [boolean] [default: true]
```

2024-08-02 09:16 UTC, lirik90 approved these changes

2024-08-02 09:16 UTC, lirik90 commented on src/web/src/app/app.module.ts
> +import { environment } from '../environments/environment';
Не используется

2024-08-02 09:16 UTC, lirik90 commented on src/web/src/locale/messages.ru.xlf
> +<?xml version="1.0" encoding="UTF-8" ?>
Кажется этот файл не используется

2024-08-02 09:17 UTC, merged