Контроль меняющего сессионного ключа
svetit-io/svetit pull request #231
Opened 2024-07-19 06:52 UTC by prt0117

2024-07-23 10:25 UTC, prt0117 commented
Надо подумать, как протестировать меняющийся ключ. Чтобы убедиться, что не только событие срабатывает, но и ключ на самом деле меняется.

2024-07-23 11:54 UTC, prt0117 commented
> Надо подумать, как протестировать меняющийся ключ. Чтобы убедиться, что не только событие срабатывает, но и ключ на самом деле меняется.

Протестил, вроде, ок.

2024-07-26 06:44 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +	_task = utils::Async("some_task",
может, тут нужно указать не основной task processor (fs-task-processor, например)

2024-08-05 03:03 UTC, lirik90 requested changes

2024-08-05 03:03 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +	_task = utils::Async("some_task",
Да, давай так и сделаем.

2024-08-05 03:03 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +            while (!engine::current_task::ShouldCancel()) {
Замени пробелы на табы

2024-08-05 03:03 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +					_jwt = std::make_shared<jwt_session_impl>(std::move(verifier), std::move(algo));
Вынеси этот большой кусок в отдельную функцию, потому что он повторяется два раза. 
Перезапись и чтение поля _jwt теперь должно быть защищено мьютексом. Посмотри в userver должен быть какой то вариант shared мьютекса (при котором не блокируется параллельное чтение), используй его. Если нет такого, то обычный.

2024-08-05 03:03 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +	_task.SyncCancel();
Проверь нормально ли останавливается приложение. 
Если inotify->Poll блокирующая операция, то вызов SyncCancel может наверное не сработать и может понадобится чтото другое.
Попробуй повставлять логов и вызвать SyncCancel ручкой посреди выполнения программы чтобы убедиться что эта таска действительно завершается корректно.

2024-08-05 03:04 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +        [privateKeyPath, this]{
```suggestion
	_task = utils::Async("some_task", [privateKeyPath, this] {
```

2024-08-05 03:27 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +            while (!engine::current_task::ShouldCancel()) {
Готово.

2024-08-05 04:24 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +	_task = utils::Async("some_task",
Готово, влил.

2024-08-05 04:40 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +	_task.SyncCancel();
Провёл предложенный тобой эксперимент. По-моему, корутина завершается успешно после того, как я вызвал SyncCancel через ручку в момент ожидания inotify->Poll. Влил эксперимент в отдельную ветку, если захочешь посмотреть, как я проверял https://github.com/svetit-io/svetit/commit/4cde77ad2124905c52eb756caf17a775b0a9af2d

2024-08-05 05:06 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +					_jwt = std::make_shared<jwt_session_impl>(std::move(verifier), std::move(algo));
Готово.

2024-08-05 05:53 UTC, lirik90 requested changes

2024-08-05 05:53 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +  	auto& fs_task_processor = ctx.GetTaskProcessor("fs-task-processor");
мы кажется переменные именуем в верблюжем регистре

2024-08-05 05:53 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +    );
```suggestion
		while (!engine::current_task::ShouldCancel()) {
			auto inotify = new engine::io::sys_linux::Inotify();
			inotify->AddWatch(privateKeyPath, engine::io::sys_linux::EventType::kModify);
			auto event = inotify->Poll(engine::Deadline());
			if (event) {
				LOG_WARNING() << "Session key changed";
				changeKey(privateKeyPath);
			}
		}
        });
```

2024-08-05 05:53 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +	std::shared_lock<engine::SharedMutex> lock(_mutex);
Тип указывать не обязательно если ты передаёшь значение.
```suggestion
	std::shared_lock lock(_mutex);
```

2024-08-05 05:53 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +	std::shared_lock<engine::SharedMutex> lock(_mutex);
```suggestion
	std::shared_lock lock(_mutex);
```

2024-08-05 05:53 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +	std::lock_guard<engine::SharedMutex> lock(_mutex);
```suggestion
	std::lock_guard lock(_mutex);
```

2024-08-05 06:27 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +  	auto& fs_task_processor = ctx.GetTaskProcessor("fs-task-processor");
Сорри, поправил.

2024-08-05 06:41 UTC, lirik90 requested changes

2024-08-05 06:41 UTC, lirik90 commented on src/back/auth/src/service/tokens_session.cpp
> +    });
Тут пробелы ((

2024-08-05 06:49 UTC, prt0117 commented on src/back/auth/src/service/tokens_session.cpp
> +    });
Поправил. Настрою IDE, чтобы подсвечивала, как у тебя подсвечивает.

2024-08-05 06:49 UTC, merged