Новый микросервис Узлы
svetit-io/svetit pull request #236
Opened 2024-07-29 10:36 UTC by prt0117

2024-08-05 18:51 UTC, lirik90 approved these changes

2024-08-05 18:51 UTC, lirik90 commented on src/back/node/db/app/migrations/V0001__Init.sql
> +	id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
Извини, забыл написать что тут нужно поле space_id. Давай пожалуйста сразу добавим.

2024-08-06 04:09 UTC, prt0117 commented on src/back/node/db/app/migrations/V0001__Init.sql
> +	id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
Добавил, влил.

2024-08-06 05:21 UTC, lirik90 requested changes

2024-08-06 05:21 UTC, lirik90 commented on src/back/node/src/api/list.cpp
> +		const auto spaceId = params["spaceId"].As<boost::uuids::uuid>();
spaceId неоткуда взяться если его никто не смапит
```suggestion
		const auto spaceId = params[std::string(headers::kSpaceId)].As<boost::uuids::uuid>();
```

2024-08-06 06:10 UTC, lirik90 approved these changes

2024-08-06 06:10 UTC, merged