feature/14-logout-button
svetit-io/svetit pull request #25
Opened 2023-09-13 04:47 UTC by prt0117

2023-09-13 06:31 UTC, lirik90 requested changes

2023-09-13 06:31 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +	public hasWspace: boolean;
Перемести его пожалуйста ближе к authorized по тому что у них близкие назначения. И public он по умолчанию кажется.
```suggestion
	authorized: boolean;
	hasWspace: boolean;
	private title$: Subscription;
```

2023-09-13 06:31 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<!--<button mat-icon-button i18n-matTooltip="@@CONTROL.EXIT" matTooltip="Выйти" (click)="auth.goToLogout()"><mat-icon>exit_to_app</mat-icon></button>-->
Забыл убрать коммент.

2023-09-13 06:31 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +			this.authorized = ok;
1. authorized - выставляется в isAuthorized, в wspace.isInitialized не нужен.
2. detectChanges - нужен чтобы обработать изменения свойств которые ты по подписке сделал. Т.е. он должен вызываться после изменения значения свойств.
3.  Блок с auth.isAuthorized лучше поместить перед блока с wspace.isInitialized так как логически это событие наступает раньше.
4. В hasWspace ты должен установить значение которое пришло по подписке, по аналогии с установкой this.authorized в auth.isAuthorized

```suggestion
		this.auth.isAuthorized().subscribe(ok => {
			this.authorized = ok;
			this.changeDetectorRef.detectChanges();
		});

		this.wspace.isInitialized().subscribe(ok => {
			this.hasWspace = ok;
			this.changeDetectorRef.detectChanges();
		});
```

2023-09-14 01:55 UTC, lirik90 requested changes

2023-09-14 01:55 UTC, lirik90 commented on src/web/src/app/app.component.html
>          <a routerLink="/user/scheme-groups" i18n="@@SCHEME_GROUPS.GROUPS">Группы</a>
Другие ссылки должны быть активны только если установлен hasWspace

2023-09-14 01:55 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a i18n="@@CONTROL.EXIT" (click)="auth.goToLogout()">Выйти</a>
Перед кнопкой должен быть разделитель

2023-09-14 04:30 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +	public hasWspace: boolean;
Готово.

2023-09-14 04:30 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<!--<button mat-icon-button i18n-matTooltip="@@CONTROL.EXIT" matTooltip="Выйти" (click)="auth.goToLogout()"><mat-icon>exit_to_app</mat-icon></button>-->
Готово.

2023-09-14 04:31 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +			this.authorized = ok;
Готово.

2023-09-14 04:31 UTC, prt0117 commented on src/web/src/app/app.component.html
>          <a routerLink="/user/scheme-groups" i18n="@@SCHEME_GROUPS.GROUPS">Группы</a>
Готово.

2023-09-14 04:31 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<a i18n="@@CONTROL.EXIT" (click)="auth.goToLogout()">Выйти</a>
Готово.

2023-09-14 06:37 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		</ng-container>
Кнопки должны быть не активные, а не исчезнуть совсем.

2023-09-14 07:10 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		</ng-container>
Готово.

2023-09-15 03:26 UTC, lirik90 requested changes

2023-09-15 03:26 UTC, lirik90 commented on src/web/src/app/app.component.html
> +        <a [ngClass]="hasWspace ? '': 'inactiveLink'" routerLink="/user/scheme-groups" i18n="@@SCHEME_GROUPS.GROUPS" inactiveLink>Группы</a>
А для чего тут в конце тега inactiveLink, вроде в HTML нет такого аттрибута? Как это работает?
И кажется можно лепить css классы к тегу так как в 56 строке сделано:
```suggestion
        <a [class.inactiveLink]="hasWspace" routerLink="/user" i18n="@@PROFILE">Профиль</a>
        <a [class.inactiveLink]="hasWspace" routerLink="/user/scheme-groups" i18n="@@SCHEME_GROUPS.GROUPS">Группы</a>
```

2023-09-15 03:26 UTC, lirik90 commented on src/web/src/app/app.component.ts
>  			this.authorized = ok;
Тут куда то пропал changeDetector.

2023-09-15 03:26 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +
Тут лишний отступ.

2023-09-15 03:50 UTC, prt0117 commented on src/web/src/app/app.component.html
> +        <a [ngClass]="hasWspace ? '': 'inactiveLink'" routerLink="/user/scheme-groups" i18n="@@SCHEME_GROUPS.GROUPS" inactiveLink>Группы</a>
Извиняюсь, не доглядел. Сначала хотел через кастомные атрибуты сделать, потом забыл этот inactiveLink убрать.

По варианту добавления классов, как в 56 строке, пока не разобрался. Если текущая реализация в целом устраивает, то можно её и оставить.

2023-09-15 03:58 UTC, prt0117 commented on src/web/src/app/app.component.html
> +        <a [ngClass]="hasWspace ? '': 'inactiveLink'" routerLink="/user/scheme-groups" i18n="@@SCHEME_GROUPS.GROUPS" inactiveLink>Группы</a>
Установку классов поменял на вариант, предложенный тобой. Работает.

2023-09-15 04:03 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +
Там дальше через пустую строку метод начинается. Не вижу лишнего отступа.

```
private title$: Subscription;
	
get isAdmin(): boolean {
	return this.user.isAdmin();
}
```

2023-09-15 04:03 UTC, prt0117 commented on src/web/src/app/app.component.ts
>  			this.authorized = ok;
А я его изначально и не поставил:) Поправил.

2023-09-15 04:08 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +
Там таб лишний в пустой строке. Он тут зелёным прямоугольником подсвечивается.) Т.е. тут в этом изменении показано что была пустая строка и потом к ней добавился таб.

2023-09-15 04:14 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +
А, всё, дошло:) Поправил)

2023-09-15 05:49 UTC, lirik90 approved these changes

2023-09-15 05:50 UTC, merged