Поправил описание ответов для списков
svetit-io/svetit pull request #268
Opened 2024-08-08 05:28 UTC by prt0117

2024-08-08 11:43 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +std::map<std::string, std::vector<model::UserInfo>> Service::GetUserInfoList(const std::string& search, const std::string& sessionId, uint32_t start, uint32_t limit) {
@lirik90 не стал создавать отдельную модель, так как пока нигде больше она не нужна, кроме этого места.

2024-08-09 03:37 UTC, lirik90 requested changes

2024-08-09 03:37 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +					return res["list"];
Тут кажется тебе вернётся уже описанный тип у которого есть такое поле, так что можно его использовать напрямую.
```suggestion
					this.hasUsers = res.list.length > 0;
					return res.list;
```

2024-08-09 03:37 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	return res;
Давай это вынесем в handler т.к. это уже генерация представления.

2024-08-09 03:49 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	return res;
Готово.

2024-08-09 04:04 UTC, lirik90 approved these changes

2024-08-09 04:04 UTC, lirik90 commented on src/back/auth/src/api/user_list.cpp
> +		res = map;
```suggestion
		auto items = _s.GetUserInfoList(search, sessionId, paging.start, paging.limit);
		
		res = std::map<std::string, std::vector<model::UserInfo>>{
			{"list", std::move(items)}
		};
```

2024-08-09 04:05 UTC, merged