feature/26-new-ms-space
svetit-io/svetit pull request #27
Opened 2023-09-15 06:22 UTC by prt0117

2023-09-15 06:34 UTC, lirik90 requested changes

2023-09-15 06:34 UTC, lirik90 commented on Makefile
> +	make -C src/back/space service-start-debug
А почему отдельно? Блок выше делает тоже самое, даже чуть больше.)

2023-09-15 06:34 UTC, lirik90 commented on src/back/space/configs/static_config.yaml.in
> +            task_processor: main-task-processor  # Run it on CPU bound task processor
Это убери пожалуйста. В МС Авторизации тоже потом уберём, но там к этому есть тест, хочу посмотреть как там работает прежде чем убирать. А тут и в следующих МС это дублировать не надо.

2023-09-15 06:34 UTC, lirik90 commented on src/back/space/src/api/hello.cpp
> +} // namespace svetit::space
Всё про hello убери пожалуйста из этого МС.

2023-09-15 06:35 UTC, lirik90 commented
Нужно ещё в docker compose прописать его.

2023-09-15 06:38 UTC, prt0117 commented on Makefile
> +	make -C src/back/space service-start-debug
Надо docker-compose.yml основной в этом случае править. Я специально в таком виде это сделал до тех пор, пока не будет понятно, будут ли какие-то особенности по интеграции в docker-compose.yml общий.

2023-09-15 06:39 UTC, prt0117 commented on src/back/space/configs/static_config.yaml.in
> +            task_processor: main-task-processor  # Run it on CPU bound task processor
Тогда придётся выпиливать это с теста в мс space, ок.

2023-09-15 06:42 UTC, lirik90 commented
Не работает доступ с фронта. Нужно пофиксить добавив путь в конфиг nginx

2023-09-18 04:24 UTC, prt0117 commented on Makefile
> +	make -C src/back/space service-start-debug
Поправил.

2023-09-18 04:24 UTC, prt0117 commented on src/back/space/configs/static_config.yaml.in
> +            task_processor: main-task-processor  # Run it on CPU bound task processor
Готово.

2023-09-18 04:24 UTC, prt0117 commented on src/back/space/src/api/hello.cpp
> +} // namespace svetit::space
Убрал.

2023-09-18 04:24 UTC, prt0117 commented
> Нужно ещё в docker compose прописать его.

Готово.

2023-09-18 04:52 UTC, prt0117 commented
> Не работает доступ с фронта. Нужно пофиксить добавив путь в конфиг nginx

Пока не получилось.

2023-09-21 09:30 UTC, prt0117 commented
> Не работает доступ с фронта. Нужно пофиксить добавив путь в конфиг nginx

Сделал, работает (см. предыдущий коммит).

2023-09-22 01:37 UTC, lirik90 requested changes

2023-09-22 01:37 UTC, lirik90 commented on src/back/space.Dockerfile
> +FROM archlinux/archlinux:base-devel AS builder
Почему то докерфайл совсем пустой. Так же МС будет не доступен.

2023-09-22 01:37 UTC, lirik90 commented on src/back/space/src/api/hello_benchmark.cpp
> +BENCHMARK(HelloBenchmark);
Этот файл лишний. Удали пожалуйста.

2023-09-22 03:13 UTC, lirik90 requested changes

2023-09-22 03:13 UTC, lirik90 commented on src/back/space/configs/config_vars.yaml
> +server-port: 8083
Добавь пожалуйста путь этого файла в .gitignore А сам файл переименуй пожалуйста в config_vars.yaml.example

2023-09-22 03:13 UTC, lirik90 commented on src/back/space/configs/config_vars_testing.yaml
> +server-port: 8083
Сделай пожалуйста тоже самое что и для config_vars.yaml

2023-09-22 05:16 UTC, prt0117 commented on src/back/space.Dockerfile
> +FROM archlinux/archlinux:base-devel AS builder
Поправил.

2023-09-22 05:26 UTC, prt0117 commented on src/back/space/src/api/hello_benchmark.cpp
> +BENCHMARK(HelloBenchmark);
Готово.

2023-09-22 05:47 UTC, prt0117 commented on src/back/space/configs/config_vars.yaml
> +server-port: 8083
Готово.

2023-09-22 05:50 UTC, prt0117 commented on src/back/space/configs/config_vars_testing.yaml
> +server-port: 8083
Готово.

2023-09-22 05:54 UTC, lirik90 approved these changes

2023-09-22 05:59 UTC, merged