Дальнейшее использование сгенерированного Angular клиента
svetit-io/svetit pull request #270
Opened 2024-08-08 06:54 UTC by prt0117

2024-08-09 04:18 UTC, lirik90 requested changes

2024-08-09 04:18 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		}
Неизвестную пока никак не обрабатываем.

Давай попробуем упростить так:
```suggestion
		return Object.keys(ApiInvitationRole.RoleEnum)
			.find(key => ApiInvitationRole.RoleEnum[key] === role);
```

2024-08-09 04:18 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		private apiSpaceService: ApiSpaceService,
Давай покороче попробуем
```suggestion
		private api: ApiSpaceService,
```

2024-08-09 04:18 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +import { Spaces as ApiSpaces } from '../api';
Для чего эта обёртка если с другим Spaces никак не конфликтует? Посмотри везде пожалуйста.

2024-08-09 04:18 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		return this.apiSpaceService.handlerInvitationPost("user", {
Подобные XUser хидеры перетрутся проксёй. Передаём пустые значения:
```suggestion
		return this.apiSpaceService.handlerInvitationPost('', {
```

2024-08-09 04:45 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		return this.apiSpaceService.handlerInvitationPost("user", {
Поправил везде.

2024-08-09 04:45 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +import { Spaces as ApiSpaces } from '../api';
Я так назвал, чтобы выделить новые сгенерированные модели. Чтобы было проще старые модели потом выпилить. Теперь убрал обертки везде, кроме одного места, где надо отдельно переписывать со старой модели на новую.

2024-08-09 04:45 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		private apiSpaceService: ApiSpaceService,
Поправил везде.

2024-08-09 04:45 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	roleFromString(role: string): InvitationRole.RoleEnum {
Вот это переписать не получилось.
```
roleFromString(role: string): InvitationRole.RoleEnum {
    return Object.keys(InvitationRole.RoleEnum)
      .find(key => InvitationRole.RoleEnum[key] === role);
  }`
```
Вот это выдавало ошибку:
![image](https://github.com/user-attachments/assets/c1e41639-c995-4f2a-b711-6d92b8293928)

2024-08-09 04:46 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	roleFromString(role: string): InvitationRole.RoleEnum {
![image](https://github.com/user-attachments/assets/9fa85550-9602-4cbd-9e44-091b58388c6b)

2024-08-09 07:33 UTC, lirik90 requested changes

2024-08-09 07:33 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +			}),
```suggestion
			map(res => res.list),
```

2024-08-09 07:33 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
>  				}))
Тут точно не ошибка? Раньше было return res.list;
Если не ошибка, то давай тогда как то так:
```suggestion
				tap(res => this.hasUsers = res.length > 0)
```

2024-08-09 07:33 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	spaces: ApiSpace[] = [];
Тут Space нельзя?

2024-08-09 07:33 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			);
А зачем такое? Что будет не так если всегда передавать name ?

2024-08-09 07:33 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		}
А если так:
```suggestion
		const key = Object.keys(InvitationRole.RoleEnum)
			.find(key => InvitationRole.RoleEnum[key] == role);
		return InvitationRole.RoleEnum[key];
```

2024-08-09 08:26 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		}
Работает, поправил.

2024-08-09 08:26 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			);
Вроде, всё штатно, если пустой spaceName передавать. Однако на бэке у нас другой метод сервиса вызывается в случае наличия spaceName (даже, если он пустой). Переписать на бэке тоже?

2024-08-09 08:26 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	spaces: ApiSpace[] = [];
Можно, но нужно будет компонент немного переписать, так как в нём 3 метода, которые в параметрах принимают наш старый Space. Переписать? Думаю, все должно быть штатно. Состав полей должен быть одинаковый, по идее.

2024-08-09 08:26 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.ts
>  				}))
Точно не ошибка. Готово.

2024-08-09 08:26 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +			}),
Готово.

2024-08-12 02:05 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	spaces: ApiSpace[] = [];
Да, давай. 3 места не так много.

2024-08-12 02:19 UTC, lirik90 requested changes

2024-08-12 02:19 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			);
Конкретно тут нужно заменить в определении функции name: string = '' на **name: string = undefined**
А в МС на C++ меняем:
```c++
std::string spaceName;                                
if (params.HasMember("spaceName")) {                  
   spaceName = params["spaceName"].As<std::string>();
```
на:
```c++
std::string spaceName = params["spaceName"].As<std::string>("");
if (!spaceName.empty()) {
```

Тут несколько мест с таким вот if else, попробуй сделать так везде.

2024-08-12 06:42 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	spaces: ApiSpace[] = [];
Готово.

2024-08-12 06:42 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			);
Готово, тут и в других методах этого сервиса.

2024-08-12 06:43 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	roleFromString(role: string): InvitationRole.RoleEnum {
Не актуально, переписали в другом месте.

2024-08-12 12:43 UTC, lirik90 approved these changes

2024-08-12 12:44 UTC, merged