Feature/19 ms spaces
svetit-io/svetit pull request #29
Opened 2023-09-22 06:45 UTC by prt0117

2023-09-23 06:27 UTC, lirik90 requested changes

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +import { TempSpaceComponent } from "./space/temp/space/component";
А почему Temp ?)

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +	canActivate: [authGuard]},
А зачем canActivate на новую строку перенёс?

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +	canActivate: [authGuard]},
Перенеси всё это чуть ниже usertest и это позволит убрать canActivate

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a routerLink="/temp">Temp</a>
Ты же в этой ветке делаешь конкретную задачу, значит и названия можно сразу писать которые понадобятся.

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/space/temp/add/component.css
> +}
Зачем три одинаковых класса которые делают одно и тоже? Назови их общим именем и примени везде где тебе нужно.

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/space/temp/add/component.html
> +</div> <!-- create-wrap -->
Мы можем использовать angular material пока у нас нет дизайна. Посмотри пожалуйста файл 
src/web/src/app/schemes/list/create-scheme-dialog/create-scheme-dialog.html там оно используется. 

Вот сайт с описанием компонентов. https://angularmaterial.dev/components/input/overview

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/space/temp/component.html
> +</ul>
А зачем нужен этот файл если в самих страницах есть ссылки друг на друга?

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/space/temp/spaces/component.css
> +	padding-left: 10px;
Очень много дублирования в css. Нужно как можно проще и как можно короче. + используем angular material

2023-09-23 06:27 UTC, lirik90 commented on src/web/src/app/space/temp/spaces/component.html
> +	</div>
Вместо дублирования нужно использовать for цикл и брать данные из массива. Пока сервер не возвращает никаких данных, можно заполнить массив тестовыми данными в коде компонента.

2023-09-24 23:41 UTC, lirik90 commented on src/web/src/app/space/temp/add/component.html
> +<hr>
Давай заголовок Добавить уберём

2023-09-25 05:45 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +	canActivate: [authGuard]},
Готово.

2023-09-25 05:45 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<a routerLink="/temp">Temp</a>
Готово.

2023-09-25 05:45 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +	canActivate: [authGuard]},
Поправил)

2023-09-25 05:45 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +import { TempSpaceComponent } from "./space/temp/space/component";
Поправил)

2023-09-25 05:53 UTC, prt0117 commented on src/web/src/app/space/temp/add/component.css
> +}
Готово.

2023-09-25 08:21 UTC, prt0117 commented on src/web/src/app/space/temp/add/component.html
> +<hr>
Готово.

2023-09-25 08:48 UTC, prt0117 commented on src/web/src/app/space/temp/component.html
> +</ul>
Готово, добавил перелинковку между новыми страницами.

2023-09-25 09:52 UTC, prt0117 commented on src/web/src/app/space/temp/add/component.html
> +</div> <!-- create-wrap -->
Переверстал на material.

2023-09-25 10:57 UTC, prt0117 commented on src/web/src/app/space/temp/spaces/component.html
> +	</div>
Готово.

2023-09-26 03:11 UTC, lirik90 requested changes

2023-09-26 03:11 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/:id', component: SpaceDetailComponent, data: {title: 'Space'}},
Почему заголовки ни как везде?
NAVIGATION.SPACE
Скорее всего это для переводов нужно.

2023-09-26 03:11 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a routerLink="/space/list">Пространства</a>
Нет условия [class.inactiveLink] 
Нет ключа для i18n

2023-09-26 03:11 UTC, lirik90 commented on src/web/src/app/space/detail/component.css
> +}
Зачем столько дублирования? Зачем нужны разные классы которые делают одно и тоже?

2023-09-26 03:11 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +<h1>Пространство Space1</h1>
Space1 нужно заменить на переменную с именем пространства.

2023-09-26 03:11 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		{name: 'Пространство №3', user: "kolya", roles: ["admin", "user", "guest"]},
У одного пользователя не может быть несколько ролей.

2023-09-26 06:59 UTC, prt0117 commented on src/web/src/app/space/temp/spaces/component.css
> +	padding-left: 10px;
Готово (оптимизировал css).

2023-09-26 08:09 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/:id', component: SpaceDetailComponent, data: {title: 'Space'}},
Готово.

2023-09-26 08:16 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<a routerLink="/space/list">Пространства</a>
Готово (ключ для i18n не понимаю, какой должен быть, указал пока @@SPACES.LIST).

2023-09-26 08:18 UTC, prt0117 commented on src/web/src/app/space/detail/component.css
> +}
Поправил.

2023-09-26 08:21 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<h1>Пространство Space1</h1>
Готово.

2023-09-26 08:24 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		{name: 'Пространство №3', user: "kolya", roles: ["admin", "user", "guest"]},
Цитирую описание задачи:
"Если же приглашение не для этого пользователя, значит этот пользователь является админом space куда пригласили какого-то пользователя. Напротив такой записи выпадающий список с Ролью".

2023-09-26 08:46 UTC, lirik90 requested changes

2023-09-26 08:46 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		{name: 'Пространство №3', user: "kolya", roles: ["admin", "user", "guest"]},
Разбираем цитату: "Если же приглашение не для этого пользователя, значит этот пользователь является админом space"

"приглашение не для этого пользователя" - Пользак А смотрит на приглашение для пользака Б
"значит этот пользователь является админом space" - пользак А является админом space, а пользак Б не имеет пока никакой роли в space, по тому что он вообще не состоит в space 

Вывод:
У пользака А - одна роль Админ
У пользака Б - будет только одна роль, такая какую назначит ему пользак А

2023-09-26 08:46 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +<h1>Пространство Space1</h1>
Что-то не видать. (

2023-09-26 08:48 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<h1>Пространство Space1</h1>
Забыл влить, влил.

2023-09-26 10:54 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		{name: 'Пространство №3', user: "kolya", roles: ["admin", "user", "guest"]},
Готово (на основе дополнительного обсуждения).

2023-09-27 01:36 UTC, lirik90 requested changes

2023-09-27 01:36 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +	selector: 'app-temp',
Тут ещё остался temp. Нужно заменить на что-то вроде app-space-add

2023-09-27 01:36 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +		<button class="space-invites-heading-addbtn mat-icon-button">+</button>
А что делает space-invites-heading-addbtn?
```suggestion
		<button mat-icon-button><mat-icon>person_add</mat-icon></button>
```

2023-09-27 01:36 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +		<button class="space-linkinvites-heading-addbtn mat-icon-button">+</button>
```suggestion
		<button mat-icon-button><mat-icon>add</mat-icon></button>
```

2023-09-27 01:36 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +			<div class="left-float left-padding"><button mat-icon-button>Х</button></div>
```suggestion
			<div class="left-float left-padding"><button mat-icon-button><mat-icon>close</mat-icon></button></div>
```

2023-09-27 01:36 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +				  <option>admin</option>
```suggestion
				  <option value="admin">Админ</option>
```

2023-09-27 03:54 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +	selector: 'app-temp',
Готово.

2023-09-27 03:58 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +		<button class="space-invites-heading-addbtn mat-icon-button">+</button>
Готово, поправил.

2023-09-27 03:58 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +		<button class="space-linkinvites-heading-addbtn mat-icon-button">+</button>
Готово, поправил.

2023-09-27 03:59 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +			<div class="left-float left-padding"><button mat-icon-button>Х</button></div>
Готово.

2023-09-27 05:16 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +				  <option>admin</option>
Готово.

2023-09-27 10:04 UTC, lirik90 commented on src/web/src/app/material.module.ts
> +import { MatLegacyAutocompleteModule} from '@angular/material/legacy-autocomplete';
А почему Legacy?

2023-09-27 10:08 UTC, prt0117 commented on src/web/src/app/material.module.ts
> +import { MatLegacyAutocompleteModule} from '@angular/material/legacy-autocomplete';
Без Legacy был конфликт, как я понимаю, между Legacy и не Legacy <mat-option>.
![изображение](https://github.com/svetit-io/svetit/assets/134271128/345bd3d8-e5fc-46cf-8fa4-2cdcc132382d)

2023-09-28 03:29 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +	</div>
Кажется тут лишний отступ.

2023-09-28 08:10 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +	</div>
Поправил.

2023-09-28 11:42 UTC, prt0117 commented on src/web/src/app/app.component.html
> +      <button mat-button (click)=select.open()>
@lirik90 поменял кнопку, чтобы более-менее отображалось корректно. вероятно, этот селект поехал после обновления legacy селекта в materal.module.ts (в рамках задачи по переходу на не legacy autocomplete). скажи, как должно выглядеть, если не нравится так.

![изображение](https://github.com/svetit-io/svetit/assets/134271128/92ddf297-d4d7-4773-a061-fdf168537f5f)
![изображение](https://github.com/svetit-io/svetit/assets/134271128/07addf8d-e9bb-44c5-bc50-762948cb5a6a)

2023-09-28 11:58 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace]);
@lirik90 вот тут спорный редирект. возможно, как-то иначе можно передать в другой компонент информацию о том, в какое пространство пользователь отправил запрос на присоединение.

2023-09-28 11:59 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +
@lirik90 дам потом нормальное имя, забыл отрефакторить.

2023-09-29 08:19 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +
Готово.

2023-09-29 08:44 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			newKey = newKey.replace(/[^a-zA-Z0-9_]/g, '');
@lirik90 вот тут надо переписать регулярку, чтобы ключ записывался только строчными буквами. поменяю позже. уже ничего не буду трогать, пока ты не посмотришь по тем проблемам, о которых я говорил сегодня.

2023-09-29 08:44 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +				Validators.pattern('[a-zA-Z0-9_]*'),
@lirik90 здесь тоже регулярку надо переписать, чтобы форма принимала только строчные буквы у ключа. позже планирую сделать.

2023-10-02 03:49 UTC, lirik90 requested changes

2023-10-02 03:49 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +import { SpaceRequestSentComponent } from './space/space-request-sent/space-request-sent.component';
Предлагаю файлы новых создаваемых компонентов называть просто component, так как имя компонента есть в названии папки. 
```suggestion
import { SpaceRequestSentComponent } from './space/space-request-sent/component';
```

2023-10-02 03:49 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/add/request/:id', component: SpaceRequestSentComponent, data: {title: 'NAVIGATION.SPACE'}},
У страниц должен быть разный заголовок

2023-10-02 03:49 UTC, lirik90 commented on src/web/src/app/app.component.html
> +      <button mat-button (click)=select.open()>
Да, стало лучше.
Попробуй пожалуйста добиться чтобы выглядело так как до обновления. Т.е. как сейчас на проде v1.0

2023-10-02 03:49 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			newKey = newKey.replace(/[^a-zA-Z0-9_]/g, '');
Напомни пожалуйста о каких проблемах речь. 🙈

2023-10-02 03:49 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace]);
Думаю и так сойдёт. Вроде ещё можно вот так, но не уверен лучше ли это:
```suggestion
		this.router.navigate(['space/add/request', this.selectedSpace]);
```

2023-10-02 09:55 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			newKey = newKey.replace(/[^a-zA-Z0-9_]/g, '');
цитирую:возникли следующие проблемы, с которыми пока не разобрался:

1) изначально при загрузке страницы у меня пустой массив с пространствами, я добавляю через форму новые пространства в него, но автокомплит их не видит до тех пор, пока я не начну печатать в автокомплите, в этом случае успешно подтягивает все новые элементы из массива. при этом когда был массив с самого начала не пустой, то при загрузке страницы автокомплит работал корректно при клике на нём и сразу показывал 10 первых пространств. тут проблема в плоскости, наверное, инициализации наблюдения за изменениями в автокомплите, ngOnInit и change detection. пока знаний не хватает, чтобы сходу это починить. могу дальше разбираться. 

2) код, который я взял со SO, для автокомплита ориентируется на массив строк, а сейчас у меня источником информации о пространствах является массив объектов Space (внутри name и key), и пока у меня не получилось переписать все эти pipe'ы и subscribe'ы на массив. поэтому у меня при добавлении пространства идёт добавление одновременно в два массива (один с объектами и он должен в идеале и остаться только, второй со строками с названиями пространств). могу дальше рыть.

==

Если же захочешь эти места посмотреть и откомментить, могу пока на новые страницы переключиться, оставив add page в текущем виде.

2023-10-02 10:27 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			newKey = newKey.replace(/[^a-zA-Z0-9_]/g, '');
Обе проблемы пофикшены.

2023-10-02 11:58 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace]);
Так не работает.

2023-10-03 02:20 UTC, lirik90 requested changes

2023-10-03 02:20 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		}).join("");
```suggestion
		return word
			.split('')
			.map(char => this.translitFromRuToEn[char] || char)
			.join('');
```

2023-10-03 02:20 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			newKey = newKey.replace(/[^a-zA-Z0-9_]/g, '');
Если функция возвращает явный тип, то тип переменной указывать не нужно.
Сначала лучше привести к нижнему регистру, тогда транслитить можно будет меньшим массивом.

```suggestion
			let newKey = name.toLowerCase();
			newKey= this._transliterate(name);
			newKey = newKey.replace(/[^a-z0-9_]/g, '');
```

2023-10-03 02:20 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +	};
Ключ у нас в нижнем регистре, по этому транслитить нужно будет только нижний регистр. Заглавные буквы давай уберём из массива.

2023-10-03 02:20 UTC, lirik90 commented on src/web/src/app/space/space-request-sent/space-request-sent.component.ts
> +    }
Замени пожалуйста пробелы на табы.
```suggestion
		this.space = this.route.snapshot.paramMap.get('id');
	}
```

2023-10-03 02:20 UTC, lirik90 commented on src/web/src/app/space/space-request-sent/space-request-sent.component.html
> +<p>Запрос на присоединение к пространству '{{space}}' отправлен.</p>
Тут должно быть имя пространства, а не id

2023-10-03 02:20 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +</div>
А зачем тут ещё один div ? Пагинатор же сам уже div. 
```suggestion
<mat-paginator *ngIf="refs.length > refsPageSize"
	[length]="refs.length"
	[pageSize]="refsPageSize"
	(page)="pageEvent = getPaginatorRefs($event)">
</mat-paginator> 
```

2023-10-03 05:41 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +</div>
Поправил.

2023-10-03 05:42 UTC, prt0117 commented on src/web/src/app/space/space-request-sent/space-request-sent.component.html
> +<p>Запрос на присоединение к пространству '{{space}}' отправлен.</p>
Поправил.

2023-10-03 05:43 UTC, prt0117 commented on src/web/src/app/space/space-request-sent/space-request-sent.component.ts
> +    }
Готово.

2023-10-03 05:44 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +	};
Готово.

2023-10-03 05:47 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			newKey = newKey.replace(/[^a-zA-Z0-9_]/g, '');
Готово.

2023-10-03 05:48 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		}).join("");
Готово.

2023-10-03 05:49 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/add/request/:id', component: SpaceRequestSentComponent, data: {title: 'NAVIGATION.SPACE'}},
Готово.

2023-10-03 05:54 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +import { SpaceRequestSentComponent } from './space/space-request-sent/space-request-sent.component';
Готово.

2023-10-03 05:54 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +				Validators.pattern('[a-zA-Z0-9_]*'),
Готово.

2023-10-03 06:24 UTC, lirik90 requested changes

2023-10-03 06:24 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/add/request/:id', component: SpaceRequestSentComponent, data: {title: 'NAVIGATION.SPACEQUESTSENT'}},
Quest?)

2023-10-03 06:24 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST" ><span class="badge">* </span>Пространства</a>
В задаче кружок, а тут звёздочка.) Кружок должен появляться по условию что есть новые Приглашения/Запросы. Кружок так же должен висеть над иконкой пользователя. И сделай пожалуйста кружок жёлтым.

2023-10-03 06:24 UTC, lirik90 commented on src/web/src/app/space/space-request-sent/component.html
> +<p>Запрос на присоединение к пространству '{{space}}' отправлен.</p>
Всё равно Id, а должно быть название.

2023-10-03 06:54 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/add/request/:id', component: SpaceRequestSentComponent, data: {title: 'NAVIGATION.SPACEQUESTSENT'}},
Сорри) Request)

2023-10-03 06:58 UTC, prt0117 commented on src/web/src/app/space/space-request-sent/component.html
> +<p>Запрос на присоединение к пространству '{{space}}' отправлен.</p>
Всё, вроде, нормально. Название отображается.
![изображение](https://github.com/svetit-io/svetit/assets/134271128/bf782fcf-e40f-4b60-92bd-79557b8b0710)

2023-10-03 08:28 UTC, prt0117 commented on src/web/src/app/app.component.html
> +      <button mat-button (click)=select.open()>
Готово.

2023-10-03 08:30 UTC, prt0117 commented on src/web/src/app/app.component.html
> +      <button mat-button (click)=select.open()>
Сейчас у меня вот так свернутом состоянии:

![изображение](https://github.com/svetit-io/svetit/assets/134271128/f58230a1-0d2e-4a16-8e5c-4e4c8c007a90)

И в раскрытом состоянии:
![изображение](https://github.com/svetit-io/svetit/assets/134271128/906216fc-b723-476f-aff7-8f0e031b504a)

2023-10-03 09:12 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<a [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST" ><span class="badge">* </span>Пространства</a>
Готово.

Получилось вот так:
![изображение](https://github.com/svetit-io/svetit/assets/134271128/f3693474-6ecd-4def-8ac3-26fefb52c7eb)
![изображение](https://github.com/svetit-io/svetit/assets/134271128/f7fdc29e-39e5-49fe-8025-11dcad826cd3)

2023-10-03 09:58 UTC, prt0117 commented on src/web/src/app/app.component.html
> +      <button mat-button (click)=select.open()>
В целом, починил, но сейчас остался небольшой баг - не вся область кнопки выбора языка кликабельна, а только её нижняя правая часть. Пока не знаю, как пофиксить.
![Снимок экрана от 2023-10-03 15-57-38](https://github.com/svetit-io/svetit/assets/134271128/a1e053c5-3244-45ce-9216-8a8459c6094e)
![Снимок экрана от 2023-10-03 15-57-44](https://github.com/svetit-io/svetit/assets/134271128/65444ffa-bfad-40ca-81bf-00db47fe2a80)

2023-10-04 02:47 UTC, lirik90 requested changes

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.html
> +	  <mat-icon *ngIf="!activeBadge" class="app-toolbar__user-icon">person</mat-icon>
Классный компонент ты нашёл. Я и не знал что есть готовый matBadge. Давай тогда под него с бэка вернём вернём кол-во приглашений.
```suggestion
		<mat-icon
			class="app-toolbar__user-icon"
			[matBadgeHidden]="!userNotificationSize"
			[matBadge]="userNotificationSize"
			matBadgePosition="after"
			matBadgeSize="small">person</mat-icon>
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a *ngIf="!activeBadge" [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST">Пространства</a>
```suggestion
		<a [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST"
			[matBadgeHidden]="!spaceInvitationSize"
			[matBadge]="spaceInvitationSize"
			matBadgePosition="before"
			matBadgeSize="small">Пространства</a>
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +	activeBadge: boolean = false;
```suggestion
	userNotificationSize: number = 0;
	spaceInvitationSize: number = 0;
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +		this.activeBadge = this.isSpacesBadge();
Тут складываем все уведомления для пользователя. Пока это только spaceInvitationSize, но есть идея ещё кое-каких уведомлений добавить в будущем. )
invitationSize придёт с бэка.

```suggestion
		this._subSpace = this.space.isInitialized().subscribe(res => {
			if (!res)
				return;
			this.initialized = true;

			const invitationSize = 1; // res.invitationSize
			this.spaceInvitationSize = invitationSize;
			this.userNotificationSize += invitationSize;
			this.changeDetectorRef.detectChanges();
		});
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator  *ngIf="spaces.length > 7" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></mat-paginator>
```suggestion
	<mat-paginator  *ngIf="spaces.length > spacesPageSize" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></mat-paginator> 
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator *ngIf="spacerefs.length > 7" class="width-and-clear" [length]="spacerefs.length" [pageSize]="refsPageSize" (page)="pageEvent = getPaginatorRefs($event)"></mat-paginator>
```suggestion
	<mat-paginator *ngIf="spacerefs.length > refsPageSize" class="width-and-clear" [length]="spacerefs.length" [pageSize]="refsPageSize" (page)="pageEvent = getPaginatorRefs($event)"></mat-paginator> 
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator  *ngIf="spaceinvites.length > 7" class="spaces-invites-wrap" [length]="spaceinvites.length" [pageSize]="invitesPageSize" (page)="pageEvent = getPaginatorInvites($event)"></mat-paginat
```suggestion
	<mat-paginator  *ngIf="spaceinvites.length > invitesPageSize" class="spaces-invites-wrap" [length]="spaceinvites.length" [pageSize]="invitesPageSize" (page)="pageEvent = getPaginatorInvites($event)"></mat-paginator> 
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace.name]);
Имя может содержать любые символы. Передавать его в Query параметрах не вариант. Нужно передавать как в [этом](https://stackblitz.com/edit/angular-bupuzn) примере

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace.name]);
Имя может содержать любые символы, передавать в УРЛе его не вариант. Нужно сделать как в [этом](https://stackblitz.com/edit/angular-bupuzn) примере.

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +		this.activeBadge = this.isSpacesBadge();
invitationSize будет приходить с бэка.
В userNotificationSize суммируем все уведомления для пользователя, пока это только invitationSize, но есть идея добавить ещё =)

```suggestion
		this._subSpace = this.space.isInitialized().subscribe(res => {
			if (!res)
				return;
			this.initialized = true;
			const invitationSize = 1; // res.invitationSize
			this.spaceInvitationSize = invitationSize;
			this.userNotificationSize += invitationSize;
			this.changeDetectorRef.detectChanges();
		});
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +	activeBadge: boolean = false;
```suggestion
	userNotificationSize = 0;
	spaceInvitationSize = 0;
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a *ngIf="!activeBadge" [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST">Пространства</a>
```suggestion
		<a [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST"
			[matBadgeHidden]="!spaceInvitationSize"
			[matBadge]="spaceInvitationSize"
			matBadgePosition="before"
			matBadgeSize="small">Пространства</a>
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/app.component.html
> +	  <mat-icon *ngIf="!activeBadge" class="app-toolbar__user-icon">person</mat-icon>
```suggestion
		<mat-icon class="app-toolbar__user-icon"
			[matBadgeHidden]="!userNotificationSize"
			[matBadge]="userNotificationSize"
			matBadgePosition="after"
			matBadgeSize="small">person</mat-icon>
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator *ngIf="invites.length > 7" class="width-and-clear" [length]="invites.length" [pageSize]="invitesPageSize" (page)="pageEvent = getPaginatorInvites($event)"></mat-paginator>
```suggestion
<mat-paginator *ngIf="invites.length > invitesPageSize" class="width-and-clear" [length]="invites.length" [pageSize]="invitesPageSize" (page)="pageEvent = getPaginatorInvites($event)"></mat-paginator>
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator *ngIf="refs.length > 7" class="width-and-clear" [length]="refs.length" [pageSize]="refsPageSize" (page)="pageEvent = getPaginatorRefs($event)"></mat-paginator>
```suggestion
<mat-paginator *ngIf="refs.length > refsPageSize" class="width-and-clear" [length]="refs.length" [pageSize]="refsPageSize" (page)="pageEvent = getPaginatorRefs($event)"></mat-paginator> 
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator *ngIf="users.length > 7" class="width-and-clear" [length]="users.length" [pageSize]="usersPageSize" (page)="pageEvent = getPaginatorUsers($event)"></mat-paginator>
```suggestion
<mat-paginator *ngIf="users.length > usersPageSize" class="width-and-clear" [length]="users.length" [pageSize]="usersPageSize" (page)="pageEvent = getPaginatorUsers($event)"></mat-paginator> 
```

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +		<div class="left-float left-padding">vasya112@example.com</div>
Тут почему то email прибит

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +					<option value="guest">guest</option>
Отображаемые значения должны быть написаны по русски и с переводом в будущем.

2023-10-04 02:47 UTC, lirik90 commented on src/web/src/app/material.module.ts
>  import { MatLegacyPaginatorModule as MatPaginatorModule } from '@angular/material/legacy-paginator';
Мы в этой задаче активно используем пагинатор, сможем тут тоже от Legacy избавиться? Или там сильно сложно?

2023-10-04 02:50 UTC, lirik90 commented on src/web/src/app/space/space-request-sent/component.html
> +<p>Запрос на присоединение к пространству '{{space}}' отправлен.</p>
Там в компоненте написано get('id'), а получается не id а name. А name в урле не хорошо передавать.)

2023-10-04 02:50 UTC, lirik90 commented on src/web/src/app/app.component.html
> +		<a [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST" ><span class="badge">* </span>Пространства</a>
Очень круто! Спасибо!

2023-10-04 02:53 UTC, lirik90 commented on src/web/src/app/app.component.html
> +      <button mat-button (click)=select.open()>
Супер! Выглядит здорово!)

2023-10-04 03:05 UTC, lirik90 commented
1. Заголовки странице не отображаются на вкладке браузера.
2. Помеченные кнопки не работают.
![image](https://github.com/svetit-io/svetit/assets/3821904/2f7ac854-d05b-42e3-a556-b82774c6f97f)

2023-10-04 03:42 UTC, lirik90 requested changes

2023-10-04 03:42 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +      placeholder="Введите название пространства"
Нужно использовать i18n-placeholder как например в [src/app/schemes/list/list.component.html:3](https://github.com/svetit-io/svetit/blob/e005001d9976156b222806274fd7386f750531b6/src/web/src/app/schemes/list/list.component.html#L3)

2023-10-04 04:24 UTC, prt0117 commented on src/web/src/app/app.component.html
> +	  <mat-icon *ngIf="!activeBadge" class="app-toolbar__user-icon">person</mat-icon>
Готово.

2023-10-04 04:27 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<a *ngIf="!activeBadge" [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST">Пространства</a>
Готово.

2023-10-04 04:28 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +	activeBadge: boolean = false;
Готово.

2023-10-04 04:30 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +		this.activeBadge = this.isSpacesBadge();
Готово.

2023-10-04 04:32 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator  *ngIf="spaces.length > 7" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></mat-paginator>
Готово.

2023-10-04 04:32 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator *ngIf="spacerefs.length > 7" class="width-and-clear" [length]="spacerefs.length" [pageSize]="refsPageSize" (page)="pageEvent = getPaginatorRefs($event)"></mat-paginator>
Готово.

2023-10-04 04:32 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator  *ngIf="spaceinvites.length > 7" class="spaces-invites-wrap" [length]="spaceinvites.length" [pageSize]="invitesPageSize" (page)="pageEvent = getPaginatorInvites($event)"></mat-paginat
Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace.name]);
Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request/' + this.selectedSpace.name]);
Дубль. Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +		this.activeBadge = this.isSpacesBadge();
Дубль. Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +	activeBadge: boolean = false;
Дубль. Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/app.component.html
> +		<a *ngIf="!activeBadge" [class.inactiveLink]="!initialized" routerLink="/space/list" i18n="@@SPACES.LIST">Пространства</a>
Дубль. Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/app.component.html
> +	  <mat-icon *ngIf="!activeBadge" class="app-toolbar__user-icon">person</mat-icon>
Дубль. Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator *ngIf="invites.length > 7" class="width-and-clear" [length]="invites.length" [pageSize]="invitesPageSize" (page)="pageEvent = getPaginatorInvites($event)"></mat-paginator>
Дубль. Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator *ngIf="refs.length > 7" class="width-and-clear" [length]="refs.length" [pageSize]="refsPageSize" (page)="pageEvent = getPaginatorRefs($event)"></mat-paginator>
Готово.

2023-10-04 04:45 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator *ngIf="users.length > 7" class="width-and-clear" [length]="users.length" [pageSize]="usersPageSize" (page)="pageEvent = getPaginatorUsers($event)"></mat-paginator>
Дубль. Готово.

2023-10-04 04:48 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +		<div class="left-float left-padding">vasya112@example.com</div>
Да, забыл вынести в массив. Готово.

2023-10-04 05:11 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +					<option value="guest">guest</option>
Готово.

2023-10-04 05:16 UTC, prt0117 commented on src/web/src/app/material.module.ts
>  import { MatLegacyPaginatorModule as MatPaginatorModule } from '@angular/material/legacy-paginator';
Ты выделил модуль не пагинатора, а инпута. Его тоже нужно обновить до не легаси состояния? Сам MatPaginatorModule получилось обновить до не легаси.

2023-10-04 05:22 UTC, prt0117 commented
> 1. Заголовки страниц не отображаются на вкладке браузера.
> 

Их нужно тянуть из файлов с локалями, как я понимаю? То есть файлы эти нужно сгенерировать сначала, если не ошибаюсь.

>     2. Помеченные кнопки не работают.
>        ![image](https://user-images.githubusercontent.com/3821904/272450193-2f7ac854-d05b-42e3-a556-b82774c6f97f.png)

А что должны делать данные кнопки?

1) копировать ссылку в буфер обмена?
2) кнопка удаления ссылки? должна удалять запись (строку целиком)?
3) кнопка добавления пользователя? как она должна работать?
4) кнопка добавления ссылки? как она должна работать?
5) кнопка удаления пространства? как она должна работать?

2023-10-04 05:39 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +      placeholder="Введите название пространства"
Готово.

2023-10-04 06:29 UTC, lirik90 commented
> Их нужно тянуть из файлов с локалями, как я понимаю? То есть файлы эти нужно сгенерировать сначала, если не ошибаюсь.

Нужно просто внести текст к ключам заголовков в файлы src/assets/i18n/*.json

2023-10-04 06:36 UTC, lirik90 commented
> А что должны делать данные кнопки?
> 
> 1. копировать ссылку в буфер обмена?
> 2. кнопка удаления ссылки? должна удалять запись (строку целиком) и элемент из массива?
> 3. кнопка добавления пользователя? как она должна работать? какая форма и где она должна открываться?
> 4. кнопка добавления ссылки? как она должна работать? какая форма и где должна открываться?
> 5. кнопка удаления пространства? как она должна работать? просто пока удалять строку целиком и элемент из массива?

1. Да
2. Да
3. 4. В задаче написано так: "сли нажать на кнопки добавления, то появится новая редактируемая запись в соответствующем списке выше." Т.е. в самом верху списка появляется запись в которой в случае с добавлением пользователя, редактируется имя пользователя и роль.  А в случае ссылки редактируется имя ссылки, и дата истечения срока действия. В такой строке кроме кнопки удалить, должна быть ещё и кнопка с галочкой для сохранения.
5. Да

2023-10-04 06:55 UTC, prt0117 commented
> Нужно просто внести текст к ключам заголовков в файлы src/assets/i18n/*.json

Внёс, но это не помогло. Также смотрю, что на других страницах title тоже не устанавливается. Дефолтный Device Access отображается везде.

И разве строки эти тянутся не из src/web/src/locale/?

2023-10-05 10:19 UTC, prt0117 commented
> > А что должны делать данные кнопки?
> > 
> > 1. копировать ссылку в буфер обмена?
> > 2. кнопка удаления ссылки? должна удалять запись (строку целиком) и элемент из массива?
> > 3. кнопка добавления пользователя? как она должна работать? какая форма и где она должна открываться?
> > 4. кнопка добавления ссылки? как она должна работать? какая форма и где должна открываться?
> > 5. кнопка удаления пространства? как она должна работать? просто пока удалять строку целиком и элемент из массива?
> 
>     1. Да
> 
>     2. Да
> 
>     3. 4. В задаче написано так: "сли нажать на кнопки добавления, то появится новая редактируемая запись в соответствующем списке выше." Т.е. в самом верху списка появляется запись в которой в случае с добавлением пользователя, редактируется имя пользователя и роль.  А в случае ссылки редактируется имя ссылки, и дата истечения срока действия. В такой строке кроме кнопки удалить, должна быть ещё и кнопка с галочкой для сохранения.
> 
>     4. Да

Реализовал кнопки удаления и копирования на страницах Пространства и Пространство. 

Кнопки инвайта пользователей и добавления ссылок реализовал на странице Пространства.

Вопрос:
1) нужно ли сделать формы инвайта и добавления ссылок на странице Пространство (которые будут открываться по кнопкам "+" в заголовках блоков "Приглашения" и "Ссылки" на странице Пространство)?

2023-10-06 03:10 UTC, lirik90 requested changes

2023-10-06 03:10 UTC, lirik90 commented on src/web/src/app/space/model.ts
> +}
Это та же модель что и Space. Нужно старую удали, а эту переименовать в Space.
```suggestion
export interface Space {
	id: string;
	name: string;
	key: string;
	requestsAllowed: boolean;
	createdAt: Date;
}
```

2023-10-06 03:53 UTC, lirik90 requested changes

2023-10-06 03:53 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		document.body.removeChild(copyToClipboard);
https://material.angular.io/cdk/clipboard/overview

2023-10-06 03:53 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		this.invites = [...this.invites];
А такое для чего?)

2023-10-06 04:07 UTC, lirik90 requested changes

2023-10-06 04:07 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		}
```suggestion
		return space?.name;
```

2023-10-06 05:16 UTC, prt0117 commented on src/web/src/app/space/model.ts
> +}
Готово.

2023-10-06 05:17 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.invites = [...this.invites];
Чтобы инвайты перерисовались после обновления массива с ними?:) Но раз у нас пагинатор.firstPage() и getInvites() вызываются, то, может, и лишнее - проверю.

2023-10-06 05:23 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.invites = [...this.invites];
Проверил, убрал)

2023-10-06 05:37 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		}
Поправил.

2023-10-06 05:42 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		document.body.removeChild(copyToClipboard);
А в нашем 15-ом angular material https://v15.material.angular.io/components/categories нету этого модуля, по твоей ссылке 16-ый angular material.

2023-10-06 05:58 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		document.body.removeChild(copyToClipboard);
Давай обновимся.)

2023-10-06 06:05 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		this.invites = [...this.invites];
Пагинатор не может отслеживать обновления массива. Т.е. никакой магии не происходит когда ты массив перезаписываешь самим сабой. Там какая то событийная модель и вся магия отрисовки обновлённых значений, на сколько я понял, в ней. Т.е. как я понял компонент слушает события которые ему доступны (видимо мышь, клавиатура и т.д.) и если событие наступило, то проверяются все значения. Если же нам хочется обновить значение когда происходит событие которое недоступно компоненту, то мы должны использовать ChangeDetector как [тут](https://github.com/svetit-io/svetit/blob/e005001d9976156b222806274fd7386f750531b6/src/web/src/app/app.component.ts#L138) например.

Это не точная информация, а то как я понял работу ангуларовской магии.

2023-10-06 06:23 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		document.body.removeChild(copyToClipboard);
> Давай обновимся.)

Давай) А как это сделать?

Я бы почитал сначала migration guide с версии 15 на 16, такой должен быть официальный.

2023-10-06 06:25 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.invites = [...this.invites];
> Пагинатор не может отслеживать обновления массива. Т.е. никакой магии не происходит когда ты массив перезаписываешь самим сабой. Там какая то событийная модель и вся магия отрисовки обновлённых значений, на сколько я понял, в ней. Т.е. как я понял компонент слушает события которые ему доступны (видимо мышь, клавиатура и т.д.) и если событие наступило, то проверяются все значения. Если же нам хочется обновить значение когда происходит событие которое недоступно компоненту, то мы должны использовать ChangeDetector как [тут](https://github.com/svetit-io/svetit/blob/e005001d9976156b222806274fd7386f750531b6/src/web/src/app/app.component.ts#L138) например.
> 
> Это не точная информация, а то как я понял работу ангуларовской магии.

Понял. Ну, вроде, работает и в текущем виде (после убирания перезаписи массива самим собой).

2023-10-06 06:27 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		document.body.removeChild(copyToClipboard);
https://update.angular.io/?l=3&v=15.0-16.0

2023-10-06 06:32 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		document.body.removeChild(copyToClipboard);
Хм, раньше эта страница выдавала и сами команды которые нужно запускать, а теперь почему то нет. (( Но скорее всего там что-то простое вроде npm i @angular@16

2023-10-09 02:47 UTC, lirik90 requested changes

2023-10-09 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	];
Вынеси пожалуйста получение объектов в файл service.ts в будущем он будет похож на [такое](https://github.com/svetit-io/svetit/blob/develop/src/web/src/app/schemes/schemes.service.ts).

Моки можно перенести на бэк или если оставить пока во фронте, то в service.ts будут функции примерно такого содержания:
```typescript
getSpaceList(limit: number, page: number): Observable<PaginatorApi<Space>> {
	let spaces: Space[] = [...];
	const res: PaginatorApi<Space> = {
		count: spaces.length,
		results: spaces.slice(limit * page, limit * page + limit),
	};
	return of(res);
}
```

2023-10-09 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +    spacesHighValue: number = 7;
1. Замени пожалуйста пробелы на табы
2. Сделай пожалуйста pageSizeOptions = [7, 15, 30, 100]
3. Сделай пожалуйста чтобы pageSize загружался из и сохранялся в localStorage
4. LowValue и HighValue - кажется проще рассчитывать на лету.
5. PageIndex есть в event в paginatorHandler

2023-10-09 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator #linksPaginator *ngIf="links.length > linksPageSize" class="width-and-clear" [length]="links.length" [pageSize]="linksPageSize" (page)="pageEvent = getPaginatorLinks($event)"></mat-pa
А для чего тут pageEvent = ?

2023-10-09 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator #spacesPaginator *ngIf="spaces.length > spacesPageSize" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></
length - общее кол-во придёт с бэка. И поскольку ты используешь ViewChild, его наверное сразу туда можно будет установить.

Ниже вариант getSpaces

```suggestion
	<mat-paginator #spacesPaginator class="width-and-clear"
	*ngIf="spaces.length > spacesPageSize"
	[pageSize]="spacesPageSize"
	(page)="getSpaces($event.pageIndex, $event.pageSize)"></mat-paginator> 
```

2023-10-09 02:47 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	}
Тут space это SpaceService
Пример getInvitationList в комментарии выше, только там getSpaceList

```suggestion
	getInvites(limit: number, page: number) {
		this.space.getInvitationList(limit, page)
			.subscribe(res => {
				this.invitesPaginator.length = res.count;
				this.invites = res.results;
			});
	}
```

2023-10-09 10:47 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	];
Готово.

2023-10-09 10:48 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +    spacesHighValue: number = 7;
Сегодня не успел, планирую завтра утром к этому приступить.

2023-10-09 10:48 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator #linksPaginator *ngIf="links.length > linksPageSize" class="width-and-clear" [length]="links.length" [pageSize]="linksPageSize" (page)="pageEvent = getPaginatorLinks($event)"></mat-pa
Удалил везде. Это был кусок кода с SO^^

2023-10-09 10:49 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator #spacesPaginator *ngIf="spaces.length > spacesPageSize" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></
Сходу length в пагинотор на стороне компонента поместить не получилось. Вернусь к этому завтра по плану.

2023-10-09 10:51 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	}
Сделал. Только, как писал выше, в пагинатор на стороне компонента length не получилось передать, поэтому стал использовать переменную. Планирую вернуться к этому (к length) завтра - разобраться.

2023-10-10 01:52 UTC, lirik90 requested changes

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/auth/service.ts
> +
Перенеси в src/app/user/service.ts

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/auth/service.ts
>  	}
Это должно быть в src/app/user/service.ts
```suggestion
	getById(userId: string): Observable<User> {
		const user = this._mockDataForSpaceDetailPage.find(u => u.userId === userId);
		return of(user);
	}
```

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +</div>
Замени пожалуйста пробелы на табы.

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			takeUntil(this.ngUnsubscribe)
А для чего такая штука?

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		this.space.getSpaceListAll()
А если пространств миллион?) Методов вроде getSpaceListAll быть не должно.

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +    	copyToClipboard.value = this.document.location.origin + this.linksURL + link.id;
Замени пожалуйста пробелы на табы

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	invitesPageIndex: number = 0;
Кажется invitesPageIndex не нужен.

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		if (this.invitesPaginator) {
А в каких случаях invitesPaginator может вернуть false?

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +			this.invitesPaginator.firstPage();
А разве firstPage не вызовет getInvites ?

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		this.getInvites(this.invitesPageSize, this.invitesPageIndex);
Возможно тут нужно проверять есть ли this.invitesPaginator и на первой ли он сейчас странице. Если не на первой, то наверное достаточно вызова this.invitesPaginator.firstPage();, а если на первой то тогда уже обновляем список сами вызовом getInvites.

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	}
Нужно подождать завершения delSpaceById. В промежутке пока ждём нужно заблокировать другие кнопки на странице и показывать колесо прогресса. Обновляем список пространств только после того как delSpaceById вернул положительный результат.

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/model.ts
> +export interface SpaceUserAddinitionalInfo{
Уже есть класс User

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +
Лишняя пустая строка тут и в конце функции.

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	isSpaceExists(key: string) {
Space - есть в названии Service (SpaceService). Давай просто isExists

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	createNewSpace(name: string, key: string, requestsAllowed: boolean) {
Space - есть в названии Service

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	createNewLink(spaceId: string, creatorId: string, name: string, expiredAt: Date) {
createOld выглядело бы странно.) Давай просто createLink

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
Эти методы асинхронные, по тому как дёргают бэк для складывания записей в БД. Давай добавим небольшую задержку чтобы нагляднее этот момент обработать на фронте.
```suggestion
	createNewInvite(spaceId: string, userId: string, role: string, creatorId: string): Observable<boolean> {
		this.invites.push({
			id: Math.random(),
			spaceId: spaceId,
			userId: userId,
			role: role,
			creatorId: creatorId,
			createdAt: new Date(),
		});
		return of(true)
			.pipe(delay(2000));
	}
```

2023-10-10 01:52 UTC, lirik90 commented on src/web/src/app/user.ts
> +	//previous: string;
Комментарии тут лишние. Если эти свойства не нужны, просто удаляем их.

2023-10-10 05:32 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +    spacesHighValue: number = 7;
1. Готово.
2. Готово.
3. Готово.
4. Вообще избавился от этих переменных.
5. Пока не вижу, как от него избавиться. Пагинатор в момент ngOnInit не существует ещё, когда мы первый раз данные получаем. Можно попробовать использовать ngAfterViewInit, но в этом случае, как мне кажется, может что-то на экране происходить не очень приятное - какие-то визуально отображаемые рендеренги подгружаемых данных и т.д., может потребоваться какой-то лоадер и т.п. Если это нам нужно, то говори, буду разбираться

2023-10-10 05:46 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator #spacesPaginator *ngIf="spaces.length > spacesPageSize" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></
Пробовал ещё раз обращаться к пагинатору из компонента в ngOnInit и в ngAfterViewInit - в обеих случаях пагинатор ещё не существует. 

Что касается общего количества, то ставлю пока через переменную, заполняемую в момент получения данных из ангуларовского сервиса.

2023-10-10 05:48 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	}
Ответил выше про недоступность пагинатора сразу после инициализации. Примерно советуют ещё вот такое https://stackoverflow.com/a/59445975 , но мне не до конца понятно, какие это может эффекты принести, поэтому не использую пока. Но если точно нужно нам это, то скажи, займусь.

2023-10-10 05:53 UTC, prt0117 commented on src/web/src/app/auth/service.ts
> +
Готово.

2023-10-10 06:52 UTC, prt0117 commented on src/web/src/app/auth/service.ts
>  	}
Готово.

2023-10-10 06:55 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +</div>
Готово.

2023-10-10 08:10 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			takeUntil(this.ngUnsubscribe)
Как минимум, для того, чтобы отключить кнопку "Отправить", если пользователь чистит содержимое инпута автокомплита) А вообще - это копипаст с SO, так как все эти асинхронные штуки в тот момент были мне не очень ясны. Ну какая-то задержка, как видно по коду, плюс отвалятся все лишние запросы, которые были во время задержки, и выполнится самый свежий запрос. Что-то такое. Переписать? Или могу у ChatGPT спросить, что код делает:D

2023-10-10 08:15 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			takeUntil(this.ngUnsubscribe)
ChatGPT 3.5:

Предоставленный код, по-видимому, написан на TypeScript и использует RxJS, которая представляет собой библиотеку для реактивного программирования на JavaScript/ TypeScript. Позвольте мне пошагово описать, что делает этот код:

this.controlAutocomplete.valueChanges: Эта часть, вероятно, представляет наблюдаемый объект. valueChanges - это распространенный шаблон в Angular для создания наблюдаемого объекта, который генерирует события при изменении значения элемента ввода (например, текстового ввода).

.pipe(...): Оператор pipe используется для объединения ряда операторов RxJS вместе для манипулирования данными, передаваемыми наблюдаемым объектом.

debounceTime(500): Этот оператор задерживает выбросы из наблюдаемого объекта на 500 миллисекунд. Это означает, что при многократном быстром изменении входного значения он будет ждать 500 миллисекунд бездействия, прежде чем выдать последнее значение.

distinctUntilChanged(): Этот оператор гарантирует, что наблюдаемый объект выдает только отличные (отличные от предыдущих) значения. Он отфильтровывает последовательные повторяющиеся значения.

takeUntil(this.ngUnsubscribe): Этот оператор приведет к завершению работы наблюдаемого объекта (прекращению выдачи значений), когда наблюдаемый объект ngUnsubscribe выдаст значение. Обычно это используется для управления жизненным циклом наблюдаемых объектов и отмены подписки на них, когда они больше не нужны, чтобы предотвратить утечки памяти.

.subscribe(selected => { ... }): Здесь код подписывается на наблюдаемый объект, созданный на шаге 1. Он предоставляет функцию обратного вызова, которая будет выполняться всякий раз, когда наблюдаемый объект выдает новое значение.
Внутри обратного вызова он проверяет, является ли значение selected ложным (например, null или undefined). Если выбрано значение falsy, оно устанавливает для этого.selectedSpace значение null. Это говорит о том, что этот код, скорее всего, используется для очистки выделенного пространства при изменении входного значения, но в данный момент ни один параметр не выбран (если выбран неверно).

Таким образом, этот код настраивает Observable для отслеживания изменений значения входного элемента this.controlAutocomplete. Когда обнаруживается изменение, он применяет время отмены, гарантирует, что выдаются только различные значения, и подписывается на наблюдаемое. Внутри обратного вызова подписки он очищает свойство this.selectedSpace до значения null, если ни один параметр не выбран. Использование takeUntil предполагает, что этот код также управляет жизненным циклом подписки, чтобы предотвратить утечки памяти в компоненте Angular.

2023-10-10 08:18 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.space.getSpaceListAll()
Дада, это я осознанно написал (понимая, что так нельзя)). Так как начал переписывать автокомплит на использование сервиса Space, держа в уме, что это будут реальные http запросы (а не работа с массивом, как на фронте было для теста изначально), но сходу не получилось, и я отложил. Сейчас этим и займусь.

2023-10-10 08:51 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.space.getSpaceListAll()
Пока всё равно не получилось. Вернусь к этому чуть позже, как с другими комментами разберусь.

2023-10-10 08:51 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +    	copyToClipboard.value = this.document.location.origin + this.linksURL + link.id;
Готово.

2023-10-10 08:54 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	invitesPageIndex: number = 0;
А что вместо него? PageIndex из PageEvent? Если да, то я выше уже писал, что пагинатор, который, как я понимаю, инициирует PageEvent не доступен в момент инициализации компонента. Поэтому приходится вызывать getInvites, передавая туда в том числе и invitesPageIndex. 

Это справедливо и для других ...PageIndex (links..., spaces..., users...).

Или я не так понял?

2023-10-10 08:56 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		if (this.invitesPaginator) {
Раньше его не было на странице, когда была только 1 страница результатов без пагинатора (я его скрывал через ngIf специально). Теперь пагинатор всегда на странице, так что это условие можно убрать.

2023-10-10 09:32 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		if (this.invitesPaginator) {
Убрал проверку условия и последующий вызов методов getInvites (...Links, ...Users, ...Spaces и так далее).

2023-10-10 09:42 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +			this.invitesPaginator.firstPage();
Теперь вызовет, так как пагинатор у нас теперь всегда отображается. Раньше его не было на странице (я его скрывал через ngIf), когда все данные помещались на одной странице.

Убрал лишние вызовы getInvites, ...Links, ...Spaces, ...Users и так далее.

2023-10-10 09:45 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		this.getInvites(this.invitesPageSize, this.invitesPageIndex);
Сделал пагинатор всегда отображающимся, так как нужно управлять уметь PageSize (чтобы не включить большой PageSize, например, и не зависнуть на нём без возможности поставить PageSize поменьше). В результате условие проверки на наличие пагинатора - не требуется. 

Так же, как и последующий вызов getInvites(... Links, ...Spaces и так далее) не требуется более - всё решается через firstPage().

2023-10-10 09:45 UTC, prt0117 commented on src/web/src/app/space/model.ts
> +export interface SpaceUserAddinitionalInfo{
Удалил SpaceUserAddinitionalInfo, использую только класс User теперь.

2023-10-10 09:48 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +
Поправил. Иногда так оборачивал специально, когда хотелось более комплексную или сложную логику дополнительно отделить\выделить\огранить.

2023-10-10 09:50 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	isSpaceExists(key: string) {
Готово.

2023-10-10 09:51 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	createNewSpace(name: string, key: string, requestsAllowed: boolean) {
Готово.

2023-10-10 09:52 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	createNewLink(spaceId: string, creatorId: string, name: string, expiredAt: Date) {
Готово.

2023-10-10 09:55 UTC, prt0117 commented on src/web/src/app/user.ts
> +	//previous: string;
Готово.

2023-10-10 11:11 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.space.getSpaceListAll()
Победил с помощью ChatGPT и SO)

2023-10-11 00:39 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +    spacesHighValue: number = 7;
5. В момент ngOnInit ты на первой странице, т.е. значение PageIndex = 0, для этого отдельный член класса не нужен.

2023-10-11 01:31 UTC, lirik90 requested changes

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +		i18n-placeholder="@@SPACES.ADD.JOIN.INPUT_PLACEHOLDER"
Почему то i18n-placeholder не на том же уровне с другими атрибутами.

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/space-request-sent/component.ts
> +import { Component, OnInit } from '@angular/core';
Переименуй пожалуйста папку space-request-sent в request-sent , тут space есть в названии папки выше, т.е. все все компоненты в этой папки по умолчанию space-...

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +		<mat-autocomplete #auto="matAutocomplete" (optionSelected)="onSelectOption($event.option)"	[displayWith]="displaySpaceName">
Тут лишний таб между атрибутами

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +	filteredSpaces: Observable<Space[]>;
Давай оставим spaces и уберём filteredSpaces

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			))
Давай стараться использовать имена максимально короткие, но достаточные чтобы можно было понять для чего это.
```suggestion
			switchMap(value => this.space.getList(10, 0, value || '').pipe(
				map(res => res.results)
			))
```

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
```suggestion
	getList(limit: number, page: number, name: string = ''): Observable<PaginatorApi<Space>> {
		const grouped = this.spaces.filter(space => space.name.includes(name));
		const res: PaginatorApi<Space> = {
			count: grouped.length,
			results: grouped.slice(limit * page, limit * page + limit),
		};
		return of(res);
	}
```

2023-10-11 01:31 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	getInvitesList(limit: number, page: number): Observable<PaginatorApi<SpaceInvitation>> {
Давай везде использовать одинаковые имена.
В описании задачи в названии таблицы используется имя invitation, у меня с английским не очень, т.к. используя переводчик перевожу это как "приглашение". Тот же переводчик переводит "Invites"->"Приглашает". А "Invite"->"Приглашать". 
Если ты считаешь что Invite более удачное слово, то давай тогда везде использовать его, т.е. замени в самой задаче и везде в других местах, включая бэк, где используется слово Invitation.

Ещё момент что слово List тут подразумевает множественное число, т.е. букву s добавлять не нужно getInviteList

2023-10-11 01:33 UTC, lirik90 requested changes

2023-10-11 01:33 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
Зачем отдельная функция для этого?

2023-10-11 01:33 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
Space уже есть в названии службы

2023-10-11 01:38 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +	<mat-paginator #spacesPaginator *ngIf="spaces.length > spacesPageSize" class="width-and-clear" [length]="spaces.length" [pageSize]="spacesPageSize" (page)="pageEvent = getPaginatorSpaces($event)"></
Видимо тут лучше через переменную как ты сделал. Проверил почему не сработало без неё, это потому что у нас весь список вместе с пагинатором скрытый когда список пуст. А отображается только после того как список запрошен уже в первый раз. Если бы мы его не скрывали, то тогда бы всё получилось, по тому что мы обращаемся к пагинатору не в ngOnInit, а после события получения списка с сервера, т.е. пока идёт запрос к серверу, пагинатор уже инициализируется.

2023-10-11 01:40 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			takeUntil(this.ngUnsubscribe)
Разве в таком случае ты не должен установить какое то значение в ngUnsubscribe ?

2023-10-11 01:47 UTC, lirik90 requested changes

2023-10-11 01:47 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		let contains = this.space.isExists(data.key);
1. Нужно провалидировать и подсветить красным поле на этапе заполнения поля пользователем, а не тогда когда он уже нажал кнопку.
2. Когда нажал кнопку, такой проверки не нужно, бэк сам проверит.
3. В SpaceService все методы которые ты добавляешь (моки) должны быть асинхронными, по тому что это имитация вызова бэка.

2023-10-11 09:50 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +			this.invitesPaginator.firstPage();
Вернул везде вызовы getInvites, ...Links, ...Spaces, ...Users - без них не работает корректно.

2023-10-11 09:50 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	}
Готово.

2023-10-11 09:50 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
Готово.

2023-10-11 10:17 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +    spacesHighValue: number = 7;
Поскольку у вернул обратно вызовы методов getInvites и аналогичных в функции, срабатывающие при удалении или добавлении элементов, то тут нужно подумать, а можно ли как-то получать PageIndex из pageEvent в этих функциях. Я пока не знаю, возможно ли это. Предлагаю обсудить на созвоне.

2023-10-11 10:22 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			takeUntil(this.ngUnsubscribe)
Ну как я это понимаю, эта штука нужна, чтобы принудительно отписать (что у нас не используется). Можем убрать и посмотреть, что получится)

2023-10-11 10:23 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		if (this.invitesPaginator) {
Вернул везде вызовы getInvites, ...Links, ...Spaces, ...Users - без них не работает корректно.

2023-10-11 10:35 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +		i18n-placeholder="@@SPACES.ADD.JOIN.INPUT_PLACEHOLDER"
Готово.

2023-10-11 10:36 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		this.getInvites(this.invitesPageSize, this.invitesPageIndex);
Вернул везде вызовы getInvites, ...Links, ...Spaces, ...Users - без них не работает корректно.

2023-10-11 10:38 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	invitesPageIndex: number = 0;
Точно не нужен, дошло, он всегда 0 сейчас во всех местах, где используется.

2023-10-11 10:42 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +    spacesHighValue: number = 7;
Точно, удалил.

2023-10-11 10:49 UTC, prt0117 commented on src/web/src/app/space/space-request-sent/component.ts
> +import { Component, OnInit } from '@angular/core';
Готово.

2023-10-11 10:50 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +		<mat-autocomplete #auto="matAutocomplete" (optionSelected)="onSelectOption($event.option)"	[displayWith]="displaySpaceName">
Убрал (заменил на пробел).

2023-10-12 04:05 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +	filteredSpaces: Observable<Space[]>;
Готово.

2023-10-12 04:13 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
Готово.

2023-10-12 04:13 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			))
Готово.

2023-10-12 04:46 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	getInvitesList(limit: number, page: number): Observable<PaginatorApi<SpaceInvitation>> {
Переименовал везде invite в invitation. Множественное число перед List везде убрал в названиях методов.

2023-10-12 04:53 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
Убрал отдельную функцию, переписал на использование соседнего метода getSpaceById(). 

Но возникла дополнительная проблема - getSpaceById вызывается множество раз на странице Space List, чтобы поставить имя пространства перед строками с приглашениями и ссылками. Из-за этого всё повисает, так как каждый вызов эмитирует задержку в 2 сек. Итого на странице может быть более 10 вызовов, а это 20 сек задержки. Нужно как-то нам это обойти, получая не только id пространств при запросе списка приглашений и ссылок, но и названия пространств сразу пачкой. Надо подумать.

2023-10-12 04:56 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
Готово.

2023-10-12 06:10 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		let contains = this.space.isExists(data.key);
Готово.

2023-10-13 03:12 UTC, lirik90 requested changes

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/overlay/overlay.service.ts
> +
Лишняя пустая строка

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/progress-spinner/progress-spinner.component.ts
> +  @Input() value?: number;
Кажется эти свойства никак не используются. Наверное можно удалить.

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/progress-spinner/progress-spinner.component.ts
> +  }
Замени пожалуйста пробелы на табы.

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +<app-progress-spinner class="example-margin" [displayProgressSpinner]="displayProgressSpinner">
example-margin кажется никак не используется.

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +
Пустая строка.

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/overlay/overlay.service.ts
> +export class OverlayService {
Давай пожалуйста сделаем из этого класса обслуживатель для всех изменяющих запросов к серверу.
Т.е. нам нужно для всех запросов показывать спинер и если запрос упал с ошибкой, показывать ошибку. Показ ошибки сделаем в отдельной задаче, а спинер можем сделать сразу. Назови этот класс как то вроде RequestWatcherService, или придумай название получше если фантазии хватает, и сделай его чуть менее универсальным.
Т.е. у нас где то в AppComponent будет сам спинер (и блок с ошибкой в будущем), и при инициализации AppComponent вызовет этот класс установив в него ссылку на спинер. Этот компонент будет хранить ссылку и показывать компонент по мере необходимости.

Т.е. тут нам понадобятся функции вроде SetProgressSpiner и WatchFor

WatchFor может иметь примерно такой вид:
```typescript
WatchFor<T>(source$: Observable<T>) {
  source$.pipe(
      tap(() => this.hideSpinner()),
      catchError(err => {
        this.hideSpinner();
        this.showError(err.message);
        console.warn('catch', err);
        return throwError(err);
    }),
  )
}

2023-10-13 03:12 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +</app-progress-spinner>
Этот компонент понадобится нам всегда, лучше его засунуть в AppComponent

2023-10-13 03:58 UTC, lirik90 commented on src/web/src/app/overlay/overlay.service.ts
> +export class OverlayService {
Или по другому, чтобы можно было использовать как то так:
```typescript
this.space.create(...).pipe(
  this.requestWatcher.Watch,
).subscribe(...)
```
тогда функция Watch будет выглядеть как то так:
```typescript
Watch<T>(source$: Observable<T>): Observable<T> {
  this.showSpinner();
  return source$.pipe(
      tap(() => this.hideSpinner()),
      catchError(err => {
        this.hideSpinner();
        this.showError(err.message);
        console.warn('catch', err);
        return throwError(err);
      }),
  );
}
```

2023-10-13 04:04 UTC, prt0117 commented on src/web/src/app/overlay/overlay.service.ts
> +
Готово.

2023-10-13 04:06 UTC, prt0117 commented on src/web/src/app/progress-spinner/progress-spinner.component.ts
> +  @Input() value?: number;
Готово.

2023-10-13 04:07 UTC, prt0117 commented on src/web/src/app/progress-spinner/progress-spinner.component.ts
> +  }
Готово.

2023-10-13 04:08 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +<app-progress-spinner class="example-margin" [displayProgressSpinner]="displayProgressSpinner">
Готово.

2023-10-13 04:09 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +
Готово.

2023-10-13 04:30 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +</app-progress-spinner>
Готово.

2023-10-13 09:07 UTC, prt0117 commented on src/web/src/app/overlay/overlay.service.ts
> +export class OverlayService {
Готово.

2023-10-13 09:07 UTC, prt0117 commented
Поменял input на span для вывода названия пространства на странице Пространства в формах добавления приглашения и ссылки.

2023-10-13 09:20 UTC, prt0117 commented
Сделал селекты более material.

2023-10-13 09:21 UTC, prt0117 commented
Поменял css у прогресс спиннера, чтобы убрать белый квадрат на фоне.

2023-10-13 13:37 UTC, lirik90 requested changes

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +	@ViewChild('appSpinner') appSpinner: ElementRef;
Кажется тут это лишнее.

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/app.component.html
> +</app-progress-spinner>
Перенеси пожалуйста на одну строку. И якорь тут кажется не нужен.
```suggestion
<app-progress-spinner></app-progress-spinner>
```

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/app.module.ts
> +import { ProgressSpinnerComponent } from './progress-spinner/progress-spinner.component';
Перенеси пожалуйста папку с progress-spinner
```suggestion
import { ProgressSpinnerComponent } from './request-watcher/progress-spinner/component';
```

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/progress-spinner/progress-spinner.component.ts
> +	@Input() displayProgressSpinner: boolean;
Кажется эти свойства не используются.

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +	public displayProgressSpinner = false;
Кажется это свойство не используется.

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +	appSpinner: TemplateRef<any>;
Может переименуем просто в spinner?

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +	private progressSpinnerOverlayConfig: OverlayConfig;
Кажется хранить конфиг не нужно. Давай удалим это свойство.

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +	}
Функция очень маленькая и используется только в одном месте. Давай удалим её пожалуйста.

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +		this.overlayRef = this.createOverlay(this.progressSpinnerOverlayConfig);
Давай сократим.

```suggestion
		this.overlayRef = this.overlay.create({
			hasBackdrop: true,
			positionStrategy: this.positionGloballyCenter()
		});
```

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +	setProgressSpinner(appSpinner: TemplateRef<any>, vcRef: ViewContainerRef) {
Давай публичные методы называть с большой буквы.
```suggestion
	SetProgressSpinner(appSpinner: TemplateRef<any>, vcRef: ViewContainerRef) {
```

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +	}
Замени пожалуйста пробелы на табы.
И давай логирование перенесём в showError

```suggestion
	WatchFor<T>(source$: Observable<T>): Observable<T> {
		this.showSpinner();
		return source$.pipe(
			tap(v => this.hideSpinner()),
			catchError(err => {
				this.hideSpinner();
			  	this.showError(err.message);
			  	return throwError(err);
			})
		)
	}
```

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/request-watcher/service.ts
> +		alert(msg);
Думаю ошибки довольно часто могут появляться. Давай пока просто в консоль.
```suggestion
		console.warn('catch', msg);
```

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +export class SpaceKeyValidation implements AsyncValidator {
А такой валидатор где-то ещё будет использоваться? Может не нужно выносить его в отдельный файл?

2023-10-13 13:37 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +			);
Тут почти ничего не происходит, а столько отступов и новых строк. Давай пожалуйста сократим чуток. 
```suggestion
		return this.space.isExists(value)
			.pipe(map(res => res ? {keyExists: true} : null));
```

2023-10-15 19:56 UTC, lirik90 requested changes

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +	spaces: Observable<Space[]>;
В ангуларе видимо принято публичные Observable декларировать с долларом на конце.
Восклицательный знак указывает компилятору что эта переменная гарантированно не может быть null или undefined и позволяет убрать лишние проверки на null и undefined. Это было в [туториале](https://angular.io/tutorial/tour-of-heroes/toh-pt6#asyncpipe), давай тоже добавим пожалуйста.
```suggestion
	spaces$!: Observable<Space[]>;
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +				createdAt: option.value.createdAt
option.value.createdAt - кажется такого значения там нет. 
```suggestion
				createdAt: null
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +
Лишняя пустая строка.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		});
А для чего debounceTime в первом случае 300, а во втором 500? Как это работает? Что будет если объединить? Например вот так:
```suggestion
		this.spaces = this.controlAutocomplete.valueChanges.pipe(
			startWith(''),
			debounceTime(300), // Optional: debounce input changes to avoid excessive requests
			distinctUntilChanged(), // Optional: ensure distinct values before making requests
			switchMap(value => {
				if (!value)
					this.selectedSpace = null;

				return this.space.getList(10, 0, value || '').pipe(
					map(res => res.results)
				);
			})
		);
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		}
Само условие можно убрать для краткости, потому что перезапись keyWasChanged ни к чему плохому не приведёт.
```suggestion
		this.keyWasChanged = true;
```

Если считаешь что правильнее всё таки с условием, то можно убрать фигурные скобки, т.к. во всей функции есть только одно это условие и отсутствие фигурных скобок визуально ничего не ухудшит.
```suggestion
		if (!this.keyWasChanged)
			this.keyWasChanged = true;
```

Если фигурные скобки всётаки нужны, то нужно добавить пробел после круглых скобок.
```suggestion
		if (!this.keyWasChanged) {
			this.keyWasChanged = true;
		}
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +	};
Перенеси пожалуйста это поближе к функции _transliterate

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			).subscribe(res => {
Давай пожалуйста перенесём src => this.requestWatcher.WatchFor(src) в SpaceService.
В SpaceService::createNew оставил коммент.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			.pipe(delay(2000));
```suggestion
			.pipe(
				delay(2000),
				src => this.requestWatcher.WatchFor(src)
			);
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +			<div class="left-float left-padding"><button mat-icon-button type="submit" i18n=""><mat-icon>done</mat-icon></button></div>
i18n тут не нужен.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +						<mat-option value="guest" i18n="" selected>Гость</mat-option>
i18n тут не заполнен.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator #linksPaginator class="width-and-clear" [length]="linksTotal" [pageSize]="linksPageSize" [pageSizeOptions]="[7, 15, 30, 100]" (page)="getLinks($event.pageSize, $event.pageIndex); saveP
Давай пожалуйста savePageSizeToLocalStorage перенесём в getLinks

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	usersPageSize: number = 10;
Может сделаем под это общую структуру? Так будет проще сохранять.
```suggestion
	pageSize = {
		invitations: 7,
		links: 7,
		users: 10,
	};
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		this.usersPageSize = pageSize ? parseInt(pageSize) : 10;
```suggestion
		const pageSizeStr = localStorage.getItem('spaceDetailPageSize');
		const pageSize = JSON.parse(pageSizeStr);
		if (pageSize?.invitations && pageSize?.links && pageSize?.users)
			this.pageSize = pageSize;
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	currentUserId: string = "2";
currentUserId нужно использовать реальный.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	}
Лучше, как и в функциях ниже, перенести this.currentSpaceId внутрь getCurrentSpace
```suggestion
		this.getCurrentSpace();
		this.getInvitations(this.invitationsPageSize, 0);
		this.getLinks(this.linksPageSize, 0);
		this.getUsers(this.usersPageSize, 0);
	}

	getCurrentSpace() {
		this.space.getById(this.currentSpaceId)
			.subscribe(res => {
				this.currentSpace = res;
				this.currentSpaceLoaded = true;
			});
	}
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	}
```suggestion
	getInvitations(limit: number, page: number) {
		this.savePageSize("invitations", limit);
		this.space.getInvitationListForSpace(this.currentSpaceId, limit, page)
			.subscribe(res => {
				this.invitations = res.results;
				this.invitationsTotal = res.count;
			});
	}
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +}
Нужно проверить что изменение значения в this.pageSize не приводит к двойному запросу списков с сервера. Т.е. пагинатор может проверить что оригинальное значение изменилось и не сверив его со своим текущим, обновить страницу. 

Если такое происходит нужно будет дублировать this.pageSize и изменять дубль, а не оригинал.

```suggestion
	savePageSize(id: string, limit: number) {
		if (this.pageSize[id] == limit)
			return;
		
		this.pageSize[id] = limit;
		localStorage.setItem('spaceDetailPageSize', JSON.stringify(this.pageSize));
	}
}
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			//.pipe(delay(2000));
Везде нужна задержка чтобы видеть что асинхронные запросы обрабатываются корректно.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +</div>
А зачем отдельный div ? И зачем currentSpaceLoaded, можно же проверить сам объект?
```suggestion
<h1 *ngIf="currentSpace">{{currentSpace.name}}</h1>
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	currentSpaceLoaded = false;
Кажется это лишнее.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	}
В текущем виде ты не дожидаясь завершения удаления записи из базы, уже запрашиваешь список. Так тебе может вернуться список в котором удаляемая запись ещё есть.
```suggestion
	onInvitationDelBtn(invitation: SpaceInvitation){
		this.space.delInvitationById(invitation.id).pipe(
			src => this.requestWatcher.WatchFor(src)
		).subscribe(res => {
			this.invitationsPaginator.firstPage();
			this.getInvitations(this.invitationsPageSize, 0);
		});
	}
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		this.linksPaginator.firstPage();
Мне кажется что функция firstPage() уже приведёт к вызову getLinks если пагинатор находился не на первой странице. Проверь пожалуйста. И если это так, то тут нужно вызывать getLinks только если сейчас первая страница в пагинаторе.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/user/service.ts
> +		return of(user);
добавь delay

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/user/service.ts
> +		return of(user);
добавь delay

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +		<div class="left-float left-padding">{{getUserEmailById(user.userId)}}</div>
А для чего тут matNativeControl?

Давай пожалуйста сделаем полную инфу о пользователе во всплывающей подсказке.


```suggestion
		<div class="left-float"
			[matTooltip]="user.login + ' ' + user.email">{{user.displayName}}</div>
		<div class="left-float left-padding">
			<mat-form-field>
				<mat-select [(ngModel)]="user.role">
					<mat-option value="admin" i18n="@@SPACES.DETAIL.ADMINROLE">Администратор</mat-option>
					<mat-option value="user" i18n="@@SPACES.DETAIL.USERROLE">Пользователь</mat-option>
					<mat-option value="guest" i18n="@@SPACES.DETAIL.GUESTROLE">Гость</mat-option>
				</mat-select>
			</mat-form-field>
		</div>
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +
Мы можем расширить тип который приходит с сервера, дополнительными значениями которые нам нужны в этом компоненте.

```suggestion
import { RequestWatcherService } from '../../request-watcher/service';

type SpaceUserFull = SpaceUser & {
	displayName: string,
	login: string,
	email: string,
};
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	users: SpaceUser[] = [];
```suggestion
	users: SpaceUserFull[] = [];
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	}
1. this.user.getById - асинхронная операция, это значит что значение res ты получишь сильно позже чем произойдёт выход из этой функции, т.е. переменная name всегда будет пустой и функция всегда будет возвращать пустой результат.
2. Эта функция вызывается при каждой итерации цикла. Т.е. запросов на сервер полетит очень много. Вместо этого мы должны после получения списка пользователей в пространстве, определить уникальные userId и сразу заполнить поля в расширенной структуре, запросив инфу об уникальных пользователях.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +					<mat-hint i18n="">Логин пользователя</mat-hint>
i18n не заполнено.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +					<input matInput type="text" formControlName="username" required />
У этого поля должен быть автокомплит, по типу как в space/add/component

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.html
> +		<form [formGroup]="invitationForm" [hidden]="isInvitationFormHidden" (ngSubmit)="onSubmitInvitation(invitationForm)">
Немного странно что мы в шаблоне берём объект из компонента и передаём обратно в компонент.
```suggestion
		<form [formGroup]="invitationForm" [hidden]="isInvitationFormHidden" (ngSubmit)="onSubmitInvitation()">
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +				this.usersTotal = res.count;
Тут нужно запросить инфу об уникальных пользователях из полученного списка. см. коммент к функции getUserNameById

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/list/component.html
> +			<form [formGroup]="invitationForm" [hidden]="isInvitationFormHidden" (ngSubmit)="onSubmitInvitation(invitationForm)">
hidden тут выглядит как лишний трюк. Давай лучше совсем спрячем этот div.
```suggestion
		<div class="float-row-with-padding" *ngIf="isInvitationForm">
			<form [formGroup]="invitationForm" (ngSubmit)="onSubmitInvitation()">
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	}
Вместо этой функции нужно заполнять дополнительные поля после получения списка, получив отдельно инфу об уникальных пространствах. Сами пространства лучше закэшировать в массиве и сначала заполнять инфу из массива, а если в нём не оказалось нужного space то дополнять массив (например пустым объектом в котором заполнен только Id, чтобы не запрашивать инфу об одном и том же space несколько раз), а затем получать инфу об этих space и заполнять доп. свойства. 

Давай пожалуйста сделаем такой же кэш и для списка пользователей, в том числе и в space/detail/component

На этих страницах пользователь может часто щёлкать пагинатор, и было бы излишеством при каждом щелчке запрашивать инфу о пользователях и пространствах которые уже известны. К тому же и та и другая инфа редко обновляема на сервере.

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/model.ts
> +// need to clarify
Что имеется ввиду?

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/request-sent/component.ts
> +	}
А эта пустая функция обязательна? Без неё не работает? (

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			pipe(delay(2000));
А для чего такая проверка на -1? В каких ситуациях может удаляться элемент которого нет?
Давай добавим возврат ошибки и во всех таких функциях перенесём удаление после таймаута, чтобы отловить возможные проблемы с асинхронностью.
```suggestion
		return of(true).pipe(
			delay(2000),
			switchMap(val => {
				const index = this.invitations.findIndex(x => x.id === invitationId);
				if (index < 0)
				{
					const err = new Error("Invalid Id");
					return throwError(err);
				}
				this.invitations.splice(index, 1);
				return of(val);
			}),
			// TODO: requestWatcher call
		);
```

2023-10-15 19:56 UTC, lirik90 commented on src/web/src/styles.css
> +  background: #fff;*/
Не понятный комментарий.)

2023-10-16 03:23 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
Нужен кэш и получать только уникальные space. Описал чуть подробнее в комментах ниже.

2023-10-16 03:34 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		this.getInvites(this.invitesPageSize, this.invitesPageIndex);
Вопрос был в том чтобы проверять на первой ли сейчас странице пагинатор. Т.е. не убирать совсем вызовы getInvites, ...Links, ...Spaces, ...Users, а только тогда когда не на первой.

2023-10-16 03:37 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +	}
Неа. getSpaces всё также вызывается не дожидаясь завершения delSpaceById

2023-10-16 03:38 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +
Можно перенести открывающую фигурную скобку на новую строку. Так будет выглядеть почти так же как и пустая строка.

2023-10-16 03:43 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	getInvitesList(limit: number, page: number): Observable<PaginatorApi<SpaceInvitation>> {
Если не сложно, переименуй ещё пожалуйста в ключах i18n. Но это не обязательно.

2023-10-16 04:05 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		this.getInvites(this.invitesPageSize, this.invitesPageIndex);
А тут, судя по всему, вопрос в другом. Установка lenght у нас вот такая:

[length]="linksTotal"

Поэтому приходится в любом случае вызывать getLinks (...Invitations, ...Spaces и т.д.), так как именно внутри них происходит установка linksTotal, invitationsTotal и т.д.

Без getLinks просто в общем количестве элементов в UI пагинатора не будет корректного числа "до" - например, было 25 элементов, добавляем новый, но последний элемент всё равно 25-ый, а должен быть уже 26-ой.

2023-10-16 04:07 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	}
Да, ты прав. Подойдёт, если вот так будет переписано?

```
onSpaceDelBtn(space: Space){
		this.space.delSpaceById(space.id).pipe(
			src => this.requestWatcher.WatchFor(src)
		).subscribe(res => {
			this.spacesPaginator.firstPage();
			this.getSpaces(this.spacesPageSize, 0);
		});
	}
```

2023-10-16 04:10 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +	@ViewChild('appSpinner') appSpinner: ElementRef;
Убрал.

2023-10-16 04:10 UTC, prt0117 commented on src/web/src/app/app.component.html
> +</app-progress-spinner>
Готово.

2023-10-16 04:21 UTC, prt0117 commented on src/web/src/app/app.module.ts
> +import { ProgressSpinnerComponent } from './progress-spinner/progress-spinner.component';
Готово.

2023-10-16 04:23 UTC, prt0117 commented on src/web/src/app/progress-spinner/progress-spinner.component.ts
> +	@Input() displayProgressSpinner: boolean;
Готово.

2023-10-16 04:25 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +	public displayProgressSpinner = false;
Готово.

2023-10-16 04:37 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +	appSpinner: TemplateRef<any>;
Переименовал.

2023-10-16 04:38 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +	private progressSpinnerOverlayConfig: OverlayConfig;
Так оно же используется далее по коду.

2023-10-16 04:39 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +	}
Готово.

2023-10-16 04:40 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +		this.overlayRef = this.createOverlay(this.progressSpinnerOverlayConfig);
Готово.

2023-10-16 04:42 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +	setProgressSpinner(appSpinner: TemplateRef<any>, vcRef: ViewContainerRef) {
Готово.

2023-10-16 04:50 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +	}
Готово.

2023-10-16 04:51 UTC, prt0117 commented on src/web/src/app/request-watcher/service.ts
> +		alert(msg);
Готово.

2023-10-16 04:55 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +export class SpaceKeyValidation implements AsyncValidator {
Пока только в SpaceAdd должен использоваться.

А как тогда, если не выносить? В том же файле, где компонент SpaceAdd у нас, класс валидатора разместить?

2023-10-16 05:00 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +			);
Сократил, но не до конца, как в твоём предложенной коде. Без ретурна на нижнем уровне не захотело работать так же, как и с тернарным оператором.

2023-10-16 05:19 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +	spaces: Observable<Space[]>;
Готово.

2023-10-16 05:21 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +				createdAt: option.value.createdAt
Почему нет? option.valuе в данном случае - это Space. А в Space есть createdAt.

2023-10-16 05:22 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +
Готово.

2023-10-16 05:26 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		});
Объединил. Работает. debounceTime разный, так как за основу брались разные ответы на SO)

2023-10-16 05:30 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		}
Убрал условие.

2023-10-16 05:39 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +	};
Готово.

2023-10-16 05:52 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			).subscribe(res => {
Готово.

2023-10-16 05:52 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			.pipe(delay(2000));
Готово.

2023-10-16 05:56 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +			<div class="left-float left-padding"><button mat-icon-button type="submit" i18n=""><mat-icon>done</mat-icon></button></div>
Готово.

2023-10-16 06:15 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +						<mat-option value="guest" i18n="" selected>Гость</mat-option>
Готово.

2023-10-16 06:25 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator #linksPaginator class="width-and-clear" [length]="linksTotal" [pageSize]="linksPageSize" [pageSizeOptions]="[7, 15, 30, 100]" (page)="getLinks($event.pageSize, $event.pageIndex); saveP
У нас в некоторых местах компонента getLinks вызывается вот так:
this.getLinks(this.linksPageSize, 0);
То есть без параметров, необходимых для savePageSizeToLocalStorage().
Можно сделать эти параметры необязательными - тебя так устроит?

2023-10-16 06:39 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	usersPageSize: number = 10;
Готово.

2023-10-16 06:45 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.usersPageSize = pageSize ? parseInt(pageSize) : 10;
В этом случае при сохранении трёх разных pageSize в рамках компонента тоже нужно будет в общем json записывать? А также придётся сначала, видимо, структуру считывать из localStorage, чтобы получить два остальных pageSize, которые не меняются, и после этого уже сохранять тройную структуру в localStorage. Так нормально будет?

2023-10-16 06:58 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	currentUserId: string = "2";
Готово.

2023-10-16 08:03 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	}
Да, конечно. Готово.

2023-10-16 08:11 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	}
Готово.

2023-10-16 08:12 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +<mat-paginator #linksPaginator class="width-and-clear" [length]="linksTotal" [pageSize]="linksPageSize" [pageSizeOptions]="[7, 15, 30, 100]" (page)="getLinks($event.pageSize, $event.pageIndex); saveP
Готово.

2023-10-16 08:30 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.usersPageSize = pageSize ? parseInt(pageSize) : 10;
Готово.

2023-10-16 08:31 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +}
Сделал, но условие не понял.

2023-10-16 08:49 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			//.pipe(delay(2000));
Вот конкретно с задержкой в этом месте у нас не работает страница SpaceList, так как на каждый инвайт должен быть запрос вот этот getById для вывода названия пространства. И то же самое для каждой ссылки-приглашения. Я уже писал об этом выше, что нужно иначе как-то запрашивать допинформацию о пространстве (нас интересует имя пространства).

2023-10-16 08:54 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			//.pipe(delay(2000));
В этой ситуации советуют реализовать custom [pipe](https://stackoverflow.com/questions/62289451/angular-async-function-call-from-template). Что думаешь? Или будем хранить название пространства в таблицах с приглашениями и ссылками?

2023-10-16 08:54 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +</div>
Готово.

2023-10-16 08:55 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	currentSpaceLoaded = false;
Убрал, готово.

2023-10-16 09:16 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	}
Готово (везде).

2023-10-16 09:43 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.linksPaginator.firstPage();
Так и сделал. Работает. Поменял везде.

2023-10-16 09:47 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +		return of(user);
С delay не работает, так как на каждую строчку приглашения на странице List идёт такой запрос. Надо как-то переписывать. И память выедается + CPU 100%.

2023-10-16 09:47 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +		return of(user);
С delay не работает, так как на каждую строчку приглашения на странице List идёт такой запрос. Надо как-то переписывать. И память выедается + CPU 100%.

2023-10-16 10:04 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +		<div class="left-float left-padding">{{getUserEmailById(user.userId)}}</div>
matNativeControl - это рудимент от старой реализации селекта ("некрасивого"). Удалил.

matTooltip реализовал - не очень красиво, но работает.

2023-10-16 10:16 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +
А в SpaceListComponent мы тоже можем расширить типы SpaceInvitation и LinkInvitation, чтобы в них было имя пространства (например, "Пространство №1")?

2023-10-16 10:17 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	users: SpaceUser[] = [];
А как это отразится на наших тестовых данных? Правильно ли я понимаю, что мы можем расширить наши тестовые массивыми нужными нам полями?

2023-10-16 10:19 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	}
1. А можем ли мы вернуть return изнутри subscribe? В этом случае вернётся корректно значение после того, как оно будет получено с бэка?

```
	getUserNameById(userId: string) {
		let name;
		this.user.getById(userId)
		.subscribe(res => {
			return res.name;
		});
	}
```

2. Ок, так и сделаю. Запланировал на завтра на утро переписывать этот момент.

2023-10-16 10:21 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +					<mat-hint i18n="">Логин пользователя</mat-hint>
Готово (заполнил везде).

2023-10-16 10:22 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +					<input matInput type="text" formControlName="username" required />
Ок, запланировал на завтра.

2023-10-16 10:30 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +		<form [formGroup]="invitationForm" [hidden]="isInvitationFormHidden" (ngSubmit)="onSubmitInvitation(invitationForm)">
Да, действительно:) Поправил.

2023-10-16 10:35 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +				this.usersTotal = res.count;
Ок, подумаю, как это сделать. Запланировал на завтра.

2023-10-16 10:41 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +			<form [formGroup]="invitationForm" [hidden]="isInvitationFormHidden" (ngSubmit)="onSubmitInvitation(invitationForm)">
Получается, тут нужно при нажатии на кнопку раскрытия формы создавать форму, чтобы ngIf сработал? А при закрытии формы нужно переменной формы присваивать null? Ок, на завтра запланировал.

2023-10-16 10:43 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	}
Ок, запланировал приступать к этому на завтра.

2023-10-16 10:44 UTC, prt0117 commented on src/web/src/app/space/model.ts
> +// need to clarify
А уже сам не помню)) Удалил) Скорее всего, какой-то рудимент от старой версии модели.

2023-10-16 10:45 UTC, prt0117 commented on src/web/src/app/space/request-sent/component.ts
> +	}
Удалил, проверил, всё прекрасно работает и без неё.

2023-10-16 10:48 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			pipe(delay(2000));
Ок, на завтра запланировал таймаут перенести.

-1 взят с ответа на SO)

2023-10-16 10:50 UTC, prt0117 commented on src/web/src/styles.css
> +  background: #fff;*/
Это сделало спиннер без квадрата белого на фоне)

2023-10-17 08:22 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +	}
Готово.

2023-10-17 08:23 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			//.pipe(delay(2000));
Готово (сделано через кэш).

2023-10-17 08:23 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +		return of(user);
Готово (ты добавил)), всё работает.

2023-10-17 08:23 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +		return of(user);
Готово (ты добавил)), всё работает.

2023-10-17 08:24 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +
Готово.

2023-10-17 08:24 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	users: SpaceUser[] = [];
Готово.

2023-10-17 08:37 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	}
Готово.

2023-10-17 08:38 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +				this.usersTotal = res.count;
Готово.

2023-10-17 09:25 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			pipe(delay(2000));
Готово, -1 был взял с ответа в SO.

2023-10-17 09:45 UTC, prt0117 commented on src/web/src/app/space/list/component.html
> +			<form [formGroup]="invitationForm" [hidden]="isInvitationFormHidden" (ngSubmit)="onSubmitInvitation(invitationForm)">
Готово.

2023-10-17 10:49 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +					<input matInput type="text" formControlName="username" required />
Начал, написал автокомплит на странице Space Detail. Пока WIP. Но визуально автокомплит уже работает, можно потыкать, завтра утром планирую продолжить.

2023-10-18 02:04 UTC, lirik90 requested changes

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +import {ChangeDetectorRef, Component, OnInit, OnDestroy, LOCALE_ID, Inject, ViewChild, ElementRef } from '@angular/core';
ViewChild, ElementRef точно нужны? Кажется не используются.

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +				createdAt: option.value.createdAt
Точно, извини, не заметил. (
Но тогда почему не так?
```typescript
if (option?.value)
  this.selectedSpace = option.value;
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	users: SpaceUser[] = [];
Нет, данные которые с бэка приходят имеют тип SpaceUser, а уже в этом компоненте мы расширяем эти данные дополнительными полями которые нам тут нужны.

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +export class SpaceKeyValidation implements AsyncValidator {
А зачем целый класс? Почему просто функцию эту туда не переместить? Или так не работает?

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +				if (this.usersPaginator) {
Кажется тут должно быть что-то такое:
```suggestion
				if (this.usersPaginator.pageIndex == 0) {
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			//.pipe(delay(2000));
Просто на каждый инвайт не должен быть запрос getById. Когда сделаем кэш как описано в комментах в тех компонентах, всё будет работать как надо.

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +}
this.pageSize это у нас структура с полями invitations, links, users. В эту функцию в id мы передаём имя одного из поля структуры. Получаем значение поля и сравниваем с новым значением. Если значение не изменилось, то выходим, т.к. не нужно в localStorage обновлять.

А ты проверил не вызывается ли запрос списка два раза если исходный this.pageSize обновлять?

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/styles.css
> +  background: #fff;*/
Очень часто хочется оставить какой то код который раньше был очень полезен. Хочется просто закомментировать и пусть полежит до лучших времён. Но по факту такие времена никогда не наступают, а если что-то подобное понадобится, то с учётом того что тут это не применимо потому что ломает новый прогресс спинер, гораздо проще будет заново написать, чем копаться в закомментированном коде. =)

Удаляй. В гит закомментированный код пушить не нужно, только если это реально какая то разовая акция чтобы что-то проверить.

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			});
1. А в каких случаях тут res может быть false ?
2. C true сравнивать не обязательно. Лучше просто if (res)
```suggestion
			.subscribe(_ => this.router.navigate(['space/list']));
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +			}, err => console.warn(err));
Ошибка уже логируется в requestWatcher.

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +			}, err => console.warn(err));
Ошибка уже логируется в requestWatcher. Тут это больше не нужно.
```suggestion
			});
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +			}, err => console.warn(err));
Ошибка уже логируется в requestWatcher. Тут это больше не нужно.

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/model.ts
> +}
Вместо userLogin предлагаю использовать тип UserFields
```suggestion
export type SpaceFields = {
	spaceName: string;
}
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +type SpaceLinkDetail = SpaceLink & SpaceLinkFields;
```suggestion
type SpaceInvitationDetail = SpaceInvitation & SpaceFields & UserFields;
type SpaceLinkDetail = SpaceLink & SpaceFields;
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillInvitationDetailFields(this.invitations);
```suggestion
				this.space.fillFields(this.invitations);
				this.user.fillFields(this.invitations);
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillLinkDetailFields(this.links);
```suggestion
				this.space.fillFields(this.links);
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/user/model.ts
> +export type UserFields = Pick<User, 'displayName' | 'login' | 'email'>;
Кажется лучше сделать отдельный тип, как ты сделал в space/model
```suggestion
export type UserFields = {
	userDisplayName: string;
	userLogin: string;
	userEmail: string;
}
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/user/service.ts
> +	fillUserFields<T extends UserFields & {userId: string}>(items: T[]) {
```suggestion
	fillFields<T extends UserFields & {userId: string}>(items: T[]) {
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
Тут **"<T extends SpaceFields & {spaceId: string}>"** означает что эта функция может принимать любой массив который содержит объекты в которых есть все поля из SpaceFields и ещё поле spaceId


```suggestion
	fillFields<T extends SpaceFields & {spaceId: string}>(items: T[]) {
		const ids = new Set<string>();
		items.forEach(item => ids.add(item.spaceId));
		for (const id of ids) {
			this.getById(id).subscribe(space => {
				for (const item of items) {
					if (item.spaceId !== space.id)
						continue;
					item.spaceName = space.name;
				}
			});
		}
	}
```

2023-10-18 02:04 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		for (const invitation of invitationsArray) {
У тебя тут получилось простое перекладывание всех значений из одного массива в другой и потом ты проходишь по всему массиву, который идентичен исходному массиву.
```typescript
let invitationsArray: SpaceInvitationDetail[] = [];
invitations.forEach(invite => invitationsArray.push(invite));
for (const invitation of invitationsArray) {...}
```

В той функции которую я писал я использовал Set потому что он хранит только уникальные значения.
```typescript
const ids = new Set<string>();
items.forEach(item => ids.add(item.spaceId));
for (const id of ids) {...}
```

Т.е. сколько бы мы не вызывали:
```typescript
ids.add("7");
ids.add("7");
ids.add("7");
```
В Set (ids) будет только одно значение "7".

Это нужно чтобы собрать уникальные id пространств, поскольку в массиве может быть очень много invitations с одинаковым spaceId, и чтобы не запрашивать с сервера 100 раз отдельными запросами один и тот же space, мы сначала выбираем только уникальные значения, а потом запрашиваем проходя по получившемуся массиву уникальных Idшников.

2023-10-18 04:48 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +import {ChangeDetectorRef, Component, OnInit, OnDestroy, LOCALE_ID, Inject, ViewChild, ElementRef } from '@angular/core';
Убрал.

2023-10-18 04:51 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +				createdAt: option.value.createdAt
Сделал так, как ты предложил. Работает.

2023-10-18 04:52 UTC, prt0117 commented on src/web/src/styles.css
> +  background: #fff;*/
Удалил.

2023-10-18 04:54 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +				if (this.usersPaginator) {
Поменял. Не досмотрел.

2023-10-18 05:01 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +}
Ты пишешь:

"А ты проверил не вызывается ли запрос списка два раза если исходный this.pageSize обновлять?"

Ты имеешь в виду двойной запрос, к примеру, getInvitations()?

2023-10-18 05:07 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			});
Готово.

2023-10-18 05:10 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +			}, err => console.warn(err));
Готово.

2023-10-18 05:11 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +			}, err => console.warn(err));
Убрал.

2023-10-18 05:11 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +			}, err => console.warn(err));
Убрал (везде в функциях удаления, где логирует requestWatcher).

2023-10-18 05:13 UTC, prt0117 commented on src/web/src/app/space/model.ts
> +}
В этом случае для замены SpaceInvitationFields нужно будет унаследоваться одновременно от SpaceFields и UserFields (при этом из UserFields нужно будет взять только Login)?

2023-10-18 05:15 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +type SpaceLinkDetail = SpaceLink & SpaceLinkFields;
А в UserFields ещё 2 дополнительных поля будут (displayName и email). Или это норм, что у нас интерфейс будет не со всеми используемыми лишними полями?

2023-10-18 05:21 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillInvitationDetailFields(this.invitations);
У нас же разные поля добавляются для invitations (spaceName, userLogin) и links (spaceName). Если мы сделаем общий метод fillFields, то нам придётся как-то в коде метода делать проверку, какие именно нам нужны поля, в зависимости от типа T. Пойдёт так?

2023-10-18 05:21 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillLinkDetailFields(this.links);
У нас же разные поля добавляются для invitations (spaceName, userLogin) и links (spaceName). Если мы сделаем общий метод fillFields, то нам придётся как-то в коде метода делать проверку, какие именно нам нужны поля, в зависимости от типа T. Пойдёт так?

2023-10-18 05:22 UTC, prt0117 commented on src/web/src/app/user/model.ts
> +export type UserFields = Pick<User, 'displayName' | 'login' | 'email'>;
Готово.

2023-10-18 05:44 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +	fillUserFields<T extends UserFields & {userId: string}>(items: T[]) {
Готово.

2023-10-18 05:47 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
А точно нужна такая одна универсальная функция? Ведь мы через неё будем дополнять spaceName для links и spaceName+userLogin для invitations. Как я понимаю, если мы захотим именно универсальную функцию, то нужно будет как-то в коде делать проверку на тип T, с которым функция работает в данный момент. И если это тип SpaceLinksDetail, то заполнять только spaceName, а если тип SpaceInvitationDetail, то дополнительно заполнять userLogin. Правильно ли я понимаю целевую логику?

2023-10-18 05:50 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		for (const invitation of invitationsArray) {
Ок, подумаю сейчас, как переписать.

2023-10-18 05:57 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +}
1. Добавить вывод в лог какого нибудь глобального счётчика в самом начале функции например getInvitations. 
2. Перейти в пагинаторе на вторую страницу.
3. Изменить кол-во отображаемых строк в пагинаторе.
4. Посмотреть сколько счётчик насчитал вызовов getInvitations.

2023-10-18 06:01 UTC, lirik90 commented on src/web/src/app/space/model.ts
> +}
Норм. К тому же эти поля возможно когда то в будущем выведем в подсказке при наведении.

2023-10-18 06:01 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +type SpaceLinkDetail = SpaceLink & SpaceLinkFields;
Норм

2023-10-18 06:03 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillInvitationDetailFields(this.invitations);
Не придётся. Видишь тут две функции вызываются. Одна одни поля заполняет, вторая другие.
space.fillFields - заполняет spaceName
user.fillFields - заполняет userDisplayName, userLogin, userEmail

2023-10-18 06:04 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillLinkDetailFields(this.links);
Не пойдёт. См. коммент выше.

2023-10-18 06:05 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
См. коммент выше. Там два вызова. Поля должен заполнять тот кто за них ответственен. SpaceService заполняет поля ServiceFields а UserService поля UserFields

2023-10-18 06:06 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		for (const invitation of invitationsArray) {
Я уже предложил как переписать в комменте выше. См функцию fillFields

2023-10-18 06:12 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +export class SpaceKeyValidation implements AsyncValidator {
Ну мы же наследуемся от AsyncValidator в этом классе. Думаю, должно быть именно так. Но могу проверить, конечно, если хочешь.

2023-10-18 06:16 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +}
Проверил. Не наблюдаю двойных вызовов, только одинарные. При каждом переходе на новую страницу либо при смене кол-ва отображаемых элементов в пагинаторе - каждый раз срабатывает getInvitations(), но по одному разу.

2023-10-18 06:24 UTC, prt0117 commented on src/web/src/app/space/model.ts
> +}
Готово.

2023-10-18 06:24 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +type SpaceLinkDetail = SpaceLink & SpaceLinkFields;
Готово.

2023-10-18 06:27 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillInvitationDetailFields(this.invitations);
Всё понял, готово.

2023-10-18 06:27 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +				this.space.fillLinkDetailFields(this.links);
Понял, готово.

2023-10-18 06:29 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
Понял, спасибо, дошло наконец-то))

2023-10-18 06:29 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		for (const invitation of invitationsArray) {
Да, всё понял, уже готово.

2023-10-18 08:13 UTC, prt0117 commented on src/web/src/app/space/detail/component.html
> +					<input matInput type="text" formControlName="username" required />
Готово - как на странице SpaceDetail, так и на SpaceList.

2023-10-18 22:09 UTC, lirik90 requested changes

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/app.component.ts
> +import { ProgressSpinnerComponent } from './request-watcher/progress-spinner/component';
Кажется это импортируется и не используется.

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		if (pageSize?.invitations && pageSize?.links && pageSize?.users){
Добавь пожалуйста пробел между круглой и фигурной скобкой.
```suggestion
		if (pageSize?.invitations && pageSize?.links && pageSize?.users) {
```

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +			})
```suggestion
			switchMap(value => this.user.getList(10, 0, value || '').pipe(
				map(res => res.results)
			))
```

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +			});
```suggestion
			.subscribe(res => this.currentSpace = res);
```

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +		if (pageSize?.invitations && pageSize?.links && pageSize?.spaces){
```suggestion
		if (pageSize?.invitations && pageSize?.links && pageSize?.spaces) {
```

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/list/component.ts
> +			})
```suggestion
			switchMap(value => this.user.getList(10, 0, value || '').pipe(
				map(res => res.results)
			))
```

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +import {Injectable, Injector} from '@angular/core';
Injector - не используется

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +import { UserService } from '../user/service';
UserService - не используется

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		private injector: Injector,
router и injector не используются
```suggestion
		private requestWatcher: RequestWatcherService,
```

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +import {Router} from '@angular/router';
Router - не используется.

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +type SpaceLinkDetail = SpaceLink & SpaceFields;
Не используется.

2023-10-18 22:09 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +import { UserFields } from '../user/model';
UserFields - не используется

2023-10-18 22:25 UTC, lirik90 requested changes

2023-10-18 22:25 UTC, lirik90 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/:id', component: SpaceDetailComponent, data: {title: 'NAVIGATION.SPACEDETAIL'}},
Извини, пропустил сразу этот момент. Тут должен быть key а не id. Т.е. везде в ссылках которые видит пользователь используем key, а при обращении к бэку используем id
```suggestion
		{path: 'space/:key', component: SpaceDetailComponent, data: {title: 'NAVIGATION.SPACEDETAIL'}},
```

2023-10-19 05:48 UTC, prt0117 commented on src/web/src/app/app.component.ts
> +import { ProgressSpinnerComponent } from './request-watcher/progress-spinner/component';
Готово. Видел подсветку, но думал, что всё равно это нужно для рендеринга тега спиннера в шаблоне.

2023-10-19 05:50 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		if (pageSize?.invitations && pageSize?.links && pageSize?.users){
Готово (везде так сделал).

2023-10-19 05:54 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +			})
Готово.

2023-10-19 05:55 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +			});
Готово.

2023-10-19 05:55 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +		if (pageSize?.invitations && pageSize?.links && pageSize?.spaces){
Готово.

2023-10-19 05:58 UTC, prt0117 commented on src/web/src/app/space/list/component.ts
> +			})
Готово.

2023-10-19 05:59 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +import {Injectable, Injector} from '@angular/core';
Готово.

2023-10-19 06:00 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +import { UserService } from '../user/service';
Готово.

2023-10-19 06:00 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		private injector: Injector,
Готово.

2023-10-19 06:00 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +import {Router} from '@angular/router';
Готово.

2023-10-19 06:00 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +type SpaceLinkDetail = SpaceLink & SpaceFields;
Готово.

2023-10-19 06:00 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +import { UserFields } from '../user/model';
Готово.

2023-10-19 06:11 UTC, prt0117 commented on src/web/src/app/app-routing.module.ts
> +		{path: 'space/:id', component: SpaceDetailComponent, data: {title: 'NAVIGATION.SPACEDETAIL'}},
Не проблема. Готово.

2023-10-20 01:41 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +export class SpaceKeyValidation implements AsyncValidator {
Ты его используешь как функцию. Т.е. наследование от AsyncValidator ни как в данном случае не работает, и передав потом эту функцию в formBuilder он не подозревает что эта функция взята из класса AsyncValidator, по тому что объект класса не передаётся.

Вроде как AsyncValidator используется для создания директив.

2023-10-20 02:25 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +}
Спасибо что проверил!

2023-10-20 02:48 UTC, lirik90 requested changes

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +import { User } from '../../user/model';
```suggestion
import { User, UserFields } from '../../user/model';
```

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +import { SpaceUser } from '../model';
```suggestion
import { Space, SpaceInvitation, SpaceLink, SpaceUser } from '../model';
```

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	currentSpaceKey;
Это лишнее. currentSpaceKey в одном месте используется, а вместо currentUserId лучше использовать currentSpace.id

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		this.getInitData();
```suggestion
		const key = this.route.snapshot.paramMap.get('key');
		this.getInitData(key);
```

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +	}
```suggestion
	getInitData(key) {
		this.space.getByKey(key)
			.subscribe(res => {
				this.currentSpace = res;
				this.getInvitations(this.pageSize.invitations, 0);
				this.getLinks(this.pageSize.links, 0);
				this.getUsers(this.pageSize.users, 0);
		});
	}
```

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/detail/component.ts
> +		this.space.getInvitationListForSpace(this.currentSpaceId, limit, page)
```suggestion
		this.space.getInvitationListForSpace(this.currentSpace.id, limit, page)
```

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +			<mat-hint class="smaller-font red" *ngIf="createForm.get('key').errors?.keyExists">Ключ занят</mat-hint>
Проверь пожалуйста чтобы везде были ключи i18n

2023-10-20 02:48 UTC, lirik90 commented on src/web/src/app/app.component.html
> +        <span *ngIf="current_lang_ !== undefined" [class]="current_lang_.icon"></span>
Проверь пожалуйста чтобы везде в новом коде были табы вместо пробелов и чтобы не было пробелов в конце строки.
```suggestion
	 <span *ngIf="current_lang_ !== undefined" [class]="current_lang_.icon"></span>
```

Можно попробовать как то автоматически если если идее или какой нибудь вот такой командой:
```bash
git -c core.whitespace=indent-with-non-tab diff --ws-error-highlight=all develop
```

Хотя такая команда почему то не всегда показывает. Например в этом файле в строке 41 не сработала. ((

2023-10-20 04:11 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.getInitData();
Готово.

2023-10-20 04:12 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	currentSpaceKey;
Готово.

2023-10-20 04:12 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +import { SpaceUser } from '../model';
Готово.

2023-10-20 04:12 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +import { User } from '../../user/model';
Готово.

2023-10-20 04:12 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +	}
Готово.

2023-10-20 04:13 UTC, prt0117 commented on src/web/src/app/space/detail/component.ts
> +		this.space.getInvitationListForSpace(this.currentSpaceId, limit, page)
Готово.

2023-10-20 04:17 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +			<mat-hint class="smaller-font red" *ngIf="createForm.get('key').errors?.keyExists">Ключ занят</mat-hint>
Проверил.

2023-10-20 04:26 UTC, prt0117 commented on src/web/src/app/app.component.html
> +        <span *ngIf="current_lang_ !== undefined" [class]="current_lang_.icon"></span>
Готово.

2023-10-27 02:16 UTC, lirik90 requested changes

2023-10-27 02:16 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +		<mat-hint class="red" *ngIf="!isSpaces && !firstGetList" i18n="@@SPACE.ADD.JOINFORM.SPACENOTFOUND">Простраства не найдены</mat-hint>
"Простраства не найдены" нужно показывать только тогда когда мы действительно проверили и получили ответ что они не найдены. Сейчас эта подсказка показывается вообще всегда, в том числе когда пользователь набирает новый текст.
```suggestion
		<mat-hint class="red" *ngIf="!isSpaces && !firstGetList" i18n="@@SPACE.ADD.JOINFORM.SPACENOTFOUND">Пространства не найдены</mat-hint>
```

2023-10-27 02:16 UTC, lirik90 commented on src/web/src/app/space/add/component.html
> +		<mat-hint class="red" *ngIf="createForm.get('key').errors?.['pattern']" i18n="@@SPACE.ADD.CREATE.KEYPATTERN">Допустимые символы - a..z, 0..9</mat-hint>
```suggestion
		<mat-hint class="red" *ngIf="createForm.get('key').errors?.['pattern']" i18n="@@SPACE.ADD.CREATE.KEYPATTERN">Допустимые символы: _, a..z, 0..9</mat-hint>
```

2023-10-27 02:16 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +					})
```suggestion
					map(res => {
						this.firstGetList = false;
						this.isSpaces = res.results.length > 0;
						return res.results
					})
```

2023-10-27 02:16 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.css
> +}
Если используешь в нескольких местах .red вынеси его в space/common.css

2023-10-27 02:16 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.html
> +					<input matInput type="text" formControlName="login" [matAutocomplete]="auto" required spaceUserExists (input)="onLoginChange($event.target.value)"/>
Пользователь существует если его выбрали из выпадающего списка.
```suggestion
					<input matInput type="text" formControlName="login" [matAutocomplete]="auto" required (input)="onLoginChange($event.target.value)"/>
```

2023-10-27 04:34 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +		<mat-hint class="red" *ngIf="!isSpaces && !firstGetList" i18n="@@SPACE.ADD.JOINFORM.SPACENOTFOUND">Простраства не найдены</mat-hint>
Вроде, поправил.

2023-10-27 04:46 UTC, prt0117 commented on src/web/src/app/space/add/component.html
> +		<mat-hint class="red" *ngIf="createForm.get('key').errors?.['pattern']" i18n="@@SPACE.ADD.CREATE.KEYPATTERN">Допустимые символы - a..z, 0..9</mat-hint>
Готово.

2023-10-27 04:51 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +					})
Готово.

2023-10-27 04:51 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.css
> +}
Готово (ты уже вынес).

2023-10-27 05:16 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.html
> +					<input matInput type="text" formControlName="login" [matAutocomplete]="auto" required spaceUserExists (input)="onLoginChange($event.target.value)"/>
Готово (убрал директиву, условия переписал).

2023-11-03 02:48 UTC, lirik90 requested changes

2023-11-03 02:48 UTC, lirik90 commented on src/web/src/app/user/service.ts
> +	}
Кажется эта функция не используется.

2023-11-03 02:48 UTC, lirik90 commented on src/web/src/app/user/service.ts
> +	}
Кажется функция не используется.

2023-11-03 02:48 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			tap(_ => { this.isGettingSpaces = true; }),
Тут фигурные скобки не нужны.
```suggestion
			tap(_ => this.hasSpaces = false),
```

2023-11-03 02:48 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +	isGettingSpaces: boolean = false;
1. предлагаю переименовать isSpaces -> hasSpaces
2. может будет достаточно hasSpaces и делать hasSpaces = false в 38 строке?
3. firstGetList - кажется ничего не делает
4. Тоже самое в invitation-list: (isGettingUsers, firstGetUsers, isUsers) -> hasUsers

2023-11-03 02:48 UTC, lirik90 commented on src/web/src/app/space/link-list/component.html
> +					<mat-hint class="red" *ngIf="form.get('name').errors?.['pattern']" i18n="@@SPACE.LIST.CREATELINK.NAMEPATTERN">Допустимые символы: a..z, 0..9 и _</mat-hint>
Кажется тут и везде в других местах квадратные скобки и кавычки лишние.
```suggestion
					<mat-hint class="red" *ngIf="form.get('name').errors?.required" i18n="@@SPACE.LIST.CREATELINK.NAMEREQUIRED">Введите название ссылки</mat-hint>
					<mat-hint class="red" *ngIf="form.get('name').errors?.pattern" i18n="@@SPACE.LIST.CREATELINK.NAMEPATTERN">Допустимые символы: a..z, 0..9 и _</mat-hint>
```

2023-11-03 03:43 UTC, lirik90 requested changes

2023-11-03 03:43 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request'], navigationExtras);
Тут должен отправляться запрос к серверу и если успешно, то тогда уже отправлять пользователя на страницу с space/add/request

2023-11-03 03:46 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +				return this.space.getList(10, 0, value || '').pipe(
Тут мы должны получить список доступных для вступления, а не список тех в которых уже состоит пользователь.
```suggestion
				return this.space.getAvailableList(10, 0, value || '').pipe(
```

2023-11-03 04:16 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			]],
Нужна проверка не занят ли ключ.

2023-11-03 04:18 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	delSpaceById(spaceId: string): Observable<boolean> {
По аналогии с другими методами относящимися к Space, давай пожалуйста переименуем delSpaceById -> delById

2023-11-03 04:22 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.html
> +				</mat-form-field>
Изменение роли должно приводить к запросу на сервер на изменение роли. Пока запрос выполняется, select давай блокировать.

2023-11-03 04:24 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.html
> +			</div>
Нажатие на эти кнопки должно приводить к отправке запроса на сервер. При нажатии на кнопку, давай пожалуйста блокировать кнопку, а после выполнения запроса нужно обновлять список.

2023-11-03 04:47 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +	}
Точно, удалил.

2023-11-03 04:47 UTC, prt0117 commented on src/web/src/app/user/service.ts
> +	}
Точно, удалил.

2023-11-03 04:49 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			tap(_ => { this.isGettingSpaces = true; }),
Готово.

2023-11-03 04:53 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +	isGettingSpaces: boolean = false;
Готово.

2023-11-03 04:57 UTC, prt0117 commented on src/web/src/app/space/link-list/component.html
> +					<mat-hint class="red" *ngIf="form.get('name').errors?.['pattern']" i18n="@@SPACE.LIST.CREATELINK.NAMEPATTERN">Допустимые символы: a..z, 0..9 и _</mat-hint>
Готово.

2023-11-03 05:16 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +		this.router.navigate(['space/add/request'], navigationExtras);
Готово.

2023-11-03 05:49 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +				return this.space.getList(10, 0, value || '').pipe(
Готово.

2023-11-03 05:51 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
> +			]],
Проверка осуществляется через директиву spaceKeyExists (https://github.com/svetit-io/svetit/blob/feature/19-ms-spaces/src/web/src/app/space/add/component.html#L36 + https://github.com/svetit-io/svetit/blob/feature/19-ms-spaces/src/web/src/app/space/add/space-key-validator.ts)

2023-11-03 05:52 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	delSpaceById(spaceId: string): Observable<boolean> {
Готово.

2023-11-03 06:22 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	getUserListForSpace(spaceId: string, limit: number, page: number): Observable<PaginatorApi<SpaceUser>> {
Вот тут ещё давай тоже пожалуйста Space уберём
```suggestion
	getUserList(spaceId: string, limit: number, page: number): Observable<PaginatorApi<SpaceUser>> {
```

2023-11-03 06:26 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
> +			]],
Извини, забыл что там используется spaceKeyExists

2023-11-03 06:35 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.html
> +				</mat-form-field>
Готово.

2023-11-03 06:42 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	getUserListForSpace(spaceId: string, limit: number, page: number): Observable<PaginatorApi<SpaceUser>> {
Готово.

2023-11-03 08:07 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.html
> +			</div>
Готово.

2023-11-08 02:56 UTC, lirik90 approved these changes

2023-11-08 04:16 UTC, merged