Таблица с ролями в мс Пространства
svetit-io/svetit pull request #290
Opened 2024-08-14 04:12 UTC by prt0117

2024-08-15 11:45 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
тут заголовок поменялся основной. и ещё ты говорил про заголовок X-Space-Is-Admin - его тоже нужно создать тут. и конфиг nginx надо переписать. плюс переписать в мс, которые завязаны на эти заголовки. Можно в отдельной задаче, наверное.

2024-08-16 03:06 UTC, lirik90 requested changes

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/db/app/migrations/V0001__Init.sql
> +
```suggestion
```

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
А в каком месте используется этот заголовок? Мы договорились добавлять его только если он где то будет использован.

X-Space-Is-Admin давай в этой задаче сделаем

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/db/app/migrations/V0001__Init.sql
> +
```suggestion
```

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +		const int roleId = 3; // hardcoded admin roleId (3)
А почему тут захардкожен админ? Получается только админ сможет зайти в пространство.
```suggestion
		const auto [space, roleId] = _s.GetSpaceAndRoleId(spaceKey, userId);
```

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/src/model/invitation_serialize.cpp
> +		roleIdOptional = roleIdParsed;
```suggestion
	if (roleIdParsed != 0)
		roleIdOptional = roleIdParsed;
```

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/src/model/role_serialize.cpp
> +	builder["spaceId"] = boost::uuids::to_string(item.spaceId);
Поле spaceId не нужно серилизовать нигде.
```suggestion
```

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/src/repo/repository.cpp
> +// hardcoded admin roleId (3)
На созвоне договорились не хардкодить в репе, а вынести в константы

2024-08-16 03:06 UTC, lirik90 commented on src/back/space/src/repo/repository.cpp
> +	}
Давай проверим так
```suggestion
	const auto res = _db->Execute(ClusterHostType::kMaster, kInsertSpaceInvitation, spaceId, userId, roleId, creatorId, 3); // hardcoded admin roleId (3)
	if (res.IsEmpty())
		throw errors::BadRequest400("Nothing was inserted");
```

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/src/repo/repository.cpp
> +	}
Проверил, работает.

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/src/repo/repository.cpp
> +// hardcoded admin roleId (3)
Забыл, готово, влил.

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/src/model/role_serialize.cpp
> +	builder["spaceId"] = boost::uuids::to_string(item.spaceId);
Готово.

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/src/model/invitation_serialize.cpp
> +		roleIdOptional = roleIdParsed;
Готово.

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +		const int roleId = 3; // hardcoded admin roleId (3)
Переписал, готово, влил.

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/db/app/migrations/V0001__Init.sql
> +
Готово.

2024-08-16 04:48 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
Готово, сделал X-Space-Is-Admin.

2024-08-16 06:06 UTC, lirik90 requested changes

2024-08-16 06:06 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
А на вопрос не ответил) А в каком месте используется этот заголовок? Мы договорились добавлять его только если он где то будет использован.

2024-08-16 06:12 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
Чет я запутался)) Я думал, что ты говоришь сделать как раз Is-Admin, а Role-Id типа не надо)) Тебе виднее глобально, какой нам и где нужен заголовок)) Так какие заголовки реализовать в этом месте?)

2024-08-16 06:14 UTC, lirik90 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
Мы с тобой обсуждали что делаем Is-Admin. И смотрим что если у нас где то раньше было использование заголовка Role не в сравнении с Admin, т.е. например если мы где то вставляем эту роль или ещё что-то и если такое место есть, то только тогда добавляем этот заголовок.

2024-08-16 06:19 UTC, prt0117 commented on src/back/space/src/api/introspect.cpp
> +				req.GetHttpResponse().SetHeader(headers::kSpaceRoleId, data._roleId);
> Мы с тобой обсуждали что делаем Is-Admin. И смотрим что если у нас где то раньше было использование заголовка Role не в сравнении с Admin, т.е. например если мы где то вставляем эту роль или ещё что-то и если такое место есть, то только тогда добавляем этот заголовок. Сейчас нужно проверить где старый заголовок использовался и поправить все места на использование нового заголовка и заодно нужно понять достаточно ли Is-Admin вместо Role

Теперь понял. Я пока вижу только одно место, где мы что-то делали с ролью из заголовка. https://github.com/svetit-io/svetit/blob/develop/src/back/node/src/service/service.cpp#L64 Но тут мы проверяем, админская роль или нет, то есть достаточно X-Space-Is-Admin. А чтобы прямо использовать id роли, например, для вставки - такого не вижу.

2024-08-16 10:41 UTC, lirik90 requested changes

2024-08-16 10:41 UTC, lirik90 commented on src/back/deps/svetit/shared/headers.hpp
> +inline constexpr std::string_view kSpaceRoleId{"X-Space-Role-Id"};
Если не используется, нужно убрать

2024-08-16 10:41 UTC, lirik90 commented on src/back/space/src/model/model.hpp
> +const int GLOBAL_SPACE_ROLE_ADMIN = 3;
Сделай пожалуйста файла src/mode/consts.hpp и в нём константы по аналогии с файлом headers.hpp в deps. В том числе и формат имени

2024-08-16 11:05 UTC, prt0117 commented on src/back/deps/svetit/shared/headers.hpp
> +inline constexpr std::string_view kSpaceRoleId{"X-Space-Role-Id"};
Готово.

2024-08-16 11:05 UTC, prt0117 commented on src/back/space/src/model/model.hpp
> +const int GLOBAL_SPACE_ROLE_ADMIN = 3;
Готово.

2024-08-16 14:20 UTC, lirik90 requested changes

2024-08-16 14:20 UTC, lirik90 commented on src/back/space/src/model/consts.hpp
> +inline constexpr int kRoleAdmin{3};
Сюда же можно добавить и текстовые константы с именами ролей

2024-08-16 14:20 UTC, lirik90 commented on src/web/pipeline/server.nginx.conf
> +	location ~ ^/([^/]+)/(project|space|node|replace_to_another_ms_name)(/.*)?$ {
```suggestion
	location ~ ^/([^/]+)/(project|space|node)(/.*)?$ {
```

2024-08-25 19:29 UTC, lirik90 approved these changes

2024-08-25 19:29 UTC, merged