Feature/41 space join page front
svetit-io/svetit pull request #42
Opened 2023-11-13 08:31 UTC by prt0117

2023-11-13 17:19 UTC, lirik90 requested changes

2023-11-13 17:19 UTC, lirik90 commented on src/web/src/app/space/link-join/component.ts
> +	targetSpace: Space = null;
```suggestion
	targetSpace: Space;
```

2023-11-13 17:19 UTC, lirik90 commented on src/web/src/app/space/link-join/component.ts
> +	}
```suggestion
	ngOnInit() {
		const linkId = this.route.snapshot.paramMap.get('token');
		this.space.getByLink(linkId)
			.subscribe(res => this.targetSpace = res);
	}
```

2023-11-13 17:19 UTC, lirik90 commented on src/web/src/app/space/link-join/component.ts
> +			});
Такое же действие как при отправке запроса на присоединение к публичному space

2023-11-17 06:20 UTC, prt0117 commented on src/web/src/app/space/link-join/component.ts
> +	targetSpace: Space = null;
Готово (только token всё же оставил, так как он потребуется при нажатии на кнопку присоединения к пространству).

2023-11-17 06:20 UTC, prt0117 commented on src/web/src/app/space/link-join/component.ts
> +	}
Готово.

2023-11-17 06:20 UTC, prt0117 commented on src/web/src/app/space/link-join/component.ts
> +			});
Готово.

2023-11-20 03:22 UTC, lirik90 requested changes

2023-11-20 03:22 UTC, lirik90 commented on src/web/src/app/space/link-join/component.html
> +<ng-container *ngIf="targetSpace !== undefined">
```suggestion
<ng-container *ngIf="targetSpace">
```

2023-11-20 03:22 UTC, lirik90 commented on src/web/src/app/space/link-join/component.html
> +	<button (click)="sendJoinRequest()">Отправить запрос</button>
i18n

2023-11-20 03:22 UTC, lirik90 commented on src/web/src/app/space/link-join/component.ts
> +			});
```suggestion
			.subscribe(res => this.targetSpace = res);
```

2023-11-20 03:22 UTC, lirik90 commented on src/web/src/app/space/link-join/component.ts
> +				}
А в каких случаях res может быть false ?
```suggestion
				const navigationExtras: NavigationExtras = {state: {spaceName: this.targetSpace.name}};
				this.router.navigate(['space/add/request'], navigationExtras);
```

2023-11-20 03:22 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	}
Кажется не используется.

2023-11-20 03:47 UTC, prt0117 commented on src/web/src/app/space/link-join/component.html
> +<ng-container *ngIf="targetSpace !== undefined">
Готово.

2023-11-20 03:48 UTC, prt0117 commented on src/web/src/app/space/link-join/component.html
> +	<button (click)="sendJoinRequest()">Отправить запрос</button>
Готово.

2023-11-20 03:48 UTC, prt0117 commented on src/web/src/app/space/link-join/component.ts
> +			});
Готово.

2023-11-20 03:51 UTC, prt0117 commented on src/web/src/app/space/link-join/component.ts
> +				}
Убрал (думаю, для моков точно это не нужно).

2023-11-20 03:52 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	}
Удалил.

2023-11-21 01:49 UTC, lirik90 approved these changes

2023-11-21 05:31 UTC, merged