Feature/43 connect front and back
svetit-io/svetit pull request #44
Opened 2023-11-21 05:43 UTC by prt0117

2023-12-15 03:12 UTC, lirik90 requested changes

2023-12-15 03:12 UTC, lirik90 commented on pipeline/.env.example
> +SPACE_DEFAULT=key1
Давай в этом файле по умолчанию сделаем этот конфиг пустым.
```suggestion
SPACE_DEFAULT=
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/add/component.ts
>  				}
А там могут быть какие то другие не ошибочные статусы? 
```suggestion
				const navigationExtras: NavigationExtras = {state: {spaceName: this.selectedSpace.name}};
				this.router.navigate(['space/add/request'], navigationExtras);
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +		return timer(500).pipe(switchMap(()=>{
А для чего тут таймер?

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +						if (res.status == 200) {
А статус может быть не 200?

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +		if (!item.role){
Добавь пробел пожалуйста везде между круглой и фигурной скобкой
```suggestion
		if (!item.role) {
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +				if (res.status == 200) {
Зачем эта проверка ведь ошибки в другой обработчик попадают ?

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
>  		// TODO: remove next line
Забыл убрать коммент
```suggestion
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
>  		// TODO: uncomment next line
Забыл убрать комменты
```suggestion
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		);
Кажется тут можно чуть короче
```suggestion
		let url = this._apiUrl + "/available/list?start=" + limit*page + "&limit=" + limit;
		if (name)
			url += '&spaceName=' + name;
		return this.http.get<Paging<Space>>(url).pipe(
			src => this.requestWatcher.WatchFor(src)
		);
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
>  	}
```suggestion
	getInvitationList(limit: number, page: number, spaceId: string = null): Observable<Paging<SpaceInvitation>> {
		let url = this._apiUrl + "/invitation?start=" + limit*page + "&limit=" + limit;
		if (spaceId)
			url += '&spaceId=' + spaceId;
		return this.http.get<Paging<SpaceInvitation>>(url).pipe(
			src => this.requestWatcher.WatchFor(src)
		);
	}
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		);
```suggestion
		let url = this._apiUrl + '/invitation/link?start=' + limit*page + '&limit=' + limit;
		if (spaceId)
			url += '&spaceId=' + spaceId;
		return this.http.get<Paging<SpaceLink>>(url).pipe(
			src => this.requestWatcher.WatchFor(src)
		);
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		return this.http.post(this._apiUrl + "/", {
Этот слеш точно необходим?

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			id: "",
Точно ли нужно добавлять пустое поле?

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			pipe(
Перенеси пожалуйста везде либо pipe( в конец предыдущей строки, либо из конца предыдущей строки точку на эту строку.

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		}).pipe(
```suggestion
	changeRoleInInvitation(id: string, role: string): Observable<any> {
		return this.http.put(this._apiUrl + "/invitation?id=" + id, { role }).pipe(
```

2023-12-15 03:12 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	join(spaceId: string, userId: string): Observable<any> {
А что в any на самом деле?

2023-12-15 04:50 UTC, prt0117 commented on src/web/src/app/space/add/component.ts
>  				}
В данном запросе - видимо, нет.

2023-12-15 04:51 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +		return timer(500).pipe(switchMap(()=>{
Чтобы при каждом вводе символа в инпут ключа не улетал мгновенно запрос на бэк на проверку занятости этого ключа. Поэтому небольшая пауза через timer.

2023-12-15 04:53 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +						if (res.status == 200) {
Ещё может быть 400 и 404 (ну и 500). Это сделано для того, чтобы обрабатывать ответ, когда пространство не найдено. Наверное, как-то иначе надо обрабатывать (везде) такие ошибки.

2023-12-15 05:00 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.ts
> +		if (!item.role){
Готово (везде).

2023-12-15 05:08 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.ts
> +				if (res.status == 200) {
Убрал (надо выработать решение для всего мс, как на фронте обрабатывать ответы с ошибками).

2023-12-15 05:14 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		return this.http.post(this._apiUrl + "/", {
Уже нет (раньше был нужен, когда конфиг nginx был другой).

2023-12-15 05:15 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			id: "",
Точно. Или будет 500. Так как в данном запросе парсим тело целиком. Насколько помню, мы с тобой сознательно на это пошли, что с фронта будем передавать все поля даже, если они пустые.

2023-12-15 05:21 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			pipe(
Готово (везде поправил, но сохранил 2 варианта в коде с пайпом - в зависимости от длины строки, к которой он добавляется, но точка в любом случае не стоит отдельно теперь).

2023-12-15 05:26 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	join(spaceId: string, userId: string): Observable<any> {
Насколько я понимаю, тут возможно либо ничего в ответе (если 200 ОК), либо json {"err":"error text"} (если ошибка возвращается). Можем, наверное, отдельную структуру использовать, чтобы маппить в неё ответы с ошибкой.

2023-12-17 00:10 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +						if (res.status == 200) {
Любой не 2xx статус улетит в catchError который в 25 строке, а не сюда. Верно?

2023-12-17 00:16 UTC, lirik90 commented on src/web/src/app/space/service.ts
>  	getById(spaceId: string) {
А почему в эти функции не добавил вызов бэка? В рамках этой задачи нужно избавится от this.spaces , this.invitations , this.links, this.users

2023-12-18 01:40 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +	}
Такой общий обработчик ошибок должен быть в сервисе. Убери его пока отсюда. Нечто подобное там уже есть, потом совместим.
Сейчас подобное в src/web/src/app/ischeme.service.ts:79 но пока не используется.

Если этот обработчик нужен чтобы перехватить 404, то тогда сделай перехват в serivce потому что для функции с названием isExists кажется что 404 это корректный результат, поэтому она не должна возвращать ошибку при 404.

2023-12-18 04:43 UTC, prt0117 commented on src/web/src/app/space/service.ts
>  	getById(spaceId: string) {
Готово (оставшиеся вызовы к мс Space доделал, моковые данные все удалил).

2023-12-18 04:48 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +						if (res.status == 200) {
Убрал в данном месте проверку на 200, работает корректно без данной проверки.

2023-12-18 05:02 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +	}
Готово.

2023-12-19 02:26 UTC, lirik90 requested changes

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	changeRoleInInvitation(id: string, role: string): Observable<any> {
Invitation id у нас number
```suggestion
	changeRoleInInvitation(id: number, role: string): Observable<any> {
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +			this.space.changeRoleInInvitation(String(item.id), value)
Зачем тут такое преобразование? Давай так.
```suggestion
			this.space.changeRoleInInvitation(item.id, value)
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +		return timer(500).pipe(switchMap(()=>{
Давай до и после оператора => добавим пробелы.
```suggestion
		return timer(500).pipe(switchMap(() => {
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/add/space-key-validator.ts
> +					})
res - у нас уже должен быть boolean, давай его в значении и верём.
```suggestion
					map(res => ({ 'keyExists': res }))
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +	isExists(key: string): Observable<any> {
isExists - должна возвращать boolean
```suggestion
	isExists(key: string): Observable<boolean> {
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +				}),
Мы должны бросить ошибку дальше если это не 404
```suggestion
				catchError(err => {
					if (err.status == 404)
						return of(false);
					return throwError(() => err);
				}),
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +		return this.http.head(this._apiUrl + "/?key=" + key, { observe: 'response' })
А observe: 'response' это для чего?
```suggestion
		return this.http.head(this._apiUrl + "/?key=" + key)
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +				src => this.requestWatcher.WatchFor(src),
Мы должны преобразовать результат в boolean
```suggestion
				src => this.requestWatcher.WatchFor(src),
				map(_ => true),
```

2023-12-19 02:26 UTC, lirik90 commented on src/web/src/app/space/service.ts
> +			role: "guest",
Нужно в /app/space/model.ts описать enum с ролями и использовать его значения везде в space вместо строковых значений.
```suggestion
			role: SpaceRole.Guest,
```

2023-12-19 05:10 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +		return this.http.head(this._apiUrl + "/?key=" + key, { observe: 'response' })
Чтобы в subscribe можно было статус ответа http получать. Но поскольку мы из subscribe убрали проверки на 200ый статус, то, думаю, уже не нужно.

2023-12-19 05:21 UTC, prt0117 commented on src/web/src/app/space/invitation-list/component.ts
> +			this.space.changeRoleInInvitation(String(item.id), value)
Готово.

2023-12-19 05:22 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +		return timer(500).pipe(switchMap(()=>{
Готово.

2023-12-19 05:22 UTC, prt0117 commented on src/web/src/app/space/add/space-key-validator.ts
> +					})
Готово.

2023-12-19 05:22 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +	isExists(key: string): Observable<any> {
Готово.

2023-12-19 05:22 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +				}),
Готово.

2023-12-19 05:22 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +				src => this.requestWatcher.WatchFor(src),
Готово.

2023-12-19 05:25 UTC, prt0117 commented on src/web/src/app/space/service.ts
> +			role: "guest",
Готово. Но только в одном месте, вроде, пригодилось, если я ничего не напутал.

2023-12-21 01:43 UTC, lirik90 commented on src/web/src/app/space/invitation-list/component.ts
> +			this.space.changeRoleInInvitation(String(item.id), value)
Чот не готово. ((

2023-12-21 01:44 UTC, lirik90 approved these changes

2023-12-21 01:45 UTC, merged