Feature/46 ms space tests
svetit-io/svetit pull request #47
Opened 2023-12-13 05:44 UTC by prt0117

2024-01-29 19:30 UTC, lirik90 requested changes

2024-01-29 19:30 UTC, lirik90 commented on src/back/space/configs/config_vars_from_env.sh
> +TESTING="true"
Для чего это?

2024-01-29 19:30 UTC, lirik90 commented on Makefile
> +	make -C pipeline stop-db
Нельзя ли аргументами передать другой порт для запуска постгреса через тестсьют?

2024-01-29 19:30 UTC, lirik90 commented on src/back/space/tests/test_create_space.py
> +    assert response.status == 409
Давай использовать табы.
Давай не дублировать код там где можно
```suggestion
import pytest

h={'X-User': 'd2f9924d-a69a-4aec-b9c0-c80171d3ed86'},
json={
	'id': '',
	'name': 'test12345678901',
	'key': '67123',
	'requestsAllowed': False,
	'createdAt': 0
}

# run by make test-space or make run-space
@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_no_auth(service_client):
	"""No authorization X-User header"""
	res = await service_client.post('/space', json=json)
	assert res.status == 401


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_valid(service_client):
	"""Valid space creation"""
	res = await service_client.post('/space', json=json, headers=h)
	assert res.status == 201


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_no_name(service_client):
	"""No name param in request json"""
	data = json.copy()
	del data['name']
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 500


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_no_key(service_client):
	"""No key param in request json"""
	data = json.copy()
	del data['key']
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 500


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_no_requests_allowed(service_client):
	"""No requestsAllowed param in request json"""
	data = json.copy()
	del data['requestsAllowed']
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 500


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_key_is_uuid_but_not_as_x_user(service_client):
	"""key is uuid but not equals the caller uuid"""
	data = json.copy()
	data['key'] = '00000000-a69a-4aec-b9c0-c80171d3ed86'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_reserved_key_1(service_client):
	"""using reserved keyword key 1"""
	data = json.copy()
	data['key'] = 'u'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_reserved_key_2(service_client):
	"""using reserved keyword key 2"""
	data = json.copy()
	data['key'] = 'auth'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_reserved_key_3(service_client):
	"""using reserved keyword key 3"""
	data = json.copy()
	data['key'] = 'settings'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_reserved_key_4(service_client):
	"""using reserved keyword key 4"""
	data = json.copy()
	data['key'] = 'main'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_reserved_key_5(service_client):
	"""using reserved keyword key 5"""
	data = json.copy()
	data['key'] = 'api'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_regex_invalid_key_1(service_client):
	"""using invalid by regex key 1"""
	data = json.copy()
	data['key'] = '-123d'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_regex_invalid_key_2(service_client):
	"""using invalid by regex key 2"""
	data = json.copy()
	data['key'] = 'Б123d'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_regex_invalid_key_3(service_client):
	"""using invalid by regex key 3"""
	data = json.copy()
	data['key'] = ''
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_invalid_key_too_long(service_client):
	"""using too long key"""
	data = json.copy()
	data['key'] = '1234567890123456789012345678901234567'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 500


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_name_is_empty(service_client):
	"""using empty name"""
	data = json.copy()
	data['name'] = ''
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 400


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_requests_allowed_is_not_bool(service_client):
	"""requestsAllowed is not bool in request json"""
	data = json.copy()
	data['requestsAllowed'] = 'False'
	res = await service_client.post('/space', json=data, headers=h)
	assert res.status == 500


@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
async def test_create_space_duplicate_key(service_client):
	"""using duplicate key"""
	# creating new space
	res = await service_client.post('/space', json=json, headers=h)
	assert res.status == 201

	# then trying to create one more with same key
	res = await service_client.post('/space', json=json, headers=h)
	assert res.status == 409
```

2024-01-29 19:30 UTC, lirik90 commented on src/back/space/tests/test_get_invitations.py
> +@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
А почему первый параметр dbname = "V0001__Init" а не "space" или "app" например?

2024-01-29 19:30 UTC, lirik90 commented on src/back/space/tests/test_get_invitations.py
> +@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
Из доки к тестсьюту:
"Use this mark to override specify extra data fixtures in a per-test manner."
А зачем нам перезаписывать данные в базе каждый раз для каждого теста?

2024-01-30 03:18 UTC, prt0117 commented on src/back/space/configs/config_vars_from_env.sh
> +TESTING="true"
Без этого при каждом make run-bin-% перегенерируется config_vars.yaml, в котором is_testing ставится false, и make test-%, make run-% перестают работать (testsuite не стартует, судя по всему).

2024-01-30 03:24 UTC, prt0117 commented on Makefile
> +	make -C pipeline stop-db
Может и можно, но, как я понимаю, из коробки тестсьют берет db-url из config_vars и подменяет там базу, порт не меняя. Ресерчить?

2024-01-30 03:37 UTC, prt0117 commented on src/back/space/tests/test_create_space.py
> +    assert response.status == 409
По табам - думал, что линтер питона в выводе make test-% ругается на табы и поменял на спейсы, но, судя по всему, (почитал сейчас) он ругался именно на смесь табов и спейсов.

2024-01-30 03:43 UTC, prt0117 commented on src/back/space/tests/test_get_invitations.py
> +@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
Так называется у нас файл с миграциями. Вроде, оно как-то завязано одно друг с другом, так как Тестсьют накатывает же миграции.

2024-01-30 03:46 UTC, prt0117 commented on src/back/space/tests/test_get_invitations.py
> +@pytest.mark.pgsql('V0001__Init', files=['test_data.sql'])
Чтобы тесты не зависили друг от друга и состояние было каждый раз свежее для каждого теста? Может, это и не нужно, но вообще удобно, так как какой-то тест если что-то поменяет в БД, то остальные тесты могут из-за этого падать. Не знаю, как лучше.

Также у нас не решенная проблема - при запуске через make run-% БД пустая, в ней нет моковых данных, поэтому курлом\постманом толком не подергать.

2024-01-30 04:17 UTC, prt0117 commented on src/back/space/tests/test_create_space.py
> +    assert response.status == 409
Вот сейчас поменял везде пробелы на табы - теперь в выводе make test-space куча предупреждений.
![изображение](https://github.com/svetit-io/svetit/assets/134271128/cc8d695d-efea-4147-ae63-fe2f5fb4de6b)
Надо либо отключать это предупреждение как-то вот так https://stackoverflow.com/a/23383744, либо что-то другое.

2024-01-30 04:22 UTC, prt0117 commented on src/back/space/tests/test_create_space.py
> +    assert response.status == 409
Также предлагаю не выносить объявление тел и заголовков запросов в тестах куда-то наверх, как ты в файле test_create_space.py. По-моему, мы очень теряем в этом случае в наглядности. Тесты становятся не читабельными и не однозначными. И их очень трудно будет дорабатывать в этом случае, особенно, если много изменений в изначальной структуре тела.

2024-03-23 05:12 UTC, lirik90 approved these changes

2024-03-23 05:12 UTC, merged