Feature/45 ms auth new endpoints
svetit-io/svetit pull request #48
Opened 2023-12-20 05:28 UTC by prt0117

…tion

2023-12-21 03:09 UTC, lirik90 requested changes

2023-12-21 03:09 UTC, lirik90 commented on pipeline/keycloak/scripts/create_basics.sh
> +kcadm.sh add-roles -r "$REALM" --uusername service-account-"$CLIENT_ID" --cclientid realm-management --rolename view-users
```suggestion
kcadm.sh add-roles -r "$REALM" --uusername default-roles-"$CLIENT_ID" --cclientid realm-management --rolename view-users
```

2023-12-21 03:09 UTC, lirik90 commented on pipeline/keycloak/scripts/create_basics.sh
> +	-s serviceAccountsEnabled=true
```suggestion
	-s enabled=true
```

2023-12-21 04:45 UTC, prt0117 commented on pipeline/keycloak/scripts/create_basics.sh
> +kcadm.sh add-roles -r "$REALM" --uusername service-account-"$CLIENT_ID" --cclientid realm-management --rolename view-users
Так не получилось, но сделал это вот так:
```
kcadm.sh add-roles --rname default-roles-"$REALM" --rolename view-users -r "$REALM" --cclientid realm-management
```

2023-12-26 01:22 UTC, lirik90 requested changes

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/api/user_byid.cpp
> +		}
Давай не использовать else там где можно обойтись без него. Без else код чуть короче и чище.
```suggestion
		if (!req.HasPathArg("id"))
			throw errors::BadRequest400("No id param");

		const auto id = req.GetPathArg("id");
		res = _s.GetUserInfoById(id, sessionId);
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/model/userinfo_serialize.cpp
> +	return list;
```suggestion
	std::vector<UserInfo> list;
	list.reserve(json.GetSize());
	for (auto&& it : json)
	{
		auto info = MapFromOIDCUserInfoById(it);
		list.push_back(std::move(info));
	}
	return list;
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/oidc.cpp
> +				throw e;
Давай 401 не возвращать, чтобы пользователя не выбивало.
```suggestion
			throw e;
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/oidc.cpp
> +				throw errors::BadRequest400("user not found");
А почему 400, а не 404?
```suggestion
				throw errors::NotFound404{};
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/oidc.cpp
> +		}
401 не перехватываем.
```suggestion
		auto res = _http.CreateRequest()
			.get(_urls._userInfoById + queryPart)
			.headers({
				{http::headers::kAuthorization, "Bearer " + token}
			})
			.timeout(std::chrono::seconds{5})
			.perform();
		res->raise_for_status();

		auto json = formats::json::FromString(res->body());
		return model::MapFromOIDCUserInfoList(json);
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/oidc.cpp
> +		}
Компилятор тут warning разве не выдаёт из-за того что нет return? 
```suggestion
		}
		return {};
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +std::vector<model::UserInfo> Service::GetUserInfoList(const std::string& search, const std::string& sessionId, unsigned int start, unsigned int limit) {
Вместо unsigned int давай использовать uint32_t 
Извини, пропустил этот момент в space. Давай там тоже поправим. Могу отдельную задачу завести или сразу в этой же.
```suggestion
std::vector<model::UserInfo> Service::GetUserInfoList(const std::string& search, const std::string& sessionId, uint32_t start, uint32_t limit) {
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +}
Давай вынесем кусок получения сессии во что то вроде getFrashSession. И в функции GetUserInfo тоже.
```suggestion
model::Session Service::GetUserInfoById(const std::string& id, const std::string& sessionId)
{
	// Получаем сессию из базы
	auto session = _session.Table().Get(sessionId);

	// Обновляем OIDC токены если требуется
	if (_tokenizer.IsExpired(session._accessToken))
	{
		// TODO: dest lock!
		updateTokens(session);
		_session.Table().UpdateTokens(session);
	}
	return session;
}

model::UserInfo Service::GetUserInfoById(const std::string& id, const std::string& sessionId)
{
	auto session = getFrashSession(sessionId);
	return _oidc.GetUserInfoById(id, session._accessToken);
}
```

2023-12-26 01:22 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	}
```suggestion
	auto session = getFrashSession(sessionId);
```

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/api/user_byid.cpp
> +		}
Готово.

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/model/userinfo_serialize.cpp
> +	return list;
Готово.

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/service/oidc.cpp
> +				throw errors::BadRequest400("user not found");
Готово.

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/service/oidc.cpp
> +				throw e;
Готово.

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/service/oidc.cpp
> +		}
Готово.

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/service/oidc.cpp
> +		}
Готово.

2023-12-26 04:14 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +std::vector<model::UserInfo> Service::GetUserInfoList(const std::string& search, const std::string& sessionId, unsigned int start, unsigned int limit) {
Готово. Везде поправлю в рамках этой задачи.

2023-12-26 04:18 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +}
Готово.

2023-12-26 04:27 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	}
Готово.

2023-12-27 01:35 UTC, lirik90 requested changes

2023-12-27 01:35 UTC, lirik90 commented on src/back/auth/src/service/oidc.hpp
> +	std::vector<model::UserInfo> GetUserInfoList(const std::string& search, const std::string& token, unsigned int start, unsigned int limit);
Замени пожалуйста unsigned int на uint32_t

2023-12-27 01:35 UTC, lirik90 commented on src/back/auth/src/service/service.hpp
> +	std::vector<model::UserInfo> GetUserInfoList(const std::string& search, const std::string& sessionId, unsigned int start, unsigned int limit);
Замени пожалуйста unsigned int на uint32_t

2023-12-27 05:06 UTC, lirik90 approved these changes

2023-12-27 05:15 UTC, merged