Бэк мс Проекты
svetit-io/svetit pull request #78
Opened 2024-03-26 11:44 UTC by prt0117

2024-04-10 02:28 UTC, lirik90 requested changes

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/api/cc-di-list.cpp
> +// #include <shared/errors.hpp>
Если не нужно, удали пожалуйста комменты.

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +		.isDeleted = json["isDeleted"].As<bool>()
Давай isDeleted не парсить нигде, в этом кажется нет смысла.

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/cc_type_param.hpp
> +	bool isDeleted;
Добавь пожалуйста значение по умолчанию везде.
```suggestion
	bool isDeleted = false;
```

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +	builder["isDeleted"] = ccTypeParam.isDeleted;
Давай мапить isDeleted, только если он true
```suggestion
	if (ccTypeParam.isDeleted)
		builder["isDeleted"] = ccTypeParam.isDeleted;
```

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +	const CcTypeParam& ccTypeParam,
Давай везде в таких типовых методах использовать одинаковое обобщённое имя (например item или другое), чтобы бы проще копипастить.
```suggestion
	const CcTypeParam& item,
```

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/di_mode.cpp
> +		return "readwrite_flag";
Давай пожалуйста enum ы тут и в базе сразу переведём в camel
```suggestion
		return "readonlyFlag";
	case ReadWriteFlag:
		return "readWriteFlag";
```

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/save_algorithm.cpp
> +		return "by_timer";
```suggestion
		return "byTimer";
```

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/sync_direction.cpp
> +		return "project_to_node";
```suggestion
		return "projectToNode";
```

2024-04-10 02:28 UTC, lirik90 commented on src/back/project/src/model/sync_direction.hpp
> +            .Case("project_to_node", svetit::project::SyncDirection::Type::ProjectToNode)
Тут пробелы
```suggestion
				.Case("projectToNode", svetit::project::SyncDirection::Type::ProjectToNode)
```

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/api/cc-di-list.cpp
> +// #include <shared/errors.hpp>
Это я оставил то, что понадобится, когда появится логика авторизации. Или всё равно удалить?

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/cc_type_param.hpp
> +	bool isDeleted;
Готово.

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +	const CcTypeParam& ccTypeParam,
Готово.

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +	builder["isDeleted"] = ccTypeParam.isDeleted;
Готово.

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +		.isDeleted = json["isDeleted"].As<bool>()
У меня сейчас в некоторых тестах (связующие таблицы) Patch запрос меняет is_deleted с False на True. Такого не может быть в реале?

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/di_mode.cpp
> +		return "readwrite_flag";
Готово.

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/save_algorithm.cpp
> +		return "by_timer";
Готово (везде).

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/sync_direction.cpp
> +		return "project_to_node";
Готово (везде).

2024-04-10 06:16 UTC, prt0117 commented on src/back/project/src/model/sync_direction.hpp
> +            .Case("project_to_node", svetit::project::SyncDirection::Type::ProjectToNode)
Готово.

2024-04-11 01:54 UTC, lirik90 commented on src/back/project/src/api/cc-di-list.cpp
> +// #include <shared/errors.hpp>
Если точно понадобится, тогда раскомментируй.

2024-04-11 02:14 UTC, lirik90 commented on src/back/project/src/model/cc_type_param_serialize.cpp
> +		.isDeleted = json["isDeleted"].As<bool>()
Блин, что-то с этим is_deleted больше проблем чем пользы (( Давай обсудим на созвоне.

2024-04-11 02:34 UTC, lirik90 approved these changes

2024-04-11 02:34 UTC, lirik90 commented on src/back/project/src/api/project.cpp
> +// #include <shared/headers.hpp>
Если не используется, давай уберём.

2024-04-11 02:34 UTC, merged