Feature/2 auth session
svetit-io/svetit pull request #8
Opened 2023-08-29 04:25 UTC by prt0117

2023-08-30 02:24 UTC, lirik90 requested changes

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/api/helpers.hpp
> +std::string getCallerUserAgent(const server::http::HttpRequest& req);
Тут мы получаем Агент который у Юзера, по этому чем короче тем лучше, можно было бы использовать getUserAgent. А выше Caller использовался для того чтобы обозначить что это не URL который был дёргнут в микросервисе, а тот изначальный урл, который дёргал фронт. Т.е. там на проксе идёт преобразование. И фронт дёргает например https://site.com:7777/api/auth/login а при вызове эндпоинта, для МС это уже выглядит как http://auth:8080/auth/login - т.е. и схема другая и домен и порт и путь. По этому там я использовал слово Caller чтобы обозначить что это особенный метод для получения внешнего урла. Он в основном для передачи в кейклоак нужен.
Постараюсь позже добавить коммент к getCallerUrl.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/api/helpers.cpp
> +std::string getCallerUserAgent(const server::http::HttpRequest& req)
Метод слишком простой, предлагаю от него избавится и напрямую вызывать req.GetHeader без проверки на пустую строку, пока что нормально если будем записывать пустую строку в поле device.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/api/helpers.cpp
> +	auto userAgent = req.GetHeader("User-Agent");
У userver есть константы под популярные хидеры. Они советуют использовать их.
```suggestion
	auto userAgent = req.GetHeader(http::headers::kUserAgent);
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/repository.cpp
> +	_session{svetit::auth::table::Session(_pg)}
```suggestion
	, _pg{ctx.FindComponent<components::Postgres>("database").GetCluster()}
	, _state{_pg}
	, _session{_pg}
```

Предлагаю запятые ставить в начале это позволяет менять меньше строк при добавлении новых членов класса и проще менять порядок если он вдруг поменяется в определении.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/api/login_callback.cpp
> +	std::string userAgent = getCallerUserAgent(req);
```suggestion
	std::string userAgent = req.GetHeader(http::headers::kUserAgent);
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/repository.hpp
> +	svetit::auth::table::Session _session;
Полный namespace можно не указывать:
```suggestion
	table::State& State();
	table::Session& Session();

private:
	storages::postgres::ClusterPtr _pg;
	table::State _state;
	table::Session _session;
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/table_state.hpp
> +	    storages::postgres::ClusterPtr pg);
```suggestion
		storages::postgres::ClusterPtr pg);
```

Используем табы, а не пробелы.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/repository.cpp
> +}
```suggestion
table::State& Repository::State() {
	return _state;
}

table::Session& Repository::Session() {
	return _session;
}
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/model/model.hpp
> +struct TokensAndUserData {
Может просто поля добавить в структуру выше?

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +        )
Если у класса один аргумент в конструкторе или если они короткие, то можно без лишних переносов строк.
```suggestion
Session::Session(storages::postgres::ClusterPtr pg)
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +        const bool& active)
Нужно вместо кучи аргументов передавать структуру. Кажется где то выше была модель с такими полями. Или можно сделать новую модель.

встроенные типы по ссылки передавать не нужно по тому что ссылка это хитрый указатель, а его создавать дольше чем сделать новый bool и скопировать значение.)

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/table_session.cpp
> +// }
Если это не нужно лучше просто удалить.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/table_session.hpp
> +        const bool& active);
Используем табы, а не пробелы.
```suggestion
	void Save(
		const std::string& token,
		const std::chrono::system_clock::time_point& created,
		const std::chrono::system_clock::time_point& expired,
		const std::string& userId,
		const std::string& device,
		const std::string& accessToken,
		const std::string& refreshToken,
		const std::string& idToken,
		const bool& active);
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/repo/table_state.cpp
> +	: _pg{pg}
move тут нужен чтобы объект меньшее кол-во раз скопировался.
```suggestion
State::State(storages::postgres::ClusterPtr pg)
	: _pg{std::move(pg)}
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	, _sess{svetit::auth::Session(_rep,_tokenizer)}
```suggestion
	, _sess{_rep,_tokenizer}
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	const TokensAndUserData& tokensAndUserData,
Может лучше расширить Tokens? Т.е. переименовать его в UserData или SessionData, а не создавать новую структуру если Tokens после этого нигде не используется.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	std::string sessionToken = _sess.Save(userId, device, tokensAndUserData._accessToken, tokensAndUserData._refreshToken, tokensAndUserData._logoutToken);
Предлагаю _sess заменить на _session, а _rep я позже заменю на _repo

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/model/model.hpp
> +	std::string
```suggestion
	std::string
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/service.cpp
> +	return tokensAndUserData;
Три раза проверять и парсить один и тот же токен плохо. Нужно сделать это один раз, и потом использовать результат.

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/service.hpp
> +		const TokensAndUserData& tokensAndUserData,
Лучше имя переменной покороче придумывать, если только это не какая то очень специфическая переменная имя которой должно сообщать какую то важную инфу о ней.)
```suggestion
		const TokensAndUserData& data,
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/tokenizer.cpp
> +}
```suggestion
{
}

tokens::OIDC& Tokenizer::OIDC() {
	return _OIDC;
}

tokens::InternalTokens& Tokenizer::InternalTokens() {
	return _internalTokens;
}
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/tokenizer.hpp
> +	svetit::auth::tokens::InternalTokens& InternalTokens();
```suggestion
	tokens::OIDC& OIDC();
	tokens::InternalTokens& InternalTokens();
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/tokenizer.hpp
> +	svetit::auth::tokens::InternalTokens _internalTokens;
```suggestion
	tokens::OIDC _OIDC;
	tokens::InternalTokens _internalTokens;
```

2023-08-30 02:24 UTC, lirik90 commented on src/back/auth/src/service/tokens_internal.hpp
> +class InternalTokens final {
Слово tokens есть в названии namespace
```suggestion
class Internal final {
```

2023-08-30 04:14 UTC, prt0117 commented on src/back/auth/src/api/helpers.hpp
> +std::string getCallerUserAgent(const server::http::HttpRequest& req);
ок. но на основе другого коммента ниже, метод полностью убираем.

2023-08-30 04:14 UTC, prt0117 commented on src/back/auth/src/api/helpers.cpp
> +std::string getCallerUserAgent(const server::http::HttpRequest& req)
метод убрал.

2023-08-30 04:18 UTC, prt0117 commented on src/back/auth/src/api/helpers.cpp
> +	auto userAgent = req.GetHeader("User-Agent");
поменял, использую константу фреймворка.

2023-08-30 04:21 UTC, prt0117 commented on src/back/auth/src/repo/repository.cpp
> +	_session{svetit::auth::table::Session(_pg)}
поменял везде.

2023-08-30 04:21 UTC, prt0117 commented on src/back/auth/src/api/login_callback.cpp
> +	std::string userAgent = getCallerUserAgent(req);
поменял.

2023-08-30 04:26 UTC, prt0117 commented on src/back/auth/src/repo/repository.hpp
> +	svetit::auth::table::Session _session;
поправил везде

2023-08-30 04:55 UTC, prt0117 commented on src/back/auth/src/repo/table_state.hpp
> +	    storages::postgres::ClusterPtr pg);
поменял везде.

2023-08-30 05:00 UTC, prt0117 commented on src/back/auth/src/repo/repository.cpp
> +}
поменял везде

2023-08-30 05:10 UTC, prt0117 commented on src/back/auth/src/model/model.hpp
> +struct TokensAndUserData {
можно, но затронет Service::TokenRefresh, так как там Tokens структура используется. Делаем?

2023-08-30 05:15 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +        )
поправил везде

2023-08-30 05:43 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +        const bool& active)
ок, создал и передаю структуру

2023-08-30 05:43 UTC, prt0117 commented on src/back/auth/src/repo/table_session.cpp
> +// }
удалил

2023-08-30 05:45 UTC, prt0117 commented on src/back/auth/src/repo/table_session.hpp
> +        const bool& active);
поправил

2023-08-30 05:48 UTC, prt0117 commented on src/back/auth/src/repo/table_state.cpp
> +	: _pg{pg}
вот это не понял. предлагаю обсудить, и тогда внесу правки везде, где это нужно.

2023-08-30 05:53 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	, _sess{svetit::auth::Session(_rep,_tokenizer)}
Поправил везде, работает, но до конца не понял этот синтаксис.

2023-08-30 05:55 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	const TokensAndUserData& tokensAndUserData,
можно, но выше писал, что в этом случае будет затронут метод Service::TokenRefresh. делаем?

2023-08-30 05:57 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	std::string sessionToken = _sess.Save(userId, device, tokensAndUserData._accessToken, tokensAndUserData._refreshToken, tokensAndUserData._logoutToken);
заменил

2023-08-30 05:58 UTC, prt0117 commented on src/back/auth/src/model/model.hpp
> +	std::string
готово

2023-08-30 06:16 UTC, prt0117 commented on src/back/auth/src/service/service.cpp
> +	return tokensAndUserData;
реализовал.

2023-08-30 06:22 UTC, prt0117 commented on src/back/auth/src/service/service.hpp
> +		const TokensAndUserData& tokensAndUserData,
поправил.

2023-08-30 06:23 UTC, prt0117 commented on src/back/auth/src/service/tokenizer.cpp
> +}
поправил.

2023-08-30 06:23 UTC, prt0117 commented on src/back/auth/src/service/tokenizer.hpp
> +	svetit::auth::tokens::InternalTokens& InternalTokens();
поправил.

2023-08-30 06:24 UTC, prt0117 commented on src/back/auth/src/service/tokenizer.hpp
> +	svetit::auth::tokens::InternalTokens _internalTokens;
поправил

2023-08-30 06:28 UTC, prt0117 commented on src/back/auth/src/service/tokens_internal.hpp
> +class InternalTokens final {
поправил.

2023-08-31 04:32 UTC, prt0117 commented on src/back/auth/src/model/model.hpp
> +struct TokensAndUserData {
Добавил новые поля в структуру Tokens

2023-08-31 04:44 UTC, prt0117 commented on src/back/auth/src/repo/table_state.cpp
> +	: _pg{pg}
поправил

2023-09-02 02:20 UTC, lirik90 approved these changes

2023-09-04 02:52 UTC, merged