Run specific testsuite test
svetit-io/svetit pull request #80
Opened 2024-03-29 10:25 UTC by prt0117

2024-03-29 10:27 UTC, prt0117 commented
Запускать в текущем варианте нужно вот так:
 make test-specific-project specific="project and not project_param"
Или вот так:
make test-specific-project specific="details"

2024-03-29 10:28 UTC, prt0117 commented
Из не решенных проблем можно выделить наличие большого количества логов в выводе команды запуска теста.

2024-03-29 23:38 UTC, lirik90 requested changes

2024-03-29 23:38 UTC, lirik90 commented on src/back/project/Makefile
> +test-debug test-release: test-%: build-%
Команда называется так же как предыдущая. Она же затрёт её, разве нет?
```suggestion
.PHONY: test-debug-specific test-release-specific
test-debug-specific test-release-specific: test-%: build-%
```

Добавь тогда пожалуйста такие конструкции и в другие МС

2024-03-29 23:38 UTC, lirik90 commented on Makefile
> +	make -C src/back/$* test-debug $(specific)
```suggestion
	make -C src/back/$* test-debug-specific $(specific)
```

2024-04-01 05:31 UTC, prt0117 commented on Makefile
> +	make -C src/back/$* test-debug $(specific)
Готов (только команду назвал не test-debug-specific, а test-specific-debug).

2024-04-01 05:32 UTC, prt0117 commented on src/back/project/Makefile
> +test-debug test-release: test-%: build-%
Готово.

2024-04-02 05:02 UTC, lirik90 approved these changes

2024-04-02 05:02 UTC, merged