Ms Project new logic
svetit-io/svetit pull request #89
Opened 2024-04-10 06:48 UTC by prt0117

2024-04-11 02:53 UTC, lirik90 requested changes

2024-04-11 02:53 UTC, lirik90 commented on src/back/deps/svetit/shared/parse/request.cpp
> +}
Давай может попроще?
```suggestion
bool parseBool(const server::http::HttpRequest& req, const std::string& key)
{
	try {
		const auto value = utils::text::ToLower(req.GetArg(key));
		return value == "true" || value == "1";
	} catch(const std::exception& e) {
		const auto msg = fmt::format("Param {} parse err: {}", key, e.what());
		throw errors::BadRequest400(msg);
	}
	return false;
}
```

Нужно добавить инклуд
```cpp
#include <userver/utils/text.hpp>
```

2024-04-11 02:53 UTC, lirik90 commented on src/back/project/src/api/project-list.cpp
> +			throw errors::BadRequest400("Too big limit param");
Вроде без валидации решили) Убери пожалуйста.
```suggestion
```

2024-04-11 06:25 UTC, prt0117 commented on src/back/deps/svetit/shared/parse/request.cpp
> +}
Поскольку keepDeleted убираем, то данная функция не нужна. Оставить её на будущее тем не менее?

2024-04-11 06:25 UTC, prt0117 commented on src/back/project/src/api/project-list.cpp
> +			throw errors::BadRequest400("Too big limit param");
Готово.

2024-04-12 02:57 UTC, lirik90 commented on src/back/deps/svetit/shared/parse/request.cpp
> +}
Нет, если не используется, давай уберём.

2024-04-12 02:59 UTC, lirik90 approved these changes

2024-04-12 02:59 UTC, merged