Feature/project new endpoints 1
svetit-io/svetit pull request #90
Opened 2024-04-12 04:47 UTC by prt0117

2024-04-12 06:13 UTC, lirik90 requested changes

2024-04-12 06:13 UTC, lirik90 commented on src/back/project/src/model/param_value_type.hpp
> +struct storages::postgres::io::CppToUserPg<svetit::project::ParamValueType::Type> {
А если это засунуть в namespace
svetit::project
не работает? ((

2024-04-12 06:13 UTC, lirik90 commented on src/back/project/src/service/service.cpp
> +	// is needed to check returned value from insert?
Давай посмотрим как в МС Пространств у нас. В целом кажется если вставилось без ошибок, то ничего не нужно проверять.
```suggestion
```

2024-04-12 06:13 UTC, lirik90 commented on src/back/project/tests/static/test_data.sql
> +(1, 1, 'paramType1', 'Param Type 1', 'Description of Param Type 1', 'int'),
Давай добавим разные данные.

2024-04-12 08:14 UTC, prt0117 commented on src/back/project/src/model/param_value_type.hpp
> +struct storages::postgres::io::CppToUserPg<svetit::project::ParamValueType::Type> {
Не получилось завести. Пробовал вот так внутри namespace svetit::project:
```
template <>
struct ::userver::v2_0_0_rc::storages::postgres::io::traits::CanUseEnumAsStrongTypedef<svetit::project::ParamValueType::Type> : std::true_type {};
```

и вот так:
```
template <>
struct userver::v2_0_0_rc::storages::postgres::io::traits::CanUseEnumAsStrongTypedef<svetit::project::ParamValueType::Type> : std::true_type {};
```
IDE ругается на ошибку:
![изображение](https://github.com/svetit-io/svetit/assets/134271128/4ab90acf-9eed-4743-bec8-85d5bdadbec9)

2024-04-12 08:23 UTC, prt0117 commented on src/back/project/src/service/service.cpp
> +	// is needed to check returned value from insert?
У нас такое в мс Space применяет вот тут https://github.com/svetit-io/svetit/blob/develop/src/back/space/src/repo/repository.cpp#L211 Но тут реально нам надо, чтобы insert возвращал id только что созданного пространства. В других местах, где у нас Insert в мс Space, мы такое не используем. Так что, думаю, если будет нужно, то применим такое в Проектах. А пока не надо.

2024-04-12 09:47 UTC, prt0117 commented on src/back/project/tests/static/test_data.sql
> +(1, 1, 'paramType1', 'Param Type 1', 'Description of Param Type 1', 'int'),
Готово. Сделал через std::optional.

2024-04-18 03:18 UTC, lirik90 approved these changes

2024-04-18 03:18 UTC, merged